#include "sturdy_rs/assets.hpp"

#include <array>
#include <cmath>
#include <cstring>
#include <exception>
#include <filesystem>
#include <span>
#include <string>
#include <string_view>
#include <utility>

#include <Engine/AssetManager.hpp>
#include <Engine/Asset.hpp>
#include <Engine/Engine.hpp>
#include <Engine/GltfImport.hpp>
#include <Renderer/Mesh.hpp>

// Generated by build.rs from src/assets.rs; defines the shared structs/enums declared above.
#include "sturdy_rs/assets_bridge.h"

namespace sturdy_rs::assets {
    namespace {

        namespace E = SFT::Engine;

        static_assert(sizeof(E::Asset) == sizeof(AssetHandle));

        std::string to_std_string(rust::Str text) {
            return std::string{text.data(), text.size()};
        }

        UString to_ustring(rust::Str text) {
            const std::string_view view{text.data(), text.size()};
            if (auto converted = UString::try_from_utf8(view)) {
                return std::move(*converted);
            }
            return UString{};
        }

        rust::String to_rust_string(const UString &text) {
            const auto view = text.cpp_string_view();
            return rust::String::lossy(view.data(), view.size());
        }

        rust::String to_rust_string(const std::filesystem::path &path) {
            const auto text = path.string();
            return rust::String::lossy(text.data(), text.size());
        }

        // `E::Asset`'s private fields (owner_, id_, generation_, type_) and `AssetHandle`'s public
        // ones share layout by construction; this is the same bit-copy trick FFI/Gltf.cpp uses to
        // cross its ABI boundary.
        E::Asset to_engine_asset(const AssetHandle &handle) noexcept {
            E::Asset asset{};
            std::memcpy(&asset, &handle, sizeof(asset));
            return asset;
        }

        AssetHandle to_asset_handle(const E::Asset &asset) noexcept {
            AssetHandle handle{};
            std::memcpy(&handle, &asset, sizeof(handle));
            return handle;
        }

        AssetErrorCode map(E::AssetErrorCode code) noexcept {
            switch (code) {
            case E::AssetErrorCode::InvalidAsset: return AssetErrorCode::InvalidAsset;
            case E::AssetErrorCode::WrongType: return AssetErrorCode::WrongType;
            case E::AssetErrorCode::NotFound: return AssetErrorCode::NotFound;
            case E::AssetErrorCode::IoFailure: return AssetErrorCode::IoFailure;
            case E::AssetErrorCode::DecodeFailure: return AssetErrorCode::DecodeFailure;
            case E::AssetErrorCode::InvalidDescription: return AssetErrorCode::InvalidDescription;
            case E::AssetErrorCode::BackendFailure: return AssetErrorCode::BackendFailure;
            case E::AssetErrorCode::InUse: return AssetErrorCode::InUse;
            case E::AssetErrorCode::Unsupported: return AssetErrorCode::Unsupported;
            }
            return AssetErrorCode::BackendFailure;
        }

        E::TextureColorSpace map(TextureColorSpace v) noexcept {
            return v == TextureColorSpace::Linear ? E::TextureColorSpace::Linear : E::TextureColorSpace::Srgb;
        }

        TextureColorSpace map(E::TextureColorSpace v) noexcept {
            return v == E::TextureColorSpace::Linear ? TextureColorSpace::Linear : TextureColorSpace::Srgb;
        }

        E::TextureKind map(TextureKind v) noexcept {
            switch (v) {
            case TextureKind::ColorAlpha: return E::TextureKind::ColorAlpha;
            case TextureKind::ColorOpaque: return E::TextureKind::ColorOpaque;
            case TextureKind::Mask: return E::TextureKind::Mask;
            case TextureKind::NormalMap: return E::TextureKind::NormalMap;
            case TextureKind::MetallicRoughness: return E::TextureKind::MetallicRoughness;
            }
            return E::TextureKind::ColorAlpha;
        }

        E::TextureDynamicRange map(TextureDynamicRange v) noexcept {
            return v == TextureDynamicRange::Hdr ? E::TextureDynamicRange::Hdr : E::TextureDynamicRange::Sdr;
        }

        E::TexturePixelFormat map(TexturePixelFormat v) noexcept {
            return v == TexturePixelFormat::Rgba16Float ? E::TexturePixelFormat::Rgba16Float
                                                          : E::TexturePixelFormat::Rgba8;
        }

        std::vector<std::byte> to_byte_vector(rust::Slice<const std::uint8_t> bytes) {
            std::vector<std::byte> out(bytes.size());
            if (!bytes.empty()) {
                std::memcpy(out.data(), bytes.data(), bytes.size());
            }
            return out;
        }

        glm::vec3 to_vec3(const std::array<float, 3> &v) noexcept { return glm::vec3{v[0], v[1], v[2]}; }
        glm::vec2 to_vec2(const std::array<float, 2> &v) noexcept { return glm::vec2{v[0], v[1]}; }
        glm::vec4 to_vec4(const std::array<float, 4> &v) noexcept { return glm::vec4{v[0], v[1], v[2], v[3]}; }

        GltfLightKind map(E::GltfLightKind v) noexcept {
            switch (v) {
            case E::GltfLightKind::Directional: return GltfLightKind::Directional;
            case E::GltfLightKind::Point: return GltfLightKind::Point;
            case E::GltfLightKind::Spot: return GltfLightKind::Spot;
            }
            return GltfLightKind::Point;
        }

        void copy_transform(const glm::mat4 &m, std::array<float, 16> &out) noexcept {
            std::memcpy(out.data(), &m, sizeof(float) * 16);
        }

        template <typename Outcome>
        Outcome make_failure(Outcome outcome, AssetErrorCode error, rust::String message) {
            outcome.ok = false;
            outcome.error = error;
            outcome.message = std::move(message);
            return outcome;
        }

        template <typename Outcome>
        Outcome make_failure(AssetErrorCode error, rust::String message) {
            return make_failure(Outcome{}, error, std::move(message));
        }

        template <typename Outcome>
        Outcome make_exception_failure() {
            return make_failure<Outcome>(AssetErrorCode::BackendFailure,
                                         rust::String{"an unexpected C++ exception was caught at the FFI boundary"});
        }

        AssetOutcome asset_outcome(const E::AssetExpected<E::Asset> &result) {
            AssetOutcome outcome{};
            if (result) {
                outcome.ok = true;
                outcome.error = AssetErrorCode::None;
                outcome.asset = to_asset_handle(*result);
                return outcome;
            }
            outcome.ok = false;
            outcome.error = map(result.error().code);
            outcome.message = to_rust_string(result.error().message);
            return outcome;
        }

        StatusOutcome status_outcome(const E::AssetResult &result) {
            StatusOutcome outcome{};
            if (result) {
                outcome.ok = true;
                outcome.error = AssetErrorCode::None;
                return outcome;
            }
            outcome.ok = false;
            outcome.error = map(result.error().code);
            outcome.message = to_rust_string(result.error().message);
            return outcome;
        }

    } // namespace

    AssetOutcome assets_load_texture(EngineView &engine,
                                     rust::Str source,
                                     TextureColorSpace color_space,
                                     TextureKind kind,
                                     rust::Str label,
                                     TextureDynamicRange dynamic_range) {
        try {
            return asset_outcome(engine.assets().load_texture(std::filesystem::path{to_std_string(source)},
                                                               map(color_space), map(kind), to_ustring(label),
                                                               map(dynamic_range)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    AssetOutcome assets_create_texture_from_bytes(EngineView &engine,
                                                  rust::Slice<const std::uint8_t> encoded,
                                                  TextureColorSpace color_space,
                                                  TextureKind kind,
                                                  rust::Str label,
                                                  TextureDynamicRange dynamic_range) {
        try {
            const auto *bytes = reinterpret_cast<const std::byte *>(encoded.data());
            const std::span<const std::byte> span{bytes, encoded.size()};
            return asset_outcome(engine.assets().create_texture_from_encoded_bytes(
                span, map(color_space), map(kind), to_ustring(label), map(dynamic_range)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    AssetOutcome assets_load_texture_streamed(EngineView &engine,
                                              rust::Str source,
                                              TextureColorSpace color_space,
                                              TextureKind kind,
                                              rust::Str label) {
        try {
            return asset_outcome(engine.assets().load_texture_streamed(
                std::filesystem::path{to_std_string(source)}, map(color_space), map(kind), to_ustring(label)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    AssetOutcome assets_create_texture(EngineView &engine,
                                       rust::Slice<const std::uint8_t> pixels,
                                       std::uint32_t width,
                                       std::uint32_t height,
                                       TexturePixelFormat format,
                                       TextureColorSpace color_space,
                                       TextureKind kind,
                                       rust::Str label,
                                       bool allow_compression,
                                       bool generate_mipmaps) {
        try {
            E::TextureAssetDesc desc{};
            desc.width = width;
            desc.height = height;
            desc.color_space = map(color_space);
            desc.format = map(format);
            desc.pixels = to_byte_vector(pixels);
            desc.label = to_ustring(label);
            desc.kind = map(kind);
            desc.allow_compression = allow_compression;
            desc.generate_mipmaps = generate_mipmaps;
            return asset_outcome(engine.assets().create_texture(std::move(desc)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    AssetOutcome assets_create_orm_texture(EngineView &engine,
                                           rust::Slice<const std::uint8_t> occlusion_rgba8,
                                           rust::Slice<const std::uint8_t> metallic_roughness_rgba8,
                                           std::uint32_t width,
                                           std::uint32_t height,
                                           rust::Str label) {
        try {
            const auto *occlusion_bytes = reinterpret_cast<const std::byte *>(occlusion_rgba8.data());
            const std::span<const std::byte> occlusion_span{occlusion_bytes, occlusion_rgba8.size()};
            const auto *mr_bytes = reinterpret_cast<const std::byte *>(metallic_roughness_rgba8.data());
            const std::span<const std::byte> mr_span{mr_bytes, metallic_roughness_rgba8.size()};
            return asset_outcome(
                engine.assets().create_orm_texture(occlusion_span, mr_span, width, height, to_ustring(label)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    void assets_pump_texture_streaming(EngineView &engine) noexcept {
        try {
            engine.assets().pump_texture_streaming();
        } catch (const std::exception &) {
            // Streaming progress is not something the caller can react to; swallow and try again
            // next tick rather than propagating a C++ exception across the FFI boundary.
        }
    }

    AssetOutcome assets_load_shader(EngineView &engine, rust::Str source, rust::Str label) {
        try {
            return asset_outcome(
                engine.assets().load_shader(std::filesystem::path{to_std_string(source)}, to_ustring(label)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    AssetOutcome assets_load_sound(EngineView &engine, rust::Str source, rust::Str label) {
        try {
            return asset_outcome(
                engine.assets().load_sound(std::filesystem::path{to_std_string(source)}, to_ustring(label)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    AssetOutcome assets_load_file(EngineView &engine, rust::Str source, rust::Str label) {
        try {
            return asset_outcome(
                engine.assets().load_file(std::filesystem::path{to_std_string(source)}, to_ustring(label)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    bool assets_generate_shape(ShapeKind shape, const ShapeParams &params, rust::Vec<ModelVertex> &out_vertices,
                               rust::Vec<std::uint32_t> &out_indices) {
        namespace R = SFT::Renderer;
        for (float value : {params.size, params.extents[0], params.extents[1], params.extents[2], params.radius,
                            params.height, params.width, params.depth, params.major_radius, params.minor_radius}) {
            if (!std::isfinite(value)) {
                return false;
            }
        }
        const R::Axis axis = params.axis == ShapeAxis::X ? R::Axis::X : params.axis == ShapeAxis::Z ? R::Axis::Z : R::Axis::Y;
        try {
            R::Mesh mesh;
            switch (shape) {
            case ShapeKind::Cube: mesh = R::Mesh::cube(R::CubeParams{.size = params.size}); break;
            case ShapeKind::Box:
                mesh = R::Mesh::rectangular_prism(R::RectangularPrismParams{.extents = to_vec3(params.extents)});
                break;
            case ShapeKind::UvSphere:
                mesh = R::Mesh::uv_sphere(R::UvSphereParams{.radius = params.radius, .rings = params.rings, .segments = params.segments});
                break;
            case ShapeKind::IcoSphere:
                mesh = R::Mesh::ico_sphere(R::IcoSphereParams{.radius = params.radius, .subdivisions = params.subdivisions});
                break;
            case ShapeKind::Plane:
                mesh = R::Mesh::plane(R::PlaneParams{.width = params.width,
                                                     .depth = params.depth,
                                                     .width_segments = params.width_segments,
                                                     .depth_segments = params.depth_segments,
                                                     .axis = axis});
                break;
            case ShapeKind::Cylinder:
                mesh = R::Mesh::cylinder(R::CylinderParams{.radius = params.radius,
                                                           .height = params.height,
                                                           .radial_segments = params.radial_segments,
                                                           .axis = axis,
                                                           .capped = params.capped});
                break;
            case ShapeKind::Cone:
                mesh = R::Mesh::cone(R::ConeParams{.radius = params.radius,
                                                   .height = params.height,
                                                   .radial_segments = params.radial_segments,
                                                   .axis = axis,
                                                   .capped = params.capped});
                break;
            case ShapeKind::Torus:
                mesh = R::Mesh::torus(R::TorusParams{.major_radius = params.major_radius,
                                                     .minor_radius = params.minor_radius,
                                                     .major_segments = params.major_segments,
                                                     .minor_segments = params.minor_segments});
                break;
            case ShapeKind::Tetrahedron: mesh = R::Mesh::tetrahedron(R::TetrahedronParams{.size = params.size}); break;
            default: return false;
            }
            if (mesh.vertices().empty() || mesh.indices().empty()) {
                return false;
            }
            out_vertices.reserve(mesh.vertices().size());
            for (const R::GeometryVertex &v : mesh.vertices()) {
                ModelVertex out{};
                out.position = {v.position.x, v.position.y, v.position.z};
                out.normal = {v.normal.x, v.normal.y, v.normal.z};
                out.uv = {v.uv.x, v.uv.y};
                out.color = {v.color.x, v.color.y, v.color.z, v.color.w};
                out.tangent = {v.tangent.x, v.tangent.y, v.tangent.z, v.tangent.w};
                out_vertices.push_back(out);
            }
            out_indices.reserve(mesh.indices().size());
            for (std::uint32_t index : mesh.indices()) {
                out_indices.push_back(index);
            }
            return true;
        } catch (const std::exception &) {
            return false;
        }
    }

    AssetOutcome assets_create_model(EngineView &engine, rust::Str label,
                                     rust::Slice<const ModelPrimitiveInput> primitives) {
        try {
            E::ModelAssetDesc desc{};
            desc.label = to_ustring(label);
            desc.primitives.reserve(primitives.size());
            for (const auto &primitive : primitives) {
                std::vector<SFT::Renderer::GeometryVertex> vertices;
                vertices.reserve(primitive.vertices.size());
                for (const auto &v : primitive.vertices) {
                    vertices.push_back(SFT::Renderer::GeometryVertex{
                        .position = to_vec3(v.position),
                        .normal = to_vec3(v.normal),
                        .uv = to_vec2(v.uv),
                        .color = to_vec4(v.color),
                        .tangent = to_vec4(v.tangent),
                    });
                }
                std::vector<std::uint32_t> indices(primitive.indices.begin(), primitive.indices.end());

                E::ModelPrimitiveDesc primitive_desc{};
                primitive_desc.mesh = SFT::Renderer::Mesh::from_vertices(vertices, indices);
                primitive_desc.shader = to_engine_asset(primitive.shader);
                if (primitive.has_vertex_color) {
                    primitive_desc.vertex_color = to_vec4(primitive.vertex_color);
                }
                primitive_desc.textures.reserve(primitive.textures.size());
                for (const auto &binding : primitive.textures) {
                    primitive_desc.textures.push_back(E::ModelTextureBinding{
                        .slot = to_ustring(binding.slot),
                        .texture = to_engine_asset(binding.texture),
                    });
                }
                primitive_desc.double_sided = primitive.double_sided;
                desc.primitives.push_back(std::move(primitive_desc));
            }
            return asset_outcome(engine.assets().create_model(std::move(desc)));
        } catch (const std::exception &) {
            return make_exception_failure<AssetOutcome>();
        }
    }

    StatusOutcome assets_set_model_float(EngineView &engine, AssetHandle model, std::uint64_t primitive,
                                         rust::Str name, float value) {
        try {
            return status_outcome(engine.assets().set_model_float(
                to_engine_asset(model), static_cast<usize>(primitive), std::string_view{name.data(), name.size()},
                value));
        } catch (const std::exception &) {
            return make_exception_failure<StatusOutcome>();
        }
    }

    StatusOutcome assets_set_model_vec4(EngineView &engine, AssetHandle model, std::uint64_t primitive,
                                        rust::Str name, std::array<float, 4> value) {
        try {
            return status_outcome(engine.assets().set_model_vec4(
                to_engine_asset(model), static_cast<usize>(primitive), std::string_view{name.data(), name.size()},
                to_vec4(value)));
        } catch (const std::exception &) {
            return make_exception_failure<StatusOutcome>();
        }
    }

    StatusOutcome assets_set_model_texture(EngineView &engine, AssetHandle model, std::uint64_t primitive,
                                           rust::Str slot, AssetHandle texture) {
        try {
            return status_outcome(engine.assets().set_model_texture(
                to_engine_asset(model), static_cast<usize>(primitive), std::string_view{slot.data(), slot.size()},
                to_engine_asset(texture)));
        } catch (const std::exception &) {
            return make_exception_failure<StatusOutcome>();
        }
    }

    StatusOutcome assets_unload(EngineView &engine, AssetHandle asset) {
        try {
            const auto result = engine.assets().unload(to_engine_asset(asset));
            StatusOutcome outcome{};
            if (result) {
                outcome.ok = true;
                outcome.error = AssetErrorCode::None;
                return outcome;
            }
            outcome.ok = false;
            outcome.error = map(result.error().code);
            outcome.message = to_rust_string(result.error().message);
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<StatusOutcome>();
        }
    }

    void assets_clear(EngineView &engine) noexcept {
        try {
            engine.assets().clear();
        } catch (const std::exception &) {
            // `clear()` is documented not to throw; guarded defensively for consistency.
        }
    }

    bool assets_contains(const EngineView &engine, AssetHandle asset) noexcept {
        return engine.assets().contains(to_engine_asset(asset));
    }

    std::uint64_t assets_size(const EngineView &engine) noexcept {
        return static_cast<std::uint64_t>(engine.assets().size());
    }

    AssetInfoOutcome assets_info(const EngineView &engine, AssetHandle asset) {
        try {
            const auto result = engine.assets().info(to_engine_asset(asset));
            AssetInfoOutcome outcome{};
            if (!result) {
                outcome.ok = false;
                outcome.error = map(result.error().code);
                outcome.message = to_rust_string(result.error().message);
                return outcome;
            }
            outcome.ok = true;
            outcome.error = AssetErrorCode::None;
            outcome.asset = to_asset_handle(result->asset);
            outcome.label = to_rust_string(result->label);
            outcome.source = to_rust_string(result->source);
            outcome.memory_bytes = static_cast<std::uint64_t>(result->memory_bytes);
            outcome.loaded = result->loaded;
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<AssetInfoOutcome>();
        }
    }

    TextureInfoOutcome assets_texture_info(const EngineView &engine, AssetHandle asset) {
        try {
            const auto result = engine.assets().texture_info(to_engine_asset(asset));
            TextureInfoOutcome outcome{};
            if (!result) {
                outcome.ok = false;
                outcome.error = map(result.error().code);
                outcome.message = to_rust_string(result.error().message);
                return outcome;
            }
            outcome.ok = true;
            outcome.error = AssetErrorCode::None;
            outcome.width = result->width;
            outcome.height = result->height;
            outcome.color_space = map(result->color_space);
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<TextureInfoOutcome>();
        }
    }

    ModelInfoOutcome assets_model_info(const EngineView &engine, AssetHandle asset) {
        try {
            const auto result = engine.assets().model_info(to_engine_asset(asset));
            ModelInfoOutcome outcome{};
            if (!result) {
                outcome.ok = false;
                outcome.error = map(result.error().code);
                outcome.message = to_rust_string(result.error().message);
                return outcome;
            }
            outcome.ok = true;
            outcome.error = AssetErrorCode::None;
            outcome.primitive_count = static_cast<std::uint64_t>(result->primitive_count);
            outcome.vertex_count = static_cast<std::uint64_t>(result->vertex_count);
            outcome.index_count = static_cast<std::uint64_t>(result->index_count);
            outcome.triangle_count = static_cast<std::uint64_t>(result->triangle_count);
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<ModelInfoOutcome>();
        }
    }

    SoundInfoOutcome assets_sound_info(const EngineView &engine, AssetHandle asset) {
        try {
            const auto result = engine.assets().sound_info(to_engine_asset(asset));
            SoundInfoOutcome outcome{};
            if (!result) {
                outcome.ok = false;
                outcome.error = map(result.error().code);
                outcome.message = to_rust_string(result.error().message);
                return outcome;
            }
            outcome.ok = true;
            outcome.error = AssetErrorCode::None;
            outcome.channels = result->channels;
            outcome.sample_rate = result->sample_rate;
            outcome.frame_count = static_cast<std::uint64_t>(result->frame_count);
            outcome.duration_seconds = result->duration_seconds;
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<SoundInfoOutcome>();
        }
    }

    RendererTextureHandleOutcome assets_texture_handle(const EngineView &engine, AssetHandle asset) {
        try {
            const auto result = engine.assets().texture_handle(to_engine_asset(asset));
            RendererTextureHandleOutcome outcome{};
            if (!result) {
                outcome.ok = false;
                outcome.error = map(result.error().code);
                outcome.message = to_rust_string(result.error().message);
                return outcome;
            }
            outcome.ok = true;
            outcome.error = AssetErrorCode::None;
            outcome.value = result->value;
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<RendererTextureHandleOutcome>();
        }
    }

    BytesOutcome assets_file_bytes(const EngineView &engine, AssetHandle asset) {
        try {
            const auto result = engine.assets().file_bytes(to_engine_asset(asset));
            BytesOutcome outcome{};
            if (!result) {
                outcome.ok = false;
                outcome.error = map(result.error().code);
                outcome.message = to_rust_string(result.error().message);
                return outcome;
            }
            outcome.ok = true;
            outcome.error = AssetErrorCode::None;
            const auto &bytes = **result;
            outcome.data.reserve(bytes.size());
            for (const auto b : bytes) {
                outcome.data.push_back(static_cast<std::uint8_t>(b));
            }
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<BytesOutcome>();
        }
    }

    SamplesOutcome assets_sound_samples(const EngineView &engine, AssetHandle asset) {
        try {
            const auto result = engine.assets().sound_samples(to_engine_asset(asset));
            SamplesOutcome outcome{};
            if (!result) {
                outcome.ok = false;
                outcome.error = map(result.error().code);
                outcome.message = to_rust_string(result.error().message);
                return outcome;
            }
            outcome.ok = true;
            outcome.error = AssetErrorCode::None;
            const auto &samples = **result;
            outcome.data.reserve(samples.size());
            for (const auto s : samples) {
                outcome.data.push_back(s);
            }
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<SamplesOutcome>();
        }
    }

    GltfImportOutcome gltf_import(EngineView &engine, rust::Str source, AssetHandle shader) {
        try {
            auto result = E::import_gltf(engine.assets(), std::filesystem::path{to_std_string(source)},
                                         to_engine_asset(shader));
            GltfImportOutcome outcome{};
            if (!result) {
                outcome.ok = false;
                outcome.error = map(result.error().code);
                outcome.message = to_rust_string(result.error().message);
                return outcome;
            }
            outcome.ok = true;
            outcome.error = AssetErrorCode::None;
            outcome.models.reserve(result->models.size());
            for (const auto &model : result->models) {
                outcome.models.push_back(to_asset_handle(model));
            }
            outcome.instances.reserve(result->instances.size());
            for (const auto &instance : result->instances) {
                GltfInstance out{};
                out.name = to_rust_string(instance.name);
                out.model = to_asset_handle(instance.model);
                copy_transform(instance.world_transform, out.world_transform);
                outcome.instances.push_back(std::move(out));
            }
            outcome.lights.reserve(result->lights.size());
            for (const auto &light : result->lights) {
                GltfLight out{};
                out.name = to_rust_string(light.name);
                out.kind = map(light.kind);
                out.radiance[0] = light.radiance.x;
                out.radiance[1] = light.radiance.y;
                out.radiance[2] = light.radiance.z;
                out.range = light.range;
                constexpr float radians_to_degrees = 180.0f / 3.14159265358979323846f;
                const auto clamp = [](float v) { return v < -1.0f ? -1.0f : (v > 1.0f ? 1.0f : v); };
                out.inner_cone_degrees = std::acos(clamp(light.inner_cone_cos)) * radians_to_degrees;
                out.outer_cone_degrees = std::acos(clamp(light.outer_cone_cos)) * radians_to_degrees;
                copy_transform(light.world_transform, out.world_transform);
                outcome.lights.push_back(std::move(out));
            }
            return outcome;
        } catch (const std::exception &) {
            return make_exception_failure<GltfImportOutcome>();
        }
    }

} // namespace sturdy_rs::assets
