#include "sturdy_rs/diagnostics.hpp"

#include <cstdint>
#include <memory>
#include <string_view>
#include <utility>

#include <Async/Scheduler.hpp>
#include <Core/Renderer.hpp>
#include <Engine/Engine.hpp>
#include <Foundation/LogSink.hpp>
#include <RHI/RHI.hpp>
#include <RHI/Selection.hpp>

#if !defined(STURDY_PLATFORM_WEB)
#include <Core/Vulkan/Rhi/VulkanNativeAccessExtension.hpp>
#endif
#if defined(_WIN32)
#include <Core/D3D12/RHI/D3D12NativeAccessExtension.hpp>
#endif
#if defined(STURDY_ENABLE_WEBGPU)
// Only compiled into Core at all when STURDY_ENABLE_WEBGPU is set — see this file's own
// `native_webgpu_*` functions below and `FFI/src/FFI/Native.cpp`'s identical guard/comment on its
// reference-API counterpart.
#include <Core/WebGPU/RHI/WebGpuNativeAccessExtension.hpp>
#endif

// Generated by build.rs from src/diagnostics.rs; defines the shared structs/enums and the Rust
// callbacks (mirrors how shim.cpp includes "sturdy_rs/bridge.h").
#include "sturdy_rs/diagnostics_bridge.h"

namespace sturdy_rs::diagnostics {
    namespace {

        namespace E = SFT::Engine;
        namespace R = SFT::RHI;

        /// Reinterprets a native pointer-sized handle as an integer, the same escape hatch the
        /// vendored `FFI/src/FFI/Native.cpp` uses (there via the `SturdyVulkanHandles`/
        /// `SturdyD3D12Handles` ABI structs, here directly as `u64`).
        std::uint64_t to_u64(const void *handle) noexcept {
            return static_cast<std::uint64_t>(reinterpret_cast<std::uintptr_t>(handle));
        }

#if !defined(STURDY_PLATFORM_WEB)
        SFT::Core::Vulkan::VulkanNativeAccessExtension *vulkan_native_access(R::RhiDevice &device) noexcept {
            if (device.backend_type() != R::BackendType::Vulkan) {
                return nullptr;
            }
            return static_cast<SFT::Core::Vulkan::VulkanNativeAccessExtension *>(
                device.extension_interface(SFT::Core::Vulkan::VulkanNativeAccessExtension::id()));
        }
#endif

#if defined(_WIN32)
        SFT::D3D12::D3D12NativeAccessExtension *d3d12_native_access(R::RhiDevice &device) noexcept {
            if (device.backend_type() != R::BackendType::D3D12) {
                return nullptr;
            }
            return static_cast<SFT::D3D12::D3D12NativeAccessExtension *>(
                device.extension_interface(SFT::D3D12::D3D12NativeAccessExtension::id()));
        }
#endif

#if defined(STURDY_ENABLE_WEBGPU)
        SFT::Core::WebGpu::WebGpuNativeAccessExtension *webgpu_native_access(R::RhiDevice &device) noexcept {
            if (device.backend_type() != R::BackendType::WebGpu) {
                return nullptr;
            }
            return static_cast<SFT::Core::WebGpu::WebGpuNativeAccessExtension *>(
                device.extension_interface(SFT::Core::WebGpu::WebGpuNativeAccessExtension::id()));
        }
#endif

        rust::String rs(const std::string &s) { return rust::String::lossy(s); }

    } // namespace

    // -- Native GPU handle interop -------------------------------------------------------------

    bool native_vulkan_available(EngineView &engine) noexcept {
#if defined(STURDY_PLATFORM_WEB)
        (void)engine;
        return false;
#else
        R::RhiDevice *device = engine.rhi_device();
        return device != nullptr && vulkan_native_access(*device) != nullptr;
#endif
    }

    bool native_vulkan_handles(EngineView &engine, NativeVulkanHandles &out) noexcept {
#if defined(STURDY_PLATFORM_WEB)
        (void)engine;
        (void)out;
        return false;
#else
        R::RhiDevice *device = engine.rhi_device();
        if (device == nullptr) {
            return false;
        }
        auto *access = vulkan_native_access(*device);
        if (access == nullptr) {
            return false;
        }
        out = NativeVulkanHandles{};
        out.instance = to_u64(access->native_instance());
        out.physical_device = to_u64(access->native_physical_device());
        out.device = to_u64(access->native_device());
        out.graphics_queue = to_u64(access->native_graphics_queue());
        out.graphics_queue_family = access->native_queue_family(R::QueueLane{R::QueueClass::Graphics, 0});
        return true;
#endif
    }

    bool native_d3d12_available(EngineView &engine) noexcept {
#if !defined(_WIN32)
        (void)engine;
        return false;
#else
        R::RhiDevice *device = engine.rhi_device();
        return device != nullptr && d3d12_native_access(*device) != nullptr;
#endif
    }

    bool native_d3d12_handles(EngineView &engine, NativeD3D12Handles &out) noexcept {
#if !defined(_WIN32)
        (void)engine;
        (void)out;
        return false;
#else
        R::RhiDevice *device = engine.rhi_device();
        if (device == nullptr) {
            return false;
        }
        auto *access = d3d12_native_access(*device);
        if (access == nullptr) {
            return false;
        }
        out = NativeD3D12Handles{};
        out.factory = to_u64(access->native_factory());
        out.adapter = to_u64(access->native_adapter());
        out.device = to_u64(access->native_device());
        out.graphics_queue = to_u64(access->native_graphics_queue());
        return true;
#endif
    }

    bool native_webgpu_available(EngineView &engine) noexcept {
#if !defined(STURDY_ENABLE_WEBGPU)
        (void)engine;
        return false;
#else
        R::RhiDevice *device = engine.rhi_device();
        return device != nullptr && webgpu_native_access(*device) != nullptr;
#endif
    }

    bool native_webgpu_handles(EngineView &engine, NativeWebGpuHandles &out) noexcept {
#if !defined(STURDY_ENABLE_WEBGPU)
        (void)engine;
        (void)out;
        return false;
#else
        R::RhiDevice *device = engine.rhi_device();
        if (device == nullptr) {
            return false;
        }
        auto *access = webgpu_native_access(*device);
        if (access == nullptr) {
            return false;
        }
        out = NativeWebGpuHandles{};
        out.instance = to_u64(access->native_instance());
        out.adapter = to_u64(access->native_adapter());
        out.device = to_u64(access->native_device());
        out.queue = to_u64(access->native_queue());
        return true;
#endif
    }

    // -- Extended GPU inventory & capabilities --------------------------------------------------

    bool gpu_capabilities(const EngineView &engine, GpuCapabilities &out) noexcept {
        const SFT::Core::RendererCapabilities &caps = engine.capabilities();
        // `b8` (Foundation's byte-sized bool) does not implicitly convert to `bool`.
        out.multithreaded_command_recording = static_cast<bool>(caps.multithreaded_command_recording);
        out.async_compute = static_cast<bool>(caps.async_compute);
        out.raytracing = static_cast<bool>(caps.raytracing);
        out.mesh_shaders = static_cast<bool>(caps.mesh_shaders);
        out.bindless = static_cast<bool>(caps.bindless);
        out.timeline_semaphores = static_cast<bool>(caps.timeline_semaphores);
        out.max_frames_in_flight = caps.max_frames_in_flight;
        return true;
    }

    std::uint32_t gpu_inventory_count(const EngineView &engine) noexcept {
        return static_cast<std::uint32_t>(engine.gpu_inventory().gpus.size());
    }

    bool gpu_inventory_get(const EngineView &engine, std::uint32_t index, PhysicalGpuInfo &out) {
        const auto &gpus = engine.gpu_inventory().gpus;
        if (index >= gpus.size()) {
            return false;
        }
        const R::PhysicalGpu &gpu = gpus[index];
        out = PhysicalGpuInfo{};
        out.name = rs(gpu.name);
        out.vendor = rs(gpu.vendor);
        out.device_type = rust::String(R::device_type_name(gpu.device_type));
        out.vendor_id = gpu.vendor_id;
        out.device_id = gpu.device_id;
        out.physical_device_id = rs(gpu.physical_device_id);
        out.preference_score = R::score_adapter(gpu.device_type, R::PowerPreference::HighPerformance);
        return true;
    }

    // -- Window diagnostics ---------------------------------------------------------------------

    namespace {
        void copy_window(const E::WindowSnapshot &snapshot, WindowInfo &out) noexcept {
            out = WindowInfo{};
            out.window_id = static_cast<std::uint64_t>(snapshot.id);
            out.width = snapshot.size.x;
            out.height = snapshot.size.y;
            out.framebuffer_width = snapshot.framebuffer_size.x;
            out.framebuffer_height = snapshot.framebuffer_size.y;
            out.position_x = snapshot.position.x;
            out.position_y = snapshot.position.y;
            out.opacity = snapshot.opacity;
            out.mouse_locked = snapshot.mouse_locked;
            out.focused = snapshot.focused;
        }
    } // namespace

    std::uint32_t window_count(const EngineView &engine) noexcept {
        return static_cast<std::uint32_t>(engine.window_state().windows().size());
    }

    bool window_snapshot(const EngineView &engine, std::uint32_t index, WindowInfo &out) noexcept {
        const auto windows = engine.window_state().windows();
        if (index >= windows.size()) {
            return false;
        }
        copy_window(windows[index], out);
        return true;
    }

    bool window_primary(const EngineView &engine, WindowInfo &out) noexcept {
        const E::WindowSnapshot *primary = engine.window_state().primary();
        if (primary == nullptr) {
            return false;
        }
        copy_window(*primary, out);
        return true;
    }

    bool window_find(const EngineView &engine, std::uint64_t window_id, WindowInfo &out) noexcept {
        const auto id = static_cast<SFT::WindowManager::WindowId>(window_id);
        const E::WindowSnapshot *found = engine.window_state().find(id);
        if (found == nullptr) {
            return false;
        }
        copy_window(*found, out);
        return true;
    }

    // -- Process-wide log sink ------------------------------------------------------------------

    std::uint64_t log_add_sink(rust::Box<LogSink> sink) {
        // `Foundation::LogSinkCallback` is a `std::function`, which must be copyable; `rust::Box`
        // is move-only, so it is kept behind a `shared_ptr` the lambda captures by copy.
        auto boxed = std::make_shared<rust::Box<LogSink>>(std::move(sink));
        const SFT::Foundation::LogSinkId id = SFT::Foundation::add_log_sink(
            [boxed](SFT::Foundation::LogLevel level, std::string_view message) {
                // The two `LogLevel` enums are ordinal-matched by construction (see
                // Foundation/LogSink.hpp's own doc comment), same as the FFI's `SturdyLogLevel`.
                const auto rust_level = static_cast<LogLevel>(level);
                const rust::Slice<const std::uint8_t> bytes{
                    reinterpret_cast<const std::uint8_t *>(message.data()), message.size()};
                log_sink_call(**boxed, rust_level, bytes);
            });
        return id.value;
    }

    void log_remove_sink(std::uint64_t id) noexcept {
        SFT::Foundation::remove_log_sink(SFT::Foundation::LogSinkId{id});
    }

    // -- Process-wide task scheduler --------------------------------------------------------------

    std::uint32_t scheduler_worker_count() noexcept { return SFT::Async::Scheduler::worker_count(); }
    bool scheduler_is_running() noexcept { return SFT::Async::Scheduler::is_running(); }

    std::unique_ptr<TaskHandle> scheduler_spawn(rust::Box<SchedulerTask> task, bool heavy) {
        auto handle = SFT::Async::Scheduler::spawn(
            [task = std::move(task)]() mutable { scheduler_task_run(*task); },
            heavy ? SFT::Async::TaskWeight::Heavy : SFT::Async::TaskWeight::Light);
        return std::make_unique<TaskHandle>(std::move(handle));
    }

    bool task_handle_is_done(const TaskHandle &handle) noexcept { return handle.is_done(); }
    void task_handle_wait(const TaskHandle &handle) noexcept { handle.wait(); }

} // namespace sturdy_rs::diagnostics
