#include "sturdy_rs/ecs.hpp"

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <map>
#include <memory>
#include <mutex>
#include <string_view>
#include <vector>

#include <Ecs/ErasedEvents.hpp>
#include <Ecs/World.hpp>
#include <Engine/Engine.hpp>
#include <Foundation/Foundation.hpp>

// Generated by build.rs from src/ecs.rs; defines the shared structs/enums this file returns.
#include "sturdy_rs/ecs_bridge.h"

namespace sturdy_rs::ecs {
    namespace {

        namespace WE = SFT::Ecs;

        // The Rust EcsErrorCode mirrors WorldErasedErrorCode variant-for-variant; catch drift here
        // rather than at a confusing call site.
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::DeadEntity) ==
                     static_cast<std::uint32_t>(EcsErrorCode::DeadEntity));
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::UnknownComponent) ==
                     static_cast<std::uint32_t>(EcsErrorCode::UnknownComponent));
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::DuplicateComponent) ==
                     static_cast<std::uint32_t>(EcsErrorCode::DuplicateComponent));
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::MissingComponent) ==
                     static_cast<std::uint32_t>(EcsErrorCode::MissingComponent));
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::SizeMismatch) ==
                     static_cast<std::uint32_t>(EcsErrorCode::SizeMismatch));
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::NotTriviallyCopyable) ==
                     static_cast<std::uint32_t>(EcsErrorCode::NotTriviallyCopyable));
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::NoComponents) ==
                     static_cast<std::uint32_t>(EcsErrorCode::NoComponents));
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::ScheduleRunning) ==
                     static_cast<std::uint32_t>(EcsErrorCode::ScheduleRunning));
        static_assert(static_cast<std::uint32_t>(WE::WorldErasedErrorCode::InvalidArgument) ==
                     static_cast<std::uint32_t>(EcsErrorCode::InvalidArgument));

        EcsErrorCode map_error_code(WE::WorldErasedErrorCode code) noexcept {
            switch (code) {
            case WE::WorldErasedErrorCode::DeadEntity: return EcsErrorCode::DeadEntity;
            case WE::WorldErasedErrorCode::UnknownComponent: return EcsErrorCode::UnknownComponent;
            case WE::WorldErasedErrorCode::DuplicateComponent: return EcsErrorCode::DuplicateComponent;
            case WE::WorldErasedErrorCode::MissingComponent: return EcsErrorCode::MissingComponent;
            case WE::WorldErasedErrorCode::SizeMismatch: return EcsErrorCode::SizeMismatch;
            case WE::WorldErasedErrorCode::NotTriviallyCopyable: return EcsErrorCode::NotTriviallyCopyable;
            case WE::WorldErasedErrorCode::NoComponents: return EcsErrorCode::NoComponents;
            case WE::WorldErasedErrorCode::ScheduleRunning: return EcsErrorCode::ScheduleRunning;
            case WE::WorldErasedErrorCode::InvalidArgument: return EcsErrorCode::InvalidArgument;
            }
            return EcsErrorCode::InvalidArgument;
        }

        EcsStatus ok_status() noexcept {
            // `code` is meaningless while `ok` is true; InvalidArgument is just a harmless default.
            return EcsStatus{true, EcsErrorCode::InvalidArgument, rust::String()};
        }

        rust::String to_rust_string(std::string_view text);

        EcsStatus fail_status(EcsErrorCode code, std::string_view message) {
            return EcsStatus{false, code, to_rust_string(message)};
        }

        EcsStatus to_status(const WE::WorldErasedExpected<void> &result) {
            if (result) {
                return ok_status();
            }
            return fail_status(map_error_code(result.error().code), result.error().message.cpp_string_view());
        }

        WE::Entity to_engine_entity(EntityId entity) noexcept {
            return WE::Entity{.index = entity.index, .generation = entity.generation};
        }

        EntityId to_bridge_entity(WE::Entity entity) noexcept {
            return EntityId{entity.index, entity.generation};
        }

        WE::ResourceKey to_engine_key(ResourceId id) noexcept {
            return WE::ResourceKey{.high = id.high, .low = id.low};
        }

        std::string_view view_of(rust::Str text) noexcept {
            return {text.data(), text.size()};
        }

        // `rust::String` has no `std::string_view` constructor, only `(const char *, size_t)`.
        rust::String to_rust_string(std::string_view text) {
            return rust::String(text.data(), text.size());
        }

        // ─── Resource storage ───────────────────────────────────────────────────────────────────
        //
        // `World::bind_resource_erased` only ever borrows a pointer; whoever calls it keeps the
        // storage alive. A Rust-owned buffer crossing this call would need to outlive a boundary
        // neither side can observe, so — like the engine's own FFI layer — this shim allocates and
        // owns resource storage itself, keyed by world and resource key, and frees it on destroy.

        struct OwnedResource {
            std::unique_ptr<std::byte[]> bytes;
            std::size_t size = 0;
        };

        struct OwnedKey {
            const WE::World *world;
            std::uint64_t high;
            std::uint64_t low;

            friend auto operator<=>(const OwnedKey &, const OwnedKey &) = default;
        };

        std::mutex g_owned_mutex;
        std::map<OwnedKey, OwnedResource> g_owned;

        // ─── Event channel storage ──────────────────────────────────────────────────────────────
        //
        // Same ownership shape as `OwnedResource` above, but backed by a heap-allocated
        // `SFT::Ecs::ErasedEvents` instead of a flat buffer, since events need `send`/`at`/`clear`
        // rather than plain byte storage. Bound into the world via `bind_resource_erased` with
        // `object` pointing at the `ErasedEvents` itself — so the size/align told to the world are
        // `sizeof`/`alignof` of the container, not its per-element size — and `clear` pointed at
        // `SFT::Ecs::clear_erased_events`, exactly as a normal (non-erased) `Events<T>` would be, so
        // an engine-driven `Ecs::Schedule` that does run against this world (this binding layer
        // never runs one itself; see `ecs_read_events`) still clears it on the usual cadence.

        struct OwnedEventChannel {
            std::unique_ptr<WE::ErasedEvents> events;
        };

        std::mutex g_events_mutex;
        std::map<OwnedKey, OwnedEventChannel> g_events;

    } // namespace

    ResourceId ecs_resource_key(rust::Str name) noexcept {
        const WE::ResourceKey key = WE::ResourceKey::from_name(view_of(name));
        return ResourceId{key.high, key.low};
    }

    ComponentLookup ecs_register_component(EngineView &engine, rust::Str name, std::uint32_t size, std::uint32_t align) {
        ComponentLookup result{};
        const std::string_view canonical_name = view_of(name);
        if (canonical_name.empty()) {
            result.message = rust::String("component name must not be empty");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }
        if (size == 0) {
            result.message = rust::String("component size must be nonzero; tag components are not supported yet");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }
        if (align == 0 || (align & (align - 1)) != 0 || align > 64) {
            result.message = rust::String("component alignment must be a power of two no greater than 64");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }

        WE::ComponentRegistry &registry = engine.ecs_world().registry();

        // Registering the same component twice is expected (a binding may call this on every run);
        // idempotent as long as the layout still matches.
        if (const auto existing = registry.find(SFT::ustr{canonical_name})) {
            const WE::ComponentInfo *descriptor = registry.info(*existing);
            if (descriptor != nullptr && (descriptor->size != size || descriptor->align != align)) {
                result.message = rust::String("a component with this name is already registered with a different layout");
                result.code = EcsErrorCode::InvalidArgument;
                return result;
            }
            result.ok = true;
            result.id = *existing;
            return result;
        }

        WE::ComponentInfo info{};
        info.key = WE::ComponentKey::from_name(canonical_name);
        info.canonical_name = SFT::UString{std::string{canonical_name}};
        info.schema_version = 1;
        info.size = size;
        info.align = align;
        // FfiBlittable records where this component came from; the trivially-* flags are what the
        // erased World API actually checks before copying bytes.
        info.flags = WE::ComponentFlags::TriviallyCopyable | WE::ComponentFlags::TriviallyDestructible |
                    WE::ComponentFlags::FfiBlittable;
        info.default_construct = [](void *destination, void *user_data) noexcept {
            // Size travels through user_data since these are plain function pointers with no
            // capture; zeroing gives a foreign component a defined initial value.
            std::memset(destination, 0, reinterpret_cast<std::size_t>(user_data));
        };
        info.copy_construct = [](void *destination, const void *source, void *user_data) noexcept {
            std::memcpy(destination, source, reinterpret_cast<std::size_t>(user_data));
        };
        info.move_construct = [](void *destination, void *source, void *user_data) noexcept {
            std::memcpy(destination, source, reinterpret_cast<std::size_t>(user_data));
        };
        info.destroy = [](void *, void *) noexcept {};
        info.user_data = reinterpret_cast<void *>(static_cast<std::size_t>(size));

        auto registered = registry.register_component(std::move(info));
        if (!registered) {
            result.message = to_rust_string(registered.error().message.cpp_string_view());
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }
        result.ok = true;
        result.id = *registered;
        return result;
    }

    ComponentLookup ecs_find_component(const EngineView &engine, rust::Str name) {
        ComponentLookup result{};
        const auto found = engine.ecs_world().registry().find(SFT::ustr{view_of(name)});
        if (!found) {
            result.message = rust::String("no component is registered under that name");
            result.code = EcsErrorCode::UnknownComponent;
            return result;
        }
        result.ok = true;
        result.id = *found;
        return result;
    }

    SpawnResult ecs_spawn(EngineView &engine,
                         rust::Slice<const std::uint32_t> component_ids,
                         rust::Slice<const std::uint32_t> sizes,
                         rust::Slice<const std::uint8_t> data) {
        SpawnResult result{};
        if (component_ids.size() != sizes.size()) {
            result.message = rust::String("component_ids and sizes must have the same length");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }
        if (component_ids.size() == 0) {
            result.message = rust::String("spawning an entity requires at least one component");
            result.code = EcsErrorCode::NoComponents;
            return result;
        }

        WE::World &world = engine.ecs_world();
        std::vector<WE::ComponentId> ids(component_ids.begin(), component_ids.end());
        std::vector<const void *> pointers;
        pointers.reserve(ids.size());
        std::size_t offset = 0;
        for (std::size_t i = 0; i < ids.size(); ++i) {
            const WE::ComponentInfo *descriptor = world.registry().info(ids[i]);
            if (descriptor == nullptr) {
                result.message = rust::String("no component is registered under one of the supplied ids");
                result.code = EcsErrorCode::UnknownComponent;
                return result;
            }
            if (descriptor->size != sizes[i]) {
                result.message = rust::String("a supplied component size does not match its registered size");
                result.code = EcsErrorCode::SizeMismatch;
                return result;
            }
            if (offset + sizes[i] > data.size()) {
                result.message = rust::String("component data is shorter than the declared sizes");
                result.code = EcsErrorCode::SizeMismatch;
                return result;
            }
            pointers.push_back(data.data() + offset);
            offset += sizes[i];
        }
        if (offset != data.size()) {
            result.message = rust::String("component data is longer than the declared sizes");
            result.code = EcsErrorCode::SizeMismatch;
            return result;
        }

        auto spawned = world.spawn_erased(ids, pointers);
        if (!spawned) {
            result.message = to_rust_string(spawned.error().message.cpp_string_view());
            result.code = map_error_code(spawned.error().code);
            return result;
        }
        result.ok = true;
        result.entity = to_bridge_entity(*spawned);
        return result;
    }

    void ecs_despawn(EngineView &engine, EntityId entity) noexcept {
        engine.ecs_world().destroy(to_engine_entity(entity));
    }

    bool ecs_is_alive(const EngineView &engine, EntityId entity) noexcept {
        return engine.ecs_world().is_alive(to_engine_entity(entity));
    }

    bool ecs_has_component(const EngineView &engine, EntityId entity, std::uint32_t component) noexcept {
        return engine.ecs_world().has_component_erased(to_engine_entity(entity), component);
    }

    EcsStatus ecs_add_component(EngineView &engine, EntityId entity, std::uint32_t component,
                                rust::Slice<const std::uint8_t> data) {
        WE::World &world = engine.ecs_world();
        const WE::ComponentInfo *descriptor = world.registry().info(component);
        if (descriptor == nullptr) {
            return fail_status(EcsErrorCode::UnknownComponent, "no component is registered under that id");
        }
        if (descriptor->size != data.size()) {
            return fail_status(EcsErrorCode::SizeMismatch, "supplied data does not match the component's registered size");
        }
        auto added = world.add_component_erased(to_engine_entity(entity), component, data.data());
        return to_status(added);
    }

    EcsStatus ecs_remove_component(EngineView &engine, EntityId entity, std::uint32_t component) {
        auto removed = engine.ecs_world().remove_component_erased(to_engine_entity(entity), component);
        return to_status(removed);
    }

    EcsStatus ecs_read_component(const EngineView &engine, EntityId entity, std::uint32_t component,
                                 rust::Slice<std::uint8_t> out) {
        auto read = engine.ecs_world().read_component_erased(to_engine_entity(entity), component, out.data(), out.size());
        return to_status(read);
    }

    EcsStatus ecs_write_component(EngineView &engine, EntityId entity, std::uint32_t component,
                                  rust::Slice<const std::uint8_t> data) {
        auto written = engine.ecs_world().write_component_erased(to_engine_entity(entity), component, data.data(), data.size());
        return to_status(written);
    }

    ResourceLookup ecs_create_resource(EngineView &engine, rust::Str name, rust::Slice<const std::uint8_t> data) {
        ResourceLookup result{};
        const std::string_view canonical_name = view_of(name);
        if (canonical_name.empty()) {
            result.message = rust::String("resource name must not be empty");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }
        if (data.size() == 0) {
            result.message = rust::String("resource size must be nonzero");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }

        WE::World &world = engine.ecs_world();
        const WE::ResourceKey key = WE::ResourceKey::from_name(canonical_name);
        result.id = ResourceId{key.high, key.low};

        const OwnedKey owned_key{&world, key.high, key.low};
        void *object = nullptr;
        {
            const std::lock_guard<std::mutex> lock{g_owned_mutex};
            if (const auto existing = g_owned.find(owned_key); existing != g_owned.end()) {
                if (existing->second.size != data.size()) {
                    result.message = rust::String("a different resource is already registered under that name");
                    result.code = EcsErrorCode::InvalidArgument;
                    return result;
                }
                result.ok = true;
                return result;
            }

            OwnedResource owned;
            owned.bytes = std::make_unique<std::byte[]>(data.size());
            owned.size = data.size();
            std::memcpy(owned.bytes.get(), data.data(), data.size());
            object = owned.bytes.get();
            g_owned.emplace(owned_key, std::move(owned));
        }

        // Alignment is the strictest the allocator guarantees: `new std::byte[]` suits any scalar,
        // which covers every layout a plain C struct can have short of over-aligned SIMD types.
        auto bound = world.bind_resource_erased(key, canonical_name, object, data.size(), alignof(std::max_align_t), nullptr);
        if (!bound) {
            const std::lock_guard<std::mutex> lock{g_owned_mutex};
            g_owned.erase(owned_key);
            result.message = to_rust_string(bound.error().message.cpp_string_view());
            result.code = map_error_code(bound.error().code);
            return result;
        }
        result.ok = true;
        return result;
    }

    EcsStatus ecs_destroy_resource(EngineView &engine, ResourceId key) {
        WE::World &world = engine.ecs_world();
        const OwnedKey owned_key{&world, key.high, key.low};
        {
            const std::lock_guard<std::mutex> lock{g_owned_mutex};
            if (g_owned.find(owned_key) == g_owned.end()) {
                // Either nothing is bound, or it is a C++ resource whose storage belongs to the
                // engine; freeing that would be a use-after-free for its real owner.
                return fail_status(EcsErrorCode::UnknownComponent, "no resource owned by this binding is bound under that id");
            }
        }

        auto unbound = world.unbind_resource_erased(to_engine_key(key));
        if (!unbound) {
            return fail_status(map_error_code(unbound.error().code), unbound.error().message.cpp_string_view());
        }

        // Freed only after the world has let go of the pointer, so nothing can read it in between.
        const std::lock_guard<std::mutex> lock{g_owned_mutex};
        g_owned.erase(owned_key);
        return ok_status();
    }

    bool ecs_has_resource(const EngineView &engine, ResourceId key) noexcept {
        return engine.ecs_world().has_resource_erased(to_engine_key(key));
    }

    EcsStatus ecs_get_resource(EngineView &engine, ResourceId key, rust::Slice<std::uint8_t> out) {
        SFT::usize bound_size = 0;
        void *object = engine.ecs_world().resource_pointer_erased(to_engine_key(key), &bound_size);
        if (object == nullptr) {
            return fail_status(EcsErrorCode::UnknownComponent, "no resource is bound under that id");
        }
        if (bound_size != out.size()) {
            return fail_status(EcsErrorCode::SizeMismatch, "supplied buffer does not match the resource's size");
        }
        std::memcpy(out.data(), object, out.size());
        return ok_status();
    }

    EcsStatus ecs_set_resource(EngineView &engine, ResourceId key, rust::Slice<const std::uint8_t> data) {
        SFT::usize bound_size = 0;
        void *object = engine.ecs_world().resource_pointer_erased(to_engine_key(key), &bound_size);
        if (object == nullptr) {
            return fail_status(EcsErrorCode::UnknownComponent, "no resource is bound under that id");
        }
        if (bound_size != data.size()) {
            return fail_status(EcsErrorCode::SizeMismatch, "supplied data does not match the resource's size");
        }
        std::memcpy(object, data.data(), data.size());
        return ok_status();
    }

    QuerySnapshot ecs_query(EngineView &engine, rust::Slice<const std::uint32_t> component_ids) {
        QuerySnapshot result{};
        if (component_ids.size() == 0) {
            result.message = rust::String("a query requires at least one component");
            result.code = EcsErrorCode::NoComponents;
            return result;
        }
        if (component_ids.size() > WE::max_erased_visit_components) {
            result.message = rust::String("too many components requested in one query");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }

        WE::World &world = engine.ecs_world();
        std::vector<WE::ComponentId> ids(component_ids.begin(), component_ids.end());

        for (auto id : ids) {
            const WE::ComponentInfo *descriptor = world.registry().info(id);
            if (descriptor == nullptr) {
                result.message = rust::String("no component is registered under one of the requested ids");
                result.code = EcsErrorCode::UnknownComponent;
                return result;
            }
            result.sizes.push_back(static_cast<std::uint32_t>(descriptor->size));
        }

        // The visitor is a capture-less lambda (required: `for_each_erased` takes a bare function
        // pointer), so the snapshot it appends into is threaded through as `user_data`.
        auto visited = world.for_each_erased(
            ids,
            [](WE::Entity entity, void **pointers, void *user_data) noexcept {
                auto *snapshot = static_cast<QuerySnapshot *>(user_data);
                snapshot->entities.push_back(to_bridge_entity(entity));
                for (std::size_t i = 0; i < snapshot->sizes.size(); ++i) {
                    const auto *bytes = static_cast<const std::uint8_t *>(pointers[i]);
                    const std::uint32_t size = snapshot->sizes[i];
                    for (std::uint32_t byte = 0; byte < size; ++byte) {
                        snapshot->data.push_back(bytes[byte]);
                    }
                }
            },
            &result);

        if (!visited) {
            result.message = to_rust_string(visited.error().message.cpp_string_view());
            result.code = map_error_code(visited.error().code);
            // Wipe anything the visitor collected before the error was noticed.
            result.entities.clear();
            result.data.clear();
            return result;
        }
        result.ok = true;
        return result;
    }

    ResourceLookup ecs_create_event_channel(EngineView &engine, rust::Str name, std::uint32_t element_size) {
        ResourceLookup result{};
        const std::string_view canonical_name = view_of(name);
        if (canonical_name.empty()) {
            result.message = rust::String("event channel name must not be empty");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }
        if (element_size == 0) {
            result.message = rust::String("event element size must be nonzero");
            result.code = EcsErrorCode::InvalidArgument;
            return result;
        }

        WE::World &world = engine.ecs_world();
        const WE::ResourceKey key = WE::ResourceKey::from_name(canonical_name);
        result.id = ResourceId{key.high, key.low};

        const OwnedKey owned_key{&world, key.high, key.low};
        WE::ErasedEvents *object = nullptr;
        {
            const std::lock_guard<std::mutex> lock{g_events_mutex};
            if (const auto existing = g_events.find(owned_key); existing != g_events.end()) {
                if (existing->second.events->element_size() != element_size) {
                    result.message = rust::String("a different event channel is already registered under that name");
                    result.code = EcsErrorCode::InvalidArgument;
                    return result;
                }
                result.ok = true;
                return result;
            }

            OwnedEventChannel owned;
            owned.events = std::make_unique<WE::ErasedEvents>(element_size);
            object = owned.events.get();
            g_events.emplace(owned_key, std::move(owned));
        }

        // `object` is a pointer to the `ErasedEvents` container itself, so the world is told the
        // container's own size/alignment (`sizeof`/`alignof(ErasedEvents)`), not `element_size` —
        // unlike `ecs_create_resource`, which binds a flat byte buffer directly.
        auto bound = world.bind_resource_erased(key, canonical_name, object, sizeof(WE::ErasedEvents),
                                                alignof(WE::ErasedEvents), &WE::clear_erased_events);
        if (!bound) {
            const std::lock_guard<std::mutex> lock{g_events_mutex};
            g_events.erase(owned_key);
            result.message = to_rust_string(bound.error().message.cpp_string_view());
            result.code = map_error_code(bound.error().code);
            return result;
        }
        result.ok = true;
        return result;
    }

    EcsStatus ecs_destroy_event_channel(EngineView &engine, ResourceId key) {
        WE::World &world = engine.ecs_world();
        const OwnedKey owned_key{&world, key.high, key.low};
        {
            const std::lock_guard<std::mutex> lock{g_events_mutex};
            if (g_events.find(owned_key) == g_events.end()) {
                return fail_status(EcsErrorCode::UnknownComponent, "no event channel owned by this binding is bound under that id");
            }
        }

        auto unbound = world.unbind_resource_erased(to_engine_key(key));
        if (!unbound) {
            return fail_status(map_error_code(unbound.error().code), unbound.error().message.cpp_string_view());
        }

        const std::lock_guard<std::mutex> lock{g_events_mutex};
        g_events.erase(owned_key);
        return ok_status();
    }

    EcsStatus ecs_send_event(EngineView &engine, ResourceId key, rust::Slice<const std::uint8_t> data) {
        WE::World &world = engine.ecs_world();
        const OwnedKey owned_key{&world, key.high, key.low};
        const std::lock_guard<std::mutex> lock{g_events_mutex};
        const auto found = g_events.find(owned_key);
        if (found == g_events.end()) {
            return fail_status(EcsErrorCode::UnknownComponent, "no event channel is bound under that id");
        }
        if (found->second.events->element_size() != data.size()) {
            return fail_status(EcsErrorCode::SizeMismatch, "supplied data does not match the channel's element size");
        }
        found->second.events->send(data.data());
        return ok_status();
    }

    // Read semantics: this shim never drives the engine's own `Ecs::Schedule`, which is what
    // normally drains an event buffer between runs via `clear_erased_events`
    // (`ScheduleConfig::clear_events_on_run`) — see the module doc above `g_events`. With no
    // scheduler in the loop, nothing else will ever clear a channel bound through this API, so a
    // "read" that only copies (leaving prior events to be handed back again next time, and the
    // buffer to grow forever) would silently break the moment a caller reads more than once.
    // Draining on read — copy out everything buffered, then clear — is the self-consistent choice
    // for a caller with no scheduler of its own: each read observes exactly the events sent since
    // the previous read (or since creation), matching what a caller intuitively expects from
    // "give me what's new" with no separate clear step required. `ecs_clear_event_channel` is
    // still available for a caller that wants to discard without reading.
    EventBatch ecs_read_events(EngineView &engine, ResourceId key) {
        EventBatch result{};
        WE::World &world = engine.ecs_world();
        const OwnedKey owned_key{&world, key.high, key.low};
        const std::lock_guard<std::mutex> lock{g_events_mutex};
        const auto found = g_events.find(owned_key);
        if (found == g_events.end()) {
            result.message = rust::String("no event channel is bound under that id");
            result.code = EcsErrorCode::UnknownComponent;
            return result;
        }

        WE::ErasedEvents &events = *found->second.events;
        const std::size_t element_size = events.element_size();
        const std::size_t count = events.size();
        result.element_size = static_cast<std::uint32_t>(element_size);
        result.count = static_cast<std::uint32_t>(count);
        result.data.reserve(count * element_size);
        for (std::size_t i = 0; i < count; ++i) {
            const auto *bytes = static_cast<const std::uint8_t *>(events.at(i));
            for (std::size_t byte = 0; byte < element_size; ++byte) {
                result.data.push_back(bytes[byte]);
            }
        }
        events.clear();
        result.ok = true;
        return result;
    }

    EcsStatus ecs_clear_event_channel(EngineView &engine, ResourceId key) {
        WE::World &world = engine.ecs_world();
        const OwnedKey owned_key{&world, key.high, key.low};
        const std::lock_guard<std::mutex> lock{g_events_mutex};
        const auto found = g_events.find(owned_key);
        if (found == g_events.end()) {
            return fail_status(EcsErrorCode::UnknownComponent, "no event channel is bound under that id");
        }
        found->second.events->clear();
        return ok_status();
    }

} // namespace sturdy_rs::ecs
