#include "sturdy_rs/reflection.hpp"

#include <array>
#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <optional>
#include <string>
#include <unordered_set>
#include <utility>
#include <span>
#include <string_view>
#include <variant>
#include <vector>

#include <Reflection/Reflection.hpp>

// Generated by build.rs from src/reflection.rs; defines the shared structs and their C++ types.
#include "sturdy_rs/reflection_bridge.h"

namespace sturdy_rs::reflection {

    // ---------------------------------------------------------------------------------------
    // This crate's own demo reflected type (see reflection_register_demo_type's doc comment in
    // reflection.rs for why it exists: the vendored engine has no small, stable, gameplay-shaped
    // reflected type of its own to exercise live-instance/method/container access against).
    // ---------------------------------------------------------------------------------------

    namespace demo {

        struct DemoActor {
            float x = 0.0f;
            float y = 0.0f;
            float z = 0.0f;
            int health = 100;
            std::vector<int> tags;
            std::optional<int> target;
            /// Reflected static field -- exercises `reflection_get_static_field`/
            /// `reflection_set_static_field` (one true address shared by every `DemoActor`, not
            /// per-instance storage).
            static inline int spawn_count = 0;

            /// Zero-argument, primitive-returning method -- exercises `reflection_invoke_method0`.
            int double_health() noexcept {
                return health * 2;
            }

            /// Non-zero-argument method -- exercises the descriptor-only side of
            /// `reflection_type_methods` (not invokable through this binding, by design).
            void heal(int amount) noexcept {
                health += amount;
            }
        };

    } // namespace demo

} // namespace sturdy_rs::reflection

SFT_REFLECT_TYPE(sturdy_rs::reflection::demo::DemoActor, "sturdy_rs.demo.actor");
SFT_REFLECT_FIELD(x);
SFT_REFLECT_FIELD(y);
SFT_REFLECT_FIELD(z);
SFT_REFLECT_FIELD(health, SFT_ATTR_STRING("units", "hp"), SFT_ATTR_INT("min", 0));
SFT_REFLECT_FIELD(tags);
SFT_REFLECT_FIELD(target);
SFT_REFLECT_STATIC_FIELD(spawn_count);
SFT_REFLECT_METHOD(double_health);
SFT_REFLECT_METHOD(heal);
SFT_REFLECT_EVENT("on_died");
SFT_REFLECT_END();

namespace sturdy_rs::reflection {
    namespace {

        namespace R = SFT::Reflection;

        rust::String to_rust_string(std::string_view text) {
            return rust::String::lossy(text.data(), text.size());
        }

        rust::String to_rust_string(const UString &text) {
            return to_rust_string(text.cpp_string_view());
        }

        PrimitiveKind map(R::PrimitiveKind kind) {
            switch (kind) {
            case R::PrimitiveKind::Bool: return PrimitiveKind::Bool;
            case R::PrimitiveKind::SignedInt: return PrimitiveKind::SignedInt;
            case R::PrimitiveKind::UnsignedInt: return PrimitiveKind::UnsignedInt;
            case R::PrimitiveKind::Float: return PrimitiveKind::Float;
            case R::PrimitiveKind::None:
            default: return PrimitiveKind::None;
            }
        }

        /// Fixed vocabulary of non-reflected fundamental type names (`StaticTypeId.hpp`'s
        /// `FundamentalTypeName` table, mirrored here since that table itself is compile-time-only
        /// and keyed by C++ type, not by runtime `TypeId`). Lets this binding recognize a
        /// primitive-typed field/parameter/return by name and know its size, without requiring that
        /// primitive to be a registered `TypeInfo` (most never are -- see `type_name_of`'s doc
        /// comment).
        struct FundamentalEntry {
            const char *name;
            std::size_t size;
            PrimitiveKind kind;
        };

        constexpr FundamentalEntry kFundamentals[] = {
            {"bool", sizeof(bool), PrimitiveKind::Bool},
            {"i8", sizeof(std::int8_t), PrimitiveKind::SignedInt},
            {"i16", sizeof(std::int16_t), PrimitiveKind::SignedInt},
            {"i32", sizeof(std::int32_t), PrimitiveKind::SignedInt},
            {"i64", sizeof(std::int64_t), PrimitiveKind::SignedInt},
            {"u8", sizeof(std::uint8_t), PrimitiveKind::UnsignedInt},
            {"u16", sizeof(std::uint16_t), PrimitiveKind::UnsignedInt},
            {"u32", sizeof(std::uint32_t), PrimitiveKind::UnsignedInt},
            {"u64", sizeof(std::uint64_t), PrimitiveKind::UnsignedInt},
            {"f32", sizeof(float), PrimitiveKind::Float},
            {"f64", sizeof(double), PrimitiveKind::Float},
            {"char", sizeof(char), PrimitiveKind::SignedInt},
            {"long long", sizeof(long long), PrimitiveKind::SignedInt},
            {"unsigned long long", sizeof(unsigned long long), PrimitiveKind::UnsignedInt},
        };

        /// `"void"` itself is a `FundamentalTypeName` entry too (see `StaticTypeId.hpp`), but is
        /// handled separately (`is_void_type`) since it never has a byte size to report.
        bool is_void_type(R::TypeId id) {
            return id == R::TypeId::from_name("void");
        }

        bool fundamental_size(std::string_view name, std::size_t &size, PrimitiveKind &kind) {
            for (const FundamentalEntry &entry : kFundamentals) {
                if (name == entry.name) {
                    size = entry.size;
                    kind = entry.kind;
                    return true;
                }
            }
            return false;
        }

        /// The field/enum/method's declared type name: first tries an actually-registered
        /// `TypeInfo` (a struct/class/enum), then falls back to the fixed fundamental-name
        /// vocabulary above (covers `int`/`float`/`bool`/... parameters and returns, which are
        /// never registered `TypeInfo`s -- see `Macros.hpp`'s `erased_type_id`). Empty when neither
        /// resolves (an unreflected struct, or any type identified only by a compiler-mangled RTTI
        /// name -- the `erased_type_id` fallback path).
        rust::String resolve_type_name(R::TypeId id) {
            const R::TypeInfo *found = R::TypeRegistry::instance().find(id);
            if (found != nullptr) {
                return to_rust_string(found->canonical_name);
            }
            if (is_void_type(id)) {
                return rust::String("void");
            }
            for (const FundamentalEntry &entry : kFundamentals) {
                if (id == R::TypeId::from_name(entry.name)) {
                    return rust::String(entry.name);
                }
            }
            return rust::String{};
        }

        /// Same as `resolve_type_name`, but only consulting the registry (never the fundamental
        /// vocabulary) -- kept for `FieldSummary::field_type_name`'s original, narrower contract
        /// (empty for a raw primitive field, matching the module's pre-existing documented
        /// behavior) so this pass doesn't silently change what already-shipped callers observe.
        rust::String type_name_of(R::TypeId id) {
            const R::TypeInfo *found = R::TypeRegistry::instance().find(id);
            return found != nullptr ? to_rust_string(found->canonical_name) : rust::String{};
        }

        /// Resolves `id`'s byte size the same way `reflection_invoke_method0` resolves a return
        /// type's size (a registered `TypeInfo`, or the fixed fundamental vocabulary) -- factored
        /// out so `reflection_fire_event` can validate every argument's declared size against the
        /// engine's own idea of that parameter's size before ever touching `fire_event`, which is
        /// what makes a mismatched caller-supplied byte layout a clean `false` instead of an
        /// out-of-bounds read.
        bool resolved_type_size(R::TypeId id, std::size_t &size) {
            const R::TypeInfo *found = R::TypeRegistry::instance().find(id);
            if (found != nullptr) {
                size = found->size;
                return true;
            }
            const rust::String name = resolve_type_name(id);
            PrimitiveKind unused_kind{};
            return fundamental_size(std::string_view{name.data(), name.size()}, size, unused_kind);
        }

        FieldSummary to_field_summary(const R::FieldInfo &field) {
            FieldSummary summary{};
            summary.name = to_rust_string(field.name);
            summary.field_type_name = type_name_of(field.field_type);
            summary.offset = static_cast<std::uint64_t>(field.offset);
            summary.size = static_cast<std::uint64_t>(field.size);
            summary.align = static_cast<std::uint64_t>(field.align);
            summary.is_static = R::has_flag(field.flags, R::FieldFlags::Static);
            summary.is_read_only = R::has_flag(field.flags, R::FieldFlags::ReadOnly);
            summary.is_trivial = R::has_flag(field.flags, R::FieldFlags::Trivial);
            summary.is_container = field.container != nullptr;
            summary.is_map = field.map != nullptr;
            summary.is_set = field.set != nullptr;
            summary.is_optional = field.optional != nullptr;
            summary.primitive_kind = map(field.primitive_kind);
            return summary;
        }

        MethodSummary to_method_summary(const R::MethodInfo &method) {
            MethodSummary summary{};
            summary.name = to_rust_string(method.name);
            summary.is_static = method.is_static;
            summary.param_type_names.reserve(method.param_types.size());
            for (R::TypeId param : method.param_types) {
                summary.param_type_names.push_back(resolve_type_name(param));
            }
            summary.return_type_name = resolve_type_name(method.return_type);
            summary.return_is_void = is_void_type(method.return_type);
            return summary;
        }

        ConstructorSummary to_constructor_summary(const R::ConstructorInfo &ctor) {
            ConstructorSummary summary{};
            summary.param_type_names.reserve(ctor.param_types.size());
            for (R::TypeId param : ctor.param_types) {
                summary.param_type_names.push_back(resolve_type_name(param));
            }
            return summary;
        }

        AttributeSummary to_attribute_summary(const R::Attribute &attribute) {
            AttributeSummary summary{};
            summary.name = to_rust_string(attribute.name);
            std::visit(
                [&](const auto &value) {
                    using Value = std::decay_t<decltype(value)>;
                    if constexpr (std::is_same_v<Value, bool>) {
                        summary.kind = AttributeKind::Bool;
                        summary.bool_value = value;
                    } else if constexpr (std::is_same_v<Value, std::int64_t>) {
                        summary.kind = AttributeKind::SignedInt;
                        summary.int_value = value;
                    } else if constexpr (std::is_same_v<Value, double>) {
                        summary.kind = AttributeKind::Float;
                        summary.float_value = value;
                    } else {
                        summary.kind = AttributeKind::String;
                        summary.string_value = to_rust_string(value);
                    }
                },
                attribute.value);
            return summary;
        }

        template <class Described>
        rust::Vec<AttributeSummary> to_attribute_summaries(const Described &described) {
            rust::Vec<AttributeSummary> attributes;
            attributes.reserve(described.attributes.size());
            for (const R::Attribute &attribute : described.attributes) {
                attributes.push_back(to_attribute_summary(attribute));
            }
            return attributes;
        }

        const R::TypeInfo *find_type(rust::Str name) {
            const std::string_view view{name.data(), name.size()};
            return R::TypeRegistry::instance().find(SFT::ustr{view});
        }

        /// Finds `field_name` among `type`'s own declared fields (not inherited -- matches every
        /// other lookup in this file, which stays declared-only).
        const R::FieldInfo *find_field(const R::TypeInfo &type, rust::Str field_name) {
            const std::string_view view{field_name.data(), field_name.size()};
            return type.find_field(view);
        }

    } // namespace

    rust::Vec<rust::String> reflection_type_names() {
        rust::Vec<rust::String> names;
        R::TypeRegistry::instance().for_each_type(
            [&](const R::TypeInfo &info) { names.push_back(to_rust_string(info.canonical_name)); });
        return names;
    }

    bool reflection_find_type(rust::Str name, TypeSummary &out) {
        const R::TypeInfo *found = find_type(name);
        if (found == nullptr) {
            return false;
        }
        out = TypeSummary{};
        out.name = to_rust_string(found->canonical_name);
        out.size = static_cast<std::uint64_t>(found->size);
        out.align = static_cast<std::uint64_t>(found->align);
        out.field_count = static_cast<std::uint64_t>(found->fields.size());
        out.method_count = static_cast<std::uint64_t>(found->methods.size());
        out.has_base = static_cast<bool>(found->base_type);
        out.base_name = out.has_base ? type_name_of(found->base_type) : rust::String{};
        out.secondary_base_count = static_cast<std::uint64_t>(found->secondary_bases.size());
        out.has_default_constructor = found->default_construct != nullptr;
        return true;
    }

    rust::Vec<FieldSummary> reflection_type_fields(rust::Str name) {
        rust::Vec<FieldSummary> fields;
        const R::TypeInfo *found = find_type(name);
        if (found == nullptr) {
            return fields;
        }
        fields.reserve(found->fields.size() + found->static_fields.size());
        for (const R::FieldInfo &field : found->fields) {
            fields.push_back(to_field_summary(field));
        }
        for (const R::FieldInfo &field : found->static_fields) {
            fields.push_back(to_field_summary(field));
        }
        return fields;
    }

    bool reflection_find_enum(rust::Str name, EnumSummary &out) {
        const std::string_view view{name.data(), name.size()};
        const R::EnumInfo *found = R::TypeRegistry::instance().find_enum(SFT::ustr{view});
        if (found == nullptr) {
            return false;
        }
        out = EnumSummary{};
        out.name = to_rust_string(found->canonical_name);
        out.size = static_cast<std::uint64_t>(found->size);
        out.align = static_cast<std::uint64_t>(found->align);
        out.underlying_type_name = type_name_of(found->underlying_type);
        out.enumerator_count = static_cast<std::uint64_t>(found->enumerators.size());
        return true;
    }

    rust::Vec<EnumeratorSummary> reflection_enum_values(rust::Str name) {
        rust::Vec<EnumeratorSummary> values;
        const std::string_view view{name.data(), name.size()};
        const R::EnumInfo *found = R::TypeRegistry::instance().find_enum(SFT::ustr{view});
        if (found == nullptr) {
            return values;
        }
        values.reserve(found->enumerators.size());
        for (const R::EnumeratorInfo &enumerator : found->enumerators) {
            EnumeratorSummary summary{};
            summary.name = to_rust_string(enumerator.name);
            summary.value = static_cast<std::int64_t>(enumerator.value);
            values.push_back(summary);
        }
        return values;
    }

    rust::Vec<MethodSummary> reflection_type_methods(rust::Str name) {
        rust::Vec<MethodSummary> methods;
        const R::TypeInfo *found = find_type(name);
        if (found == nullptr) {
            return methods;
        }
        methods.reserve(found->methods.size() + found->static_methods.size());
        for (const R::MethodInfo &method : found->methods) {
            methods.push_back(to_method_summary(method));
        }
        for (const R::MethodInfo &method : found->static_methods) {
            methods.push_back(to_method_summary(method));
        }
        return methods;
    }

    rust::Vec<ConstructorSummary> reflection_type_constructors(rust::Str name) {
        rust::Vec<ConstructorSummary> constructors;
        const R::TypeInfo *found = find_type(name);
        if (found == nullptr) {
            return constructors;
        }
        constructors.reserve(found->constructors.size());
        for (const R::ConstructorInfo &ctor : found->constructors) {
            constructors.push_back(to_constructor_summary(ctor));
        }
        return constructors;
    }

    bool reflection_default_construct(rust::Str name, rust::Slice<std::uint8_t> out) {
        const R::TypeInfo *found = find_type(name);
        if (found == nullptr || out.size() != found->size) {
            return false;
        }
        return R::default_construct_instance(*found, out.data());
    }

    bool reflection_destroy_instance(rust::Str name, rust::Slice<std::uint8_t> instance) {
        const R::TypeInfo *found = find_type(name);
        if (found == nullptr || instance.size() != found->size) {
            return false;
        }
        R::destroy_instance(*found, instance.data());
        return true;
    }

    MethodInvokeResult reflection_invoke_method0(rust::Str type_name, rust::Str method_name, rust::Slice<std::uint8_t> object) {
        MethodInvokeResult result{};
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            result.error = rust::String("unknown type");
            return result;
        }
        if (object.size() != found->size) {
            result.error = rust::String("object buffer size does not match the type's registered size");
            return result;
        }
        const std::string_view method_view{method_name.data(), method_name.size()};
        // Exact zero-argument overload only -- disambiguates an overload set the same way
        // `find_method(name, param_types)` is meant to (see `TypeInfo::find_method`'s doc comment).
        const R::MethodInfo *method = found->find_method(method_view, std::span<const R::TypeId>{});
        if (method == nullptr) {
            result.error = rust::String("no zero-argument method with that name");
            return result;
        }

        result.return_type_name = resolve_type_name(method->return_type);
        result.return_is_void = is_void_type(method->return_type);

        std::vector<unsigned char> buffer;
        void *out_return = nullptr;
        if (!result.return_is_void) {
            const R::TypeInfo *return_type = R::TypeRegistry::instance().find(method->return_type);
            std::size_t size = 0;
            if (return_type != nullptr) {
                size = return_type->size;
            } else if (!fundamental_size(std::string_view{result.return_type_name.data(), result.return_type_name.size()}, size, result.primitive_kind)) {
                result.error = rust::String("return type is not void, a registered type, or a known fundamental type");
                return result;
            }
            buffer.resize(size);
            out_return = size != 0 ? buffer.data() : nullptr;
        }

        void *object_ptr = method->is_static ? nullptr : static_cast<void *>(object.data());
        R::InvokeException exception{};
        const bool invoked = R::invoke_method(*method, object_ptr, nullptr, 0, out_return, &exception);
        if (!invoked) {
            result.error = rust::String("method has no invokable representation");
            return result;
        }
        if (exception.threw) {
            result.error = to_rust_string(exception.message);
            return result;
        }
        result.ok = true;
        if (!buffer.empty()) {
            result.data.reserve(buffer.size());
            for (unsigned char byte : buffer) {
                result.data.push_back(byte);
            }
        }
        return result;
    }

    bool reflection_field_container(rust::Str type_name, rust::Str field_name, ContainerSummary &out) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return false;
        }
        const R::FieldInfo *field = find_field(*found, field_name);
        if (field == nullptr) {
            return false;
        }
        out = ContainerSummary{};
        if (field->container != nullptr) {
            out.kind = ContainerKind::Vector;
            out.element_type_name = resolve_type_name(field->container->element_type);
            out.element_primitive_kind = map(field->container->element_primitive_kind);
            return true;
        }
        if (field->map != nullptr) {
            out.kind = ContainerKind::Map;
            out.key_type_name = resolve_type_name(field->map->key_type);
            out.key_primitive_kind = map(field->map->key_primitive_kind);
            out.element_type_name = resolve_type_name(field->map->value_type);
            out.element_primitive_kind = map(field->map->value_primitive_kind);
            return true;
        }
        if (field->set != nullptr) {
            out.kind = ContainerKind::Set;
            out.element_type_name = resolve_type_name(field->set->element_type);
            out.element_primitive_kind = map(field->set->element_primitive_kind);
            return true;
        }
        if (field->optional != nullptr) {
            out.kind = ContainerKind::Optional;
            out.element_type_name = resolve_type_name(field->optional->value_type);
            out.element_primitive_kind = map(field->optional->value_primitive_kind);
            return true;
        }
        return false;
    }

    bool reflection_get_static_field(rust::Str type_name, rust::Str field_name, rust::Slice<std::uint8_t> out) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return false;
        }
        const R::FieldInfo *field = find_field(*found, field_name);
        if (field == nullptr || !R::has_flag(field->flags, R::FieldFlags::Static)) {
            return false;
        }
        return R::copy_static_field_out(*field, out.data(), out.size());
    }

    bool reflection_set_static_field(rust::Str type_name, rust::Str field_name, rust::Slice<const std::uint8_t> data) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return false;
        }
        const R::FieldInfo *field = find_field(*found, field_name);
        if (field == nullptr || !R::has_flag(field->flags, R::FieldFlags::Static)) {
            return false;
        }
        return R::copy_static_field_in(*field, data.data(), data.size());
    }

    std::uint64_t reflection_container_size(rust::Str type_name, rust::Str field_name, rust::Slice<const std::uint8_t> instance) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return 0;
        }
        const R::FieldInfo *field = find_field(*found, field_name);
        if (field == nullptr || field->container == nullptr || field->offset + field->size > instance.size()) {
            return 0;
        }
        const void *container = instance.data() + field->offset;
        return static_cast<std::uint64_t>(R::container_size(field->container, container));
    }

    bool reflection_container_get_element(rust::Str type_name, rust::Str field_name, rust::Slice<const std::uint8_t> instance,
                                          std::uint64_t index, rust::Slice<std::uint8_t> out) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return false;
        }
        const R::FieldInfo *field = find_field(*found, field_name);
        if (field == nullptr || field->container == nullptr || !field->container->element_trivial ||
            out.size() != field->container->element_size || field->offset + field->size > instance.size()) {
            return false;
        }
        const void *container = instance.data() + field->offset;
        return R::container_get_element(field->container, container, static_cast<SFT::usize>(index), out.data());
    }

    bool reflection_container_set_element(rust::Str type_name, rust::Str field_name, rust::Slice<std::uint8_t> instance,
                                          std::uint64_t index, rust::Slice<const std::uint8_t> data) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return false;
        }
        const R::FieldInfo *field = find_field(*found, field_name);
        if (field == nullptr || field->container == nullptr || !field->container->element_trivial ||
            data.size() != field->container->element_size || field->offset + field->size > instance.size()) {
            return false;
        }
        void *container = instance.data() + field->offset;
        return R::container_set_element(field->container, container, static_cast<SFT::usize>(index), data.data());
    }

    bool reflection_container_resize(rust::Str type_name, rust::Str field_name, rust::Slice<std::uint8_t> instance,
                                     std::uint64_t new_size) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return false;
        }
        const R::FieldInfo *field = find_field(*found, field_name);
        if (field == nullptr || field->container == nullptr || field->offset + field->size > instance.size()) {
            return false;
        }
        void *container = instance.data() + field->offset;
        return R::container_resize(field->container, container, static_cast<SFT::usize>(new_size));
    }

    rust::Vec<AttributeSummary> reflection_type_attributes(rust::Str name) {
        const R::TypeInfo *found = find_type(name);
        return found != nullptr ? to_attribute_summaries(*found) : rust::Vec<AttributeSummary>{};
    }

    rust::Vec<AttributeSummary> reflection_field_attributes(rust::Str type_name, rust::Str field_name) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return {};
        }
        const R::FieldInfo *field = find_field(*found, field_name);
        return field != nullptr ? to_attribute_summaries(*field) : rust::Vec<AttributeSummary>{};
    }

    rust::Vec<EventSummary> reflection_type_events(rust::Str name) {
        rust::Vec<EventSummary> events;
        const R::TypeInfo *found = find_type(name);
        if (found == nullptr) {
            return events;
        }
        events.reserve(found->events.size());
        for (const R::EventInfo &event : found->events) {
            EventSummary summary{};
            summary.name = to_rust_string(event.name);
            summary.param_type_names.reserve(event.param_types.size());
            for (R::TypeId param : event.param_types) {
                summary.param_type_names.push_back(resolve_type_name(param));
            }
            events.push_back(summary);
        }
        return events;
    }

    bool reflection_find_event(rust::Str type_name, rust::Str event_name, EventSummary &out) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr) {
            return false;
        }
        const std::string_view view{event_name.data(), event_name.size()};
        const R::EventInfo *event = found->find_event(view);
        if (event == nullptr) {
            return false;
        }
        out = EventSummary{};
        out.name = to_rust_string(event->name);
        out.param_type_names.reserve(event->param_types.size());
        for (R::TypeId param : event->param_types) {
            out.param_type_names.push_back(resolve_type_name(param));
        }
        return true;
    }

    bool reflection_fire_event(rust::Str type_name, rust::Str event_name, rust::Slice<std::uint8_t> object,
                               rust::Slice<const std::uint32_t> arg_sizes, rust::Slice<const std::uint8_t> args_data) {
        const R::TypeInfo *found = find_type(type_name);
        if (found == nullptr || object.size() != found->size) {
            return false;
        }
        const std::string_view view{event_name.data(), event_name.size()};
        const R::EventInfo *event = found->find_event(view);
        if (event == nullptr || arg_sizes.size() != event->param_types.size()) {
            return false;
        }

        // Validate every argument's caller-declared size against the engine's own idea of that
        // parameter's size *before* building any pointer into `args_data` -- see
        // `resolved_type_size`'s doc comment for why this is the safety boundary here.
        std::vector<std::size_t> offsets;
        offsets.reserve(arg_sizes.size());
        std::size_t offset = 0;
        for (std::size_t i = 0; i < arg_sizes.size(); ++i) {
            std::size_t expected_size = 0;
            if (!resolved_type_size(event->param_types[i], expected_size) || expected_size != arg_sizes[i]) {
                return false;
            }
            offsets.push_back(offset);
            offset += arg_sizes[i];
        }
        if (offset != args_data.size()) {
            return false;
        }

        std::vector<const void *> arg_pointers;
        arg_pointers.reserve(offsets.size());
        for (std::size_t i = 0; i < offsets.size(); ++i) {
            arg_pointers.push_back(arg_sizes[i] != 0 ? args_data.data() + offsets[i] : nullptr);
        }

        R::fire_event(*event, object.data(), arg_pointers.data());
        return true;
    }

    void reflection_register_demo_type() {
        (void)R::TypeRegistry::instance().type<demo::DemoActor>();
    }

    namespace {

        const R::MethodInfo *find_method_by_name(const R::TypeInfo &type, rust::Str method_name) {
            return type.find_method(std::string_view{method_name.data(), method_name.size()});
        }

        void method_trampoline(void *object, const void *const *args, void *out_return, void *user_data) noexcept {
            rust_reflection_callback_run(static_cast<RustReflectionCallback *>(user_data), static_cast<std::uint8_t *>(object),
                                         reinterpret_cast<const std::uint8_t *const *>(args),
                                         static_cast<std::uint8_t *>(out_return));
        }

        void listener_trampoline(void *object, const void *const *args, void *user_data) noexcept {
            rust_reflection_callback_run(static_cast<RustReflectionCallback *>(user_data), static_cast<std::uint8_t *>(object),
                                         reinterpret_cast<const std::uint8_t *const *>(args), nullptr);
        }

        CallableLayout layout_of(const R::TypeInfo &type, std::span<const R::TypeId> params, R::TypeId return_type,
                                 bool has_return, bool is_static) {
            CallableLayout out{};
            out.object_size = static_cast<std::uint64_t>(type.size);
            out.is_static = is_static;
            for (R::TypeId param : params) {
                std::size_t size = 0;
                if (!resolved_type_size(param, size)) {
                    return out;
                }
                out.param_sizes.push_back(static_cast<std::uint64_t>(size));
            }
            if (has_return && !is_void_type(return_type)) {
                std::size_t size = 0;
                if (!resolved_type_size(return_type, size)) {
                    return out;
                }
                out.return_size = static_cast<std::uint64_t>(size);
            }
            out.ok = true;
            return out;
        }

    } // namespace

    CallableLayout reflection_method_layout(rust::Str type_name, rust::Str method_name) {
        const R::TypeInfo *type = find_type(type_name);
        const R::MethodInfo *method = type != nullptr ? find_method_by_name(*type, method_name) : nullptr;
        if (method == nullptr) {
            return CallableLayout{};
        }
        return layout_of(*type, method->param_types, method->return_type, true, method->is_static);
    }

    CallableLayout reflection_event_layout(rust::Str type_name, rust::Str event_name) {
        const R::TypeInfo *type = find_type(type_name);
        const R::EventInfo *event =
            type != nullptr ? type->find_event(std::string_view{event_name.data(), event_name.size()}) : nullptr;
        if (event == nullptr) {
            return CallableLayout{};
        }
        return layout_of(*type, event->param_types, R::TypeId{}, false, false);
    }

    bool reflection_set_method_override(rust::Str type_name, rust::Str method_name, RustReflectionCallback *callback) {
        const R::TypeInfo *type = find_type(type_name);
        const R::MethodInfo *method = type != nullptr ? find_method_by_name(*type, method_name) : nullptr;
        if (method == nullptr) {
            return false;
        }
        return R::TypeRegistry::instance().set_method_override(type->key, method->key, &method_trampoline, callback);
    }

    bool reflection_clear_method_override(rust::Str type_name, rust::Str method_name) {
        const R::TypeInfo *type = find_type(type_name);
        const R::MethodInfo *method = type != nullptr ? find_method_by_name(*type, method_name) : nullptr;
        if (method == nullptr) {
            return false;
        }
        return R::TypeRegistry::instance().clear_method_override(type->key, method->key);
    }

    std::uint64_t reflection_add_method_hook(rust::Str type_name, rust::Str method_name, bool after,
                                             RustReflectionCallback *callback) {
        const R::TypeInfo *type = find_type(type_name);
        const R::MethodInfo *method = type != nullptr ? find_method_by_name(*type, method_name) : nullptr;
        if (method == nullptr) {
            return 0;
        }
        auto &registry = R::TypeRegistry::instance();
        const auto subscription = after ? registry.add_method_after_hook(type->key, method->key, &listener_trampoline, callback)
                                        : registry.add_method_before_hook(type->key, method->key, &listener_trampoline, callback);
        return subscription ? subscription->id : 0;
    }

    bool reflection_remove_method_hook(rust::Str type_name, rust::Str method_name, bool after, std::uint64_t subscription) {
        const R::TypeInfo *type = find_type(type_name);
        const R::MethodInfo *method = type != nullptr ? find_method_by_name(*type, method_name) : nullptr;
        if (method == nullptr) {
            return false;
        }
        auto &registry = R::TypeRegistry::instance();
        const R::Multicast::Subscription sub{subscription};
        return after ? registry.remove_method_after_hook(type->key, method->key, sub)
                     : registry.remove_method_before_hook(type->key, method->key, sub);
    }

    std::uint64_t reflection_subscribe_event(rust::Str type_name, rust::Str event_name, RustReflectionCallback *callback) {
        const R::TypeInfo *type = find_type(type_name);
        const R::EventInfo *event =
            type != nullptr ? type->find_event(std::string_view{event_name.data(), event_name.size()}) : nullptr;
        if (event == nullptr) {
            return 0;
        }
        return event->listeners.subscribe(&listener_trampoline, callback).id;
    }

    bool reflection_unsubscribe_event(rust::Str type_name, rust::Str event_name, std::uint64_t subscription) {
        const R::TypeInfo *type = find_type(type_name);
        const R::EventInfo *event =
            type != nullptr ? type->find_event(std::string_view{event_name.data(), event_name.size()}) : nullptr;
        if (event == nullptr) {
            return false;
        }
        return event->listeners.unsubscribe(R::Multicast::Subscription{subscription});
    }

    // ---------------------------------------------------------------------------------------
    // Runtime type registration
    // ---------------------------------------------------------------------------------------

    namespace {

        /// Names of types registered through `DynamicTypeBuilder`. Those are plain bytes (memcpy
        /// move/copy, no-op destroy), so they're safe as fields of other runtime types and as
        /// byte-marshalled `reflection_invoke_method` arguments, unlike an arbitrary registered
        /// C++ type.
        std::mutex g_dynamic_types_mutex;
        std::unordered_set<std::string> g_dynamic_types;

        bool is_dynamic_type(std::string_view name) {
            const std::lock_guard lock{g_dynamic_types_mutex};
            return g_dynamic_types.contains(std::string{name});
        }

        /// Size of `id` when it's plain bytes: a fundamental or a runtime-registered type.
        bool plain_type_size(R::TypeId id, std::size_t &size) {
            const rust::String name = resolve_type_name(id);
            const std::string_view view{name.data(), name.size()};
            PrimitiveKind unused_kind{};
            if (fundamental_size(view, size, unused_kind)) {
                return true;
            }
            if (!view.empty() && is_dynamic_type(view)) {
                const R::TypeInfo *found = R::TypeRegistry::instance().find(id);
                if (found != nullptr) {
                    size = found->size;
                    return true;
                }
            }
            return false;
        }

        /// Per-type constructor state (`TypeInfo::user_data`). Leaked: the registry never frees
        /// descriptors, so a stale `TypeInfo` pointer may still construct through it.
        struct DynamicTypeData {
            std::size_t size = 0;
            std::vector<std::uint8_t> default_bytes;
        };

        void dynamic_move(void *destination, void *source, void *user_data) noexcept {
            std::memcpy(destination, source, static_cast<DynamicTypeData *>(user_data)->size);
        }

        void dynamic_copy(void *destination, const void *source, void *user_data) noexcept {
            std::memcpy(destination, source, static_cast<DynamicTypeData *>(user_data)->size);
        }

        void dynamic_default(void *destination, void *user_data) noexcept {
            const auto *data = static_cast<DynamicTypeData *>(user_data);
            std::memcpy(destination, data->default_bytes.data(), data->size);
        }

        void dynamic_destroy(void *, void *) noexcept {}

        /// `MethodInfo::invoke` carries no user data (only overrides do), so each Rust-bodied
        /// method gets its own trampoline from a fixed table, indexed into `g_method_slots`.
        /// Slots are never recycled: a stale `MethodInfo` could still call through one.
        constexpr std::size_t kMethodSlots = 1024;
        std::array<std::atomic<RustReflectionCallback *>, kMethodSlots> g_method_slots{};
        std::atomic<std::size_t> g_next_method_slot{0};

        template <std::size_t Index>
        void slot_invoke(void *object, const void *const *args, void *out_return, void *) noexcept {
            rust_reflection_callback_run(g_method_slots[Index].load(std::memory_order_acquire),
                                         static_cast<std::uint8_t *>(object),
                                         reinterpret_cast<const std::uint8_t *const *>(args),
                                         static_cast<std::uint8_t *>(out_return));
        }

        template <std::size_t... Indices>
        constexpr std::array<R::MethodInvokeFn, sizeof...(Indices)> make_slot_invokers(std::index_sequence<Indices...>) {
            return {&slot_invoke<Indices>...};
        }

        constexpr auto kSlotInvokers = make_slot_invokers(std::make_index_sequence<kMethodSlots>{});

        R::Attribute to_attribute(const AttributeSummary &summary) {
            const std::string_view name{summary.name.data(), summary.name.size()};
            R::Attribute attribute{};
            attribute.key = R::TypeId::from_name(name);
            attribute.name = UString{name};
            switch (summary.kind) {
            case AttributeKind::Bool: attribute.value = summary.bool_value; break;
            case AttributeKind::SignedInt: attribute.value = static_cast<SFT::i64>(summary.int_value); break;
            case AttributeKind::Float: attribute.value = static_cast<SFT::f64>(summary.float_value); break;
            case AttributeKind::String:
            default: attribute.value = UString{std::string_view{summary.string_value.data(), summary.string_value.size()}}; break;
            }
            return attribute;
        }

        /// Resolves a Rust-supplied type name for a method/event signature: `"void"` only where
        /// `allow_void`, otherwise a plain-bytes type (so `layout_of` and byte marshalling work).
        bool signature_type(rust::Str name, bool allow_void, R::TypeId &out) {
            std::string_view view{name.data(), name.size()};
            if (view.empty() && allow_void) {
                view = "void";
            }
            out = R::TypeId::from_name(view);
            if (view == "void") {
                return allow_void;
            }
            std::size_t size = 0;
            return plain_type_size(out, size);
        }

    } // namespace

    DynamicTypeBuilder::DynamicTypeBuilder(std::string_view type_name, std::size_t type_size, std::size_t type_align)
        : name(type_name), size(type_size), builder(type_name, type_size, type_align) {}

    DynamicTypeBuilder::~DynamicTypeBuilder() {
        for (PendingMethod &method : methods) {
            if (method.callback != nullptr) {
                rust_reflection_callback_drop(method.callback);
            }
        }
    }

    std::uint64_t reflection_type_size(rust::Str type_name) {
        std::size_t size = 0;
        return resolved_type_size(R::TypeId::from_name(std::string_view{type_name.data(), type_name.size()}), size) ? size : 0;
    }

    std::unique_ptr<DynamicTypeBuilder> reflection_type_builder_new(rust::Str name, std::uint64_t size, std::uint64_t align,
                                                                    rust::Slice<const std::uint8_t> default_bytes) {
        auto builder = std::make_unique<DynamicTypeBuilder>(std::string_view{name.data(), name.size()}, size, align);
        if (name.size() == 0) {
            builder->error = rust::String("type name must not be empty");
        } else if (size == 0) {
            builder->error = rust::String("size must be nonzero");
        } else if (align == 0 || (align & (align - 1)) != 0) {
            builder->error = rust::String("align must be a nonzero power of two");
        } else if (!default_bytes.empty() && default_bytes.size() != size) {
            builder->error = rust::String("default_bytes must be empty or exactly `size` bytes");
        }
        builder->default_bytes.assign(size, 0);
        if (default_bytes.size() == size) {
            std::memcpy(builder->default_bytes.data(), default_bytes.data(), size);
        }
        return builder;
    }

    rust::String reflection_type_builder_add_field(DynamicTypeBuilder &builder, rust::Str name, std::uint64_t offset,
                                                   rust::Str type_name, const rust::Vec<AttributeSummary> &attributes) {
        const std::string_view name_view{name.data(), name.size()};
        const R::TypeId field_type = R::TypeId::from_name(std::string_view{type_name.data(), type_name.size()});
        std::size_t field_size = 0;
        if (name_view.empty()) {
            return rust::String("field name must not be empty");
        }
        if (!plain_type_size(field_type, field_size)) {
            return rust::String("field type must be a fundamental or a runtime-registered type");
        }
        if (offset + field_size > builder.size) {
            return rust::String("field extends past the end of the type");
        }
        std::size_t field_align = field_size;
        if (const R::TypeInfo *found = R::TypeRegistry::instance().find(field_type); found != nullptr) {
            field_align = found->align;
        }
        if (field_align != 0 && offset % field_align != 0) {
            return rust::String("field offset is misaligned for its type");
        }
        std::vector<R::Attribute> converted;
        converted.reserve(attributes.size());
        for (const AttributeSummary &attribute : attributes) {
            converted.push_back(to_attribute(attribute));
        }
        builder.builder.field(name_view, offset, field_size, field_align, field_type, R::FieldFlags::Trivial, nullptr, nullptr,
                              std::move(converted));
        return rust::String{};
    }

    rust::String reflection_type_builder_add_method(DynamicTypeBuilder &builder, rust::Str name, rust::Str return_type_name,
                                                    const rust::Vec<rust::String> &param_type_names,
                                                    RustReflectionCallback *callback) {
        DynamicTypeBuilder::PendingMethod method{};
        method.name = std::string{name.data(), name.size()};
        method.callback = callback;
        // Owned from here on, so the builder's destructor frees it on every failure path.
        builder.methods.push_back(std::move(method));
        DynamicTypeBuilder::PendingMethod &pending = builder.methods.back();
        if (pending.name.empty()) {
            return rust::String("method name must not be empty");
        }
        if (!signature_type(return_type_name, true, pending.return_type)) {
            return rust::String("return type must be void, a fundamental, or a runtime-registered type");
        }
        for (const rust::String &param : param_type_names) {
            R::TypeId id{};
            if (!signature_type(rust::Str{param.data(), param.size()}, false, id)) {
                return rust::String("parameter types must be fundamentals or runtime-registered types");
            }
            pending.param_types.push_back(id);
        }
        return rust::String{};
    }

    rust::String reflection_type_builder_add_event(DynamicTypeBuilder &builder, rust::Str name,
                                                   const rust::Vec<rust::String> &param_type_names) {
        if (name.size() == 0) {
            return rust::String("event name must not be empty");
        }
        std::vector<R::TypeId> params;
        for (const rust::String &param : param_type_names) {
            R::TypeId id{};
            if (!signature_type(rust::Str{param.data(), param.size()}, false, id)) {
                return rust::String("parameter types must be fundamentals or runtime-registered types");
            }
            params.push_back(id);
        }
        builder.builder.event(std::string_view{name.data(), name.size()}, std::move(params));
        return rust::String{};
    }

    void reflection_type_builder_add_type_attribute(DynamicTypeBuilder &builder, const AttributeSummary &attribute) {
        builder.builder.type_attribute(to_attribute(attribute));
    }

    rust::String reflection_type_builder_finish(std::unique_ptr<DynamicTypeBuilder> builder) {
        if (!builder->error.empty()) {
            return builder->error;
        }
        auto &registry = R::TypeRegistry::instance();
        if (registry.find(SFT::ustr{std::string_view{builder->name}}) != nullptr) {
            // `register_type` would silently return the existing key for a same-named type,
            // leaving this builder's layout and methods unused.
            return rust::String("a type with this name is already registered");
        }
        const std::size_t first_slot = g_next_method_slot.fetch_add(builder->methods.size());
        if (first_slot + builder->methods.size() > kMethodSlots) {
            return rust::String("out of runtime method slots");
        }
        for (std::size_t i = 0; i < builder->methods.size(); ++i) {
            DynamicTypeBuilder::PendingMethod &method = builder->methods[i];
            g_method_slots[first_slot + i].store(method.callback, std::memory_order_release);
            method.callback = nullptr; // the slot owns it now, permanently
            builder->builder.method(method.name, method.return_type, std::move(method.param_types), kSlotInvokers[first_slot + i]);
        }
        auto *data = new DynamicTypeData{builder->size, std::move(builder->default_bytes)};
        builder->builder.constructors(&dynamic_move, &dynamic_destroy, &dynamic_default, &dynamic_copy, data);
        {
            // Before registering, so another thread can't observe the type without it.
            const std::lock_guard lock{g_dynamic_types_mutex};
            g_dynamic_types.insert(builder->name);
        }
        auto registered = registry.register_type(builder->builder.build());
        if (!registered) {
            const std::lock_guard lock{g_dynamic_types_mutex};
            g_dynamic_types.erase(builder->name);
            return to_rust_string(registered.error().message);
        }
        return rust::String{};
    }

    bool reflection_unregister_type(rust::Str type_name) {
        const std::string_view view{type_name.data(), type_name.size()};
        if (!R::TypeRegistry::instance().unregister_type(SFT::ustr{view})) {
            return false;
        }
        const std::lock_guard lock{g_dynamic_types_mutex};
        g_dynamic_types.erase(std::string{view});
        return true;
    }

    rust::String reflection_invoke_method(rust::Str type_name, rust::Str method_name, rust::Slice<std::uint8_t> object,
                                          rust::Slice<const std::uint32_t> arg_sizes, rust::Slice<const std::uint8_t> args_data,
                                          rust::Slice<std::uint8_t> out_return) {
        const R::TypeInfo *type = find_type(type_name);
        if (type == nullptr) {
            return rust::String("unknown type");
        }
        const R::MethodInfo *method = find_method_by_name(*type, method_name);
        if (method == nullptr) {
            return rust::String("unknown method");
        }
        if (!method->is_static && object.size() != type->size) {
            return rust::String("object buffer size does not match the type's registered size");
        }
        if (arg_sizes.size() != method->param_types.size()) {
            return rust::String("argument count does not match the method's parameter count");
        }
        std::vector<const void *> arg_pointers;
        std::size_t cursor = 0;
        for (std::size_t i = 0; i < arg_sizes.size(); ++i) {
            std::size_t size = 0;
            if (!plain_type_size(method->param_types[i], size)) {
                return rust::String("a parameter type is not a fundamental or runtime-registered type");
            }
            if (size != arg_sizes[i] || cursor + size > args_data.size()) {
                return rust::String("an argument's size does not match its parameter type");
            }
            arg_pointers.push_back(args_data.data() + cursor);
            cursor += size;
        }
        if (cursor != args_data.size()) {
            return rust::String("argument bytes left over");
        }
        std::size_t return_size = 0;
        if (!is_void_type(method->return_type) && !plain_type_size(method->return_type, return_size)) {
            return rust::String("return type is not void, a fundamental, or a runtime-registered type");
        }
        if (out_return.size() != return_size) {
            return rust::String("return buffer size does not match the return type");
        }
        // Arguments are copied into aligned storage: `args_data` is packed.
        std::vector<std::vector<std::max_align_t>> aligned(arg_pointers.size());
        for (std::size_t i = 0; i < arg_pointers.size(); ++i) {
            aligned[i].resize((arg_sizes[i] + sizeof(std::max_align_t) - 1) / sizeof(std::max_align_t) + 1);
            std::memcpy(aligned[i].data(), arg_pointers[i], arg_sizes[i]);
            arg_pointers[i] = aligned[i].data();
        }
        std::vector<std::max_align_t> return_storage((return_size + sizeof(std::max_align_t) - 1) / sizeof(std::max_align_t) + 1);
        void *object_ptr = method->is_static ? nullptr : static_cast<void *>(object.data());
        R::InvokeException exception{};
        if (!R::invoke_method(*method, object_ptr, arg_pointers.data(), arg_pointers.size(),
                              return_size != 0 ? return_storage.data() : nullptr, &exception)) {
            return rust::String("method has no invokable representation");
        }
        if (exception.threw) {
            return to_rust_string(exception.message);
        }
        if (return_size != 0) {
            std::memcpy(out_return.data(), return_storage.data(), return_size);
        }
        return rust::String{};
    }

    // ---------------------------------------------------------------------------------------
    // Runtime overlay: name/attribute overrides by handle
    // ---------------------------------------------------------------------------------------

    namespace {

        /// Resolves `(target, type_name, member)` to the matching handle and calls `visit` with it;
        /// returns `fallback` when nothing resolves.
        template <class Result, class Visit>
        Result with_overlay_handle(OverlayTarget target, rust::Str type_name, rust::Str member, Result fallback, Visit &&visit) {
            const R::TypeInfo *type = find_type(type_name);
            if (type == nullptr) {
                return fallback;
            }
            auto &registry = R::TypeRegistry::instance();
            const R::TypeHandle type_handle = registry.handle_for(type->key);
            switch (target) {
            case OverlayTarget::Type: return visit(type_handle);
            case OverlayTarget::Field: {
                const R::FieldInfo *field = find_field(*type, member);
                if (field == nullptr) {
                    return fallback;
                }
                return visit(registry.field_handle(type_handle, field->key));
            }
            case OverlayTarget::Method: {
                const R::MethodInfo *method = find_method_by_name(*type, member);
                if (method == nullptr) {
                    return fallback;
                }
                return visit(registry.method_handle(type_handle, method->key));
            }
            default: return fallback;
            }
        }

    } // namespace

    bool reflection_overlay_set_name(OverlayTarget target, rust::Str type_name, rust::Str member, rust::Str name) {
        const UString value{std::string_view{name.data(), name.size()}};
        auto &registry = R::TypeRegistry::instance();
        return with_overlay_handle(target, type_name, member, false, [&](auto handle) {
            using H = decltype(handle);
            if constexpr (std::is_same_v<H, R::TypeHandle>) {
                return registry.set_type_name_override(handle, value);
            } else if constexpr (std::is_same_v<H, R::FieldHandle>) {
                return registry.set_field_name_override(handle, value);
            } else {
                return registry.set_method_name_override(handle, value);
            }
        });
    }

    bool reflection_overlay_clear_name(OverlayTarget target, rust::Str type_name, rust::Str member) {
        auto &registry = R::TypeRegistry::instance();
        return with_overlay_handle(target, type_name, member, false, [&](auto handle) {
            using H = decltype(handle);
            if constexpr (std::is_same_v<H, R::TypeHandle>) {
                return registry.clear_type_name_override(handle);
            } else if constexpr (std::is_same_v<H, R::FieldHandle>) {
                return registry.clear_field_name_override(handle);
            } else {
                return registry.clear_method_name_override(handle);
            }
        });
    }

    bool reflection_overlay_add_attribute(OverlayTarget target, rust::Str type_name, rust::Str member,
                                          const AttributeSummary &attribute) {
        auto &registry = R::TypeRegistry::instance();
        return with_overlay_handle(target, type_name, member, false, [&](auto handle) {
            using H = decltype(handle);
            if constexpr (std::is_same_v<H, R::TypeHandle>) {
                return registry.add_type_attribute_override(handle, to_attribute(attribute));
            } else if constexpr (std::is_same_v<H, R::FieldHandle>) {
                return registry.add_field_attribute_override(handle, to_attribute(attribute));
            } else {
                return registry.add_method_attribute_override(handle, to_attribute(attribute));
            }
        });
    }

    bool reflection_overlay_clear(OverlayTarget target, rust::Str type_name, rust::Str member) {
        auto &registry = R::TypeRegistry::instance();
        return with_overlay_handle(target, type_name, member, false, [&](auto handle) {
            using H = decltype(handle);
            if constexpr (std::is_same_v<H, R::TypeHandle>) {
                return registry.clear_type_overlay(handle);
            } else if constexpr (std::is_same_v<H, R::FieldHandle>) {
                return registry.clear_field_overlay(handle);
            } else {
                return registry.clear_method_overlay(handle);
            }
        });
    }

    bool reflection_overlay_effective_name(OverlayTarget target, rust::Str type_name, rust::Str member, rust::String &out) {
        auto &registry = R::TypeRegistry::instance();
        return with_overlay_handle(target, type_name, member, false, [&](auto handle) {
            using H = decltype(handle);
            UString name;
            if constexpr (std::is_same_v<H, R::TypeHandle>) {
                name = registry.effective_type_name(handle);
            } else if constexpr (std::is_same_v<H, R::FieldHandle>) {
                name = registry.effective_field_name(handle);
            } else {
                name = registry.effective_method_name(handle);
            }
            out = to_rust_string(name);
            return true;
        });
    }

    rust::Vec<AttributeSummary> reflection_overlay_effective_attributes(OverlayTarget target, rust::Str type_name, rust::Str member) {
        auto &registry = R::TypeRegistry::instance();
        return with_overlay_handle(target, type_name, member, rust::Vec<AttributeSummary>{}, [&](auto handle) {
            using H = decltype(handle);
            std::vector<R::Attribute> attributes;
            if constexpr (std::is_same_v<H, R::TypeHandle>) {
                attributes = registry.effective_type_attributes(handle);
            } else if constexpr (std::is_same_v<H, R::FieldHandle>) {
                attributes = registry.effective_field_attributes(handle);
            } else {
                attributes = registry.effective_method_attributes(handle);
            }
            rust::Vec<AttributeSummary> out;
            out.reserve(attributes.size());
            for (const R::Attribute &attribute : attributes) {
                out.push_back(to_attribute_summary(attribute));
            }
            return out;
        });
    }

} // namespace sturdy_rs::reflection
