#include "sturdy_rs/render.hpp"

#include <cstdint>
#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>

#include <Engine/Engine.hpp>
#include <RHI/Error.hpp>
#include <RHI/HdrDisplay.hpp>
#include <RHI/Swapchain.hpp>
#include <WindowManager/Providers/SDL3/SDL3.hpp>

// Generated by build.rs from src/render.rs; defines the shared structs/enums declared there.
#include "sturdy_rs/render_bridge.h"

namespace sturdy_rs::render {
    namespace {

        namespace E = SFT::Engine;
        namespace W = SFT::WindowManager;
        namespace C = SFT::Core;
        namespace R = SFT::RHI;

        UString to_ustring(const rust::String &text) {
            const std::string_view view{text.data(), text.size()};
            if (auto converted = UString::try_from_utf8(view)) {
                return std::move(*converted);
            }
            return UString{};
        }

        rust::String to_rust_string(const UString &text) {
            return rust::String::lossy(text.data(), text.size());
        }

        rust::String to_rust_string(const std::string &text) {
            return rust::String::lossy(text);
        }

        // Additional windows opened through `window_open`/`window_recreate` are owned here (mirroring
        // `Application::windows_`'s ownership of every window it spawns) since `Engine::add_window`
        // only borrows the `WindowManager::Window` it is given; something has to keep it alive for as
        // long as the surface it backs is registered.
        std::unordered_map<std::uint64_t, std::unique_ptr<W::Window>> g_windows;

        C::RenderSurfaceHandle to_surface(SurfaceHandle handle) noexcept {
            return C::RenderSurfaceHandle{static_cast<W::WindowId>(handle.window_id)};
        }

        W::WindowMode map(WindowMode v) noexcept {
            switch (v) {
            case WindowMode::Windowed: return W::WindowMode::Windowed;
            case WindowMode::BorderlessFullscreen: return W::WindowMode::BorderlessFullscreen;
            case WindowMode::ExclusiveFullscreen: return W::WindowMode::ExclusiveFullscreen;
            }
            return W::WindowMode::Windowed;
        }

        W::WindowId window_id_of(SurfaceHandle surface) noexcept {
            return static_cast<W::WindowId>(surface.window_id);
        }

        W::CursorIcon map(CursorIcon v) noexcept {
            switch (v) {
            case CursorIcon::Default: return W::CursorIcon::Default;
            case CursorIcon::Pointer: return W::CursorIcon::Pointer;
            case CursorIcon::Text: return W::CursorIcon::Text;
            case CursorIcon::Grab: return W::CursorIcon::Grab;
            case CursorIcon::Grabbing: return W::CursorIcon::Grabbing;
            case CursorIcon::ResizeHorizontal: return W::CursorIcon::ResizeHorizontal;
            case CursorIcon::ResizeVertical: return W::CursorIcon::ResizeVertical;
            case CursorIcon::ResizeNwse: return W::CursorIcon::ResizeNwse;
            case CursorIcon::ResizeNesw: return W::CursorIcon::ResizeNesw;
            case CursorIcon::NotAllowed: return W::CursorIcon::NotAllowed;
            }
            return W::CursorIcon::Default;
        }

        W::WindowEffectKind map(WindowEffectKind v) noexcept {
            switch (v) {
            case WindowEffectKind::Blur: return W::WindowEffectKind::Blur;
            case WindowEffectKind::Acrylic: return W::WindowEffectKind::Acrylic;
            case WindowEffectKind::Mica: return W::WindowEffectKind::Mica;
            case WindowEffectKind::MicaAlt: return W::WindowEffectKind::MicaAlt;
            case WindowEffectKind::Tabbed: return W::WindowEffectKind::Tabbed;
            case WindowEffectKind::DarkMode: return W::WindowEffectKind::DarkMode;
            case WindowEffectKind::BorderColor: return W::WindowEffectKind::BorderColor;
            case WindowEffectKind::CaptionColor: return W::WindowEffectKind::CaptionColor;
            case WindowEffectKind::TextColor: return W::WindowEffectKind::TextColor;
            case WindowEffectKind::Transparent: return W::WindowEffectKind::Transparent;
            }
            return W::WindowEffectKind::Blur;
        }

        W::TextInputArea map(TextInputArea v) noexcept {
            W::TextInputArea area{};
            area.x = v.x;
            area.y = v.y;
            area.width = v.width;
            area.height = v.height;
            area.cursor_offset_x = v.cursor_offset_x;
            return area;
        }

        C::VSyncMode map(VSync v) noexcept {
            switch (v) {
            case VSync::Off: return C::VSyncMode::Off;
            case VSync::On: return C::VSyncMode::On;
            case VSync::Adaptive: return C::VSyncMode::Adaptive;
            }
            return C::VSyncMode::On;
        }

        C::VariableRefreshMode map(VariableRefresh v) noexcept {
            switch (v) {
            case VariableRefresh::Disabled: return C::VariableRefreshMode::Disabled;
            case VariableRefresh::Automatic: return C::VariableRefreshMode::Automatic;
            case VariableRefresh::Preferred: return C::VariableRefreshMode::Preferred;
            }
            return C::VariableRefreshMode::Automatic;
        }

        C::LatencyMode map(LatencyMode v) noexcept {
            switch (v) {
            case LatencyMode::Normal: return C::LatencyMode::Normal;
            case LatencyMode::Low: return C::LatencyMode::Low;
            case LatencyMode::Ultra: return C::LatencyMode::Ultra;
            }
            return C::LatencyMode::Normal;
        }

        C::PresentationPreference map(PresentationPreference v) noexcept {
            switch (v) {
            case PresentationPreference::Automatic: return C::PresentationPreference::Automatic;
            case PresentationPreference::LowestLatency: return C::PresentationPreference::LowestLatency;
            case PresentationPreference::Smoothest: return C::PresentationPreference::Smoothest;
            case PresentationPreference::PowerEfficient: return C::PresentationPreference::PowerEfficient;
            }
            return C::PresentationPreference::Automatic;
        }

        C::HdrColorSpaceMode map(HdrColorSpaceMode v) noexcept {
            switch (v) {
            case HdrColorSpaceMode::Hdr10St2084: return C::HdrColorSpaceMode::Hdr10St2084;
            case HdrColorSpaceMode::ScrgbLinear: return C::HdrColorSpaceMode::ScrgbLinear;
            case HdrColorSpaceMode::Hdr10Hlg: return C::HdrColorSpaceMode::Hdr10Hlg;
            case HdrColorSpaceMode::DolbyVision: return C::HdrColorSpaceMode::DolbyVision;
            }
            return C::HdrColorSpaceMode::Hdr10St2084;
        }

        HdrColorSpaceMode map(C::HdrColorSpaceMode v) noexcept {
            switch (v) {
            case C::HdrColorSpaceMode::Hdr10St2084: return HdrColorSpaceMode::Hdr10St2084;
            case C::HdrColorSpaceMode::ScrgbLinear: return HdrColorSpaceMode::ScrgbLinear;
            case C::HdrColorSpaceMode::Hdr10Hlg: return HdrColorSpaceMode::Hdr10Hlg;
            case C::HdrColorSpaceMode::DolbyVision: return HdrColorSpaceMode::DolbyVision;
            }
            return HdrColorSpaceMode::Hdr10St2084;
        }

        HdrTransferFunction map(R::HdrTransferFunction v) noexcept {
            switch (v) {
            case R::HdrTransferFunction::Unknown: return HdrTransferFunction::Unknown;
            case R::HdrTransferFunction::Sdr: return HdrTransferFunction::Sdr;
            case R::HdrTransferFunction::PqSt2084: return HdrTransferFunction::PqSt2084;
            case R::HdrTransferFunction::Hlg: return HdrTransferFunction::Hlg;
            case R::HdrTransferFunction::LinearExtended: return HdrTransferFunction::LinearExtended;
            }
            return HdrTransferFunction::Unknown;
        }

        HdrColorGamut map(R::HdrColorGamut v) noexcept {
            switch (v) {
            case R::HdrColorGamut::Unknown: return HdrColorGamut::Unknown;
            case R::HdrColorGamut::Rec709: return HdrColorGamut::Rec709;
            case R::HdrColorGamut::DisplayP3: return HdrColorGamut::DisplayP3;
            case R::HdrColorGamut::Rec2020: return HdrColorGamut::Rec2020;
            }
            return HdrColorGamut::Unknown;
        }

        E::AmbientOcclusionQuality map(AmbientOcclusionQuality v) noexcept {
            switch (v) {
            case AmbientOcclusionQuality::Low: return E::AmbientOcclusionQuality::Low;
            case AmbientOcclusionQuality::Medium: return E::AmbientOcclusionQuality::Medium;
            case AmbientOcclusionQuality::High: return E::AmbientOcclusionQuality::High;
            case AmbientOcclusionQuality::Ultra: return E::AmbientOcclusionQuality::Ultra;
            }
            return E::AmbientOcclusionQuality::High;
        }

        E::PostProcessAntiAliasing map(PostProcessAntiAliasing v) noexcept {
            switch (v) {
            case PostProcessAntiAliasing::None: return E::PostProcessAntiAliasing::None;
            case PostProcessAntiAliasing::Fxaa: return E::PostProcessAntiAliasing::Fxaa;
            case PostProcessAntiAliasing::ConservativeMorphological: return E::PostProcessAntiAliasing::ConservativeMorphological;
            }
            return E::PostProcessAntiAliasing::Fxaa;
        }

        E::ToneMappingOperator map(ToneMappingOperator v) noexcept {
            switch (v) {
            case ToneMappingOperator::None: return E::ToneMappingOperator::None;
            case ToneMappingOperator::Reinhard: return E::ToneMappingOperator::Reinhard;
            case ToneMappingOperator::Exponential: return E::ToneMappingOperator::Exponential;
            case ToneMappingOperator::Agx: return E::ToneMappingOperator::Agx;
            case ToneMappingOperator::HermiteSpline: return E::ToneMappingOperator::HermiteSpline;
            case ToneMappingOperator::PsychoV: return E::ToneMappingOperator::PsychoV;
            }
            return E::ToneMappingOperator::Agx;
        }

        E::AgxLook map(AgxLook v) noexcept {
            switch (v) {
            case AgxLook::None: return E::AgxLook::None;
            case AgxLook::Punchy: return E::AgxLook::Punchy;
            case AgxLook::Golden: return E::AgxLook::Golden;
            }
            return E::AgxLook::None;
        }

        E::RestirGiQuality map(RestirGiQuality v) noexcept {
            switch (v) {
            case RestirGiQuality::Low: return E::RestirGiQuality::Low;
            case RestirGiQuality::Medium: return E::RestirGiQuality::Medium;
            case RestirGiQuality::High: return E::RestirGiQuality::High;
            }
            return E::RestirGiQuality::Medium;
        }

        E::RestirGiDenoiser map(RestirGiDenoiser v) noexcept {
            switch (v) {
            case RestirGiDenoiser::None: return E::RestirGiDenoiser::None;
            case RestirGiDenoiser::Svgf: return E::RestirGiDenoiser::Svgf;
            case RestirGiDenoiser::DlssRayReconstruction: return E::RestirGiDenoiser::DlssRayReconstruction;
            case RestirGiDenoiser::FsrRedstone: return E::RestirGiDenoiser::FsrRedstone;
            }
            return E::RestirGiDenoiser::Svgf;
        }

        // `ShadowDebugView` mirrors the engine's enumeration numerically (both start at 0 and are
        // declared in the same order) rather than through a 26-way switch; the static_assert below
        // catches the engine's header drifting out of sync with the Rust mirror in src/render.rs.
        static_assert(static_cast<int>(E::ShadowDebugView::ScreenSpaceAmbientOcclusion) == 25);

        E::ShadowDebugView map(ShadowDebugView v) noexcept {
            const auto raw = static_cast<std::uint32_t>(v);
            const auto clamped = raw > 25 ? 0u : raw;
            return static_cast<E::ShadowDebugView>(clamped);
        }

        E::ShadowSettings to_engine(const ShadowSettings &s) noexcept {
            E::ShadowSettings out{};
            out.enabled = s.enabled;
            out.atlas_size = s.atlas_size;
            out.cascade_count = s.cascade_count;
            out.max_distance = s.max_distance;
            out.cascade_split_lambda = s.cascade_split_lambda;
            out.cascade_blend = s.cascade_blend;
            out.depth_bias = s.depth_bias;
            out.slope_bias = s.slope_bias;
            for (std::size_t i = 0; i < out.cascade_resolutions.size(); ++i) {
                out.cascade_resolutions[i] = s.cascade_resolutions[i];
            }
            out.filter_radius_texels = s.filter_radius_texels;
            out.normal_bias = s.normal_bias;
            out.debug_view = map(s.debug_view);
            out.max_shadowed_spot_lights = s.max_shadowed_spot_lights;
            out.max_shadowed_point_lights = s.max_shadowed_point_lights;
            out.contact_hardening = s.contact_hardening;
            out.contact_shadows = s.contact_shadows;
            out.contact_shadow_distance = s.contact_shadow_distance;
            out.contact_shadow_thickness = s.contact_shadow_thickness;
            out.contact_shadow_steps = s.contact_shadow_steps;
            out.contact_shadow_intensity = s.contact_shadow_intensity;
            out.contact_shadow_fade_distance = s.contact_shadow_fade_distance;
            return out;
        }

        E::AmbientOcclusionSettings to_engine(const AmbientOcclusionSettings &s) noexcept {
            E::AmbientOcclusionSettings out{};
            out.enabled = s.enabled;
            out.radius = s.radius;
            out.quality = map(s.quality);
            out.intensity = s.intensity;
            out.falloff_range = s.falloff_range;
            out.thin_occluder_compensation = s.thin_occluder_compensation;
            out.final_value_power = s.final_value_power;
            out.sample_distribution_power = s.sample_distribution_power;
            out.denoise = s.denoise;
            return out;
        }

        E::AntiAliasingSettings to_engine(const AntiAliasingSettings &s) noexcept {
            E::AntiAliasingSettings out{};
            out.msaa_samples = s.msaa_samples;
            out.post_process = map(s.post_process);
            out.subpixel_quality = s.subpixel_quality;
            out.edge_threshold = s.edge_threshold;
            return out;
        }

        E::BloomSettings to_engine(const BloomSettings &s) noexcept {
            E::BloomSettings out{};
            out.enabled = s.enabled;
            out.threshold = s.threshold;
            out.soft_knee = s.soft_knee;
            out.intensity = s.intensity;
            out.scatter = s.scatter;
            out.downsample_ratio = s.downsample_ratio;
            out.max_levels = s.max_levels;
            return out;
        }

        E::ToneMappingSettings to_engine(const ToneMappingSettings &s) noexcept {
            E::ToneMappingSettings out{};
            out.enabled = s.enabled;
            out.operation = map(s.operation);
            out.exposure = s.exposure;
            out.white_point = s.white_point;
            out.saturation = s.saturation;
            out.hdr_paper_white_nits = s.hdr_paper_white_nits;
            out.hdr_peak_nits = s.hdr_peak_nits;
            out.agx.look = map(s.agx_look);
            out.hermite_spline.toe_strength = s.hermite_toe_strength;
            out.hermite_spline.toe_length = s.hermite_toe_length;
            out.hermite_spline.shoulder_strength = s.hermite_shoulder_strength;
            out.hermite_spline.shoulder_length = s.hermite_shoulder_length;
            out.hermite_spline.shoulder_angle = s.hermite_shoulder_angle;
            out.psycho_v.highlights = s.psychov_highlights;
            out.psycho_v.shadows = s.psychov_shadows;
            out.psycho_v.contrast = s.psychov_contrast;
            out.psycho_v.purity_scale = s.psychov_purity_scale;
            out.psycho_v.gamut_compression = s.psychov_gamut_compression;
            out.psycho_v.gamut_compression_use_bt2020 = s.psychov_gamut_compression_use_bt2020;
            out.psycho_v.compression = s.psychov_compression;
            out.psycho_v.adapted_gray_bt709 = glm::vec3{
                s.psychov_adapted_gray_bt709[0], s.psychov_adapted_gray_bt709[1], s.psychov_adapted_gray_bt709[2]};
            out.psycho_v.background_gray_bt709 = glm::vec3{
                s.psychov_background_gray_bt709[0], s.psychov_background_gray_bt709[1], s.psychov_background_gray_bt709[2]};
            return out;
        }

        E::RestirGiSettings to_engine(const RestirGiSettings &s) noexcept {
            E::RestirGiSettings out{};
            out.enabled = s.enabled;
            out.quality = map(s.quality);
            out.spatial_reuse_samples = s.spatial_reuse_samples;
            out.spatial_reuse_radius_px = s.spatial_reuse_radius_px;
            out.temporal_history_max = s.temporal_history_max;
            out.max_ray_distance = s.max_ray_distance;
            out.multi_bounce_feedback = s.multi_bounce_feedback;
            out.intensity = s.intensity;
            out.denoiser = map(s.denoiser);
            out.svgf_atrous_iterations = s.svgf_atrous_iterations;
            out.svgf_temporal_alpha = s.svgf_temporal_alpha;
            out.svgf_phi_normal = s.svgf_phi_normal;
            out.svgf_phi_depth = s.svgf_phi_depth;
            out.svgf_phi_luminance = s.svgf_phi_luminance;
            out.show_debug_reservoirs = s.show_debug_reservoirs;
            return out;
        }

        E::MotionBlurSettings to_engine(const MotionBlurSettings &s) noexcept {
            E::MotionBlurSettings out{};
            out.enabled = s.enabled;
            out.intensity = s.intensity;
            out.shutter_angle_degrees = s.shutter_angle_degrees;
            out.tile_size_px = s.tile_size_px;
            out.sample_count = s.sample_count;
            out.max_blur_radius_px = s.max_blur_radius_px;
            out.background_foreground_weight_bias = s.background_foreground_weight_bias;
            out.camera_motion_only = s.camera_motion_only;
            return out;
        }

        E::SceneIntegrator to_engine(SceneIntegrator v) noexcept {
            switch (v) {
            case SceneIntegrator::RasterDeferred: return E::SceneIntegrator::RasterDeferred;
            case SceneIntegrator::ShadowOnly: return E::SceneIntegrator::ShadowOnly;
            case SceneIntegrator::ReflectionOnly: return E::SceneIntegrator::ReflectionOnly;
            case SceneIntegrator::AmbientOcclusionOnly: return E::SceneIntegrator::AmbientOcclusionOnly;
            case SceneIntegrator::ShadowAndTransmission: return E::SceneIntegrator::ShadowAndTransmission;
            case SceneIntegrator::FullPathTracing: return E::SceneIntegrator::FullPathTracing;
            }
            return E::SceneIntegrator::RasterDeferred;
        }

        E::SceneRenderSettings to_engine(const SceneRenderSettings &s) noexcept {
            E::SceneRenderSettings out{};
            out.enabled = s.enabled;
            out.integrator = to_engine(s.integrator);
            out.path_samples_per_pixel = s.path_samples_per_pixel;
            out.path_max_bounces = s.path_max_bounces;
            out.path_russian_roulette_start_bounce = s.path_russian_roulette_start_bounce;
            out.caustic_photon_count = s.caustic_photon_count;
            out.caustic_gather_radius = s.caustic_gather_radius;
            out.wavelength_min_nm = s.wavelength_min_nm;
            out.wavelength_max_nm = s.wavelength_max_nm;
            if (s.has_background_color) {
                out.background_color = glm::vec4{s.background_color[0], s.background_color[1],
                                                  s.background_color[2], s.background_color[3]};
            }
            out.background_intensity = s.background_intensity;
            return out;
        }

        E::DebugOverlayRenderSettings to_engine(const DebugOverlayRenderSettings &s) noexcept {
            E::DebugOverlayRenderSettings out{};
            out.enabled = s.enabled;
            out.draw_text = s.draw_text;
            return out;
        }

        E::RenderGraphDescription to_engine(const RenderGraphSettings &s) noexcept {
            E::RenderGraphDescription out{};
            out.scene = to_engine(s.scene);
            out.debug_overlay = to_engine(s.debug_overlay);
            out.shadows = to_engine(s.shadows);
            out.ambient_occlusion = to_engine(s.ambient_occlusion);
            out.anti_aliasing = to_engine(s.anti_aliasing);
            out.bloom = to_engine(s.bloom);
            out.tone_mapping = to_engine(s.tone_mapping);
            out.restir_gi = to_engine(s.restir_gi);
            out.motion_blur = to_engine(s.motion_blur);
            out.execution_mode = s.execution_mode == RenderGraphExecutionMode::WaitForCompletion
                                      ? E::RenderGraphExecutionMode::WaitForCompletion
                                      : E::RenderGraphExecutionMode::FireAndForget;
            out.resolution_scale = s.resolution_scale;
            return out;
        }

    } // namespace

    SFT::Engine::RenderGraph render_graph_from_settings(const RenderGraphSettings &settings) noexcept {
        // `to_engine` is declared inside the anonymous namespace just above; still reachable
        // unqualified here since anonymous-namespace members are visible for the rest of the file.
        return SFT::Engine::RenderGraph{to_engine(settings)};
    }

    namespace {
        std::mutex g_pending_render_graph_mutex;
        std::optional<SFT::Engine::RenderGraph> g_pending_render_graph;
    } // namespace

    void set_pending_render_graph(const RenderGraphSettings &settings) {
        const std::lock_guard<std::mutex> lock{g_pending_render_graph_mutex};
        g_pending_render_graph = render_graph_from_settings(settings);
    }

    SFT::Engine::RenderGraph consume_pending_render_graph() noexcept {
        const std::lock_guard<std::mutex> lock{g_pending_render_graph_mutex};
        return g_pending_render_graph.value_or(SFT::Engine::RenderGraph::empty());
    }

    namespace {

        W::WindowConfig build_window_config(const WindowDesc &desc, const std::string &title) noexcept {
            W::WindowConfig config{};
            config.title = title.c_str();
            config.extent = {desc.width, desc.height};
            config.position = {desc.x, desc.y};
            config.use_default_position = desc.use_default_position;
            config.visible = desc.visible;
            config.resizable = desc.resizable;
            config.decorated = desc.decorated;
            config.high_dpi = desc.high_dpi;
            config.transparent = desc.transparent;
            config.mode = map(desc.window_mode);
            config.graphics_api = W::WindowGraphicsApi::Vulkan;
            return config;
        }

        WindowOpenResult open_window_impl(EngineView &engine, const WindowDesc &desc) {
            const std::string title{desc.title};
            const W::WindowConfig config = build_window_config(desc, title);

            auto created = W::Window::create<W::SDL3::SDL3Window>(config);
            if (!created) {
                return WindowOpenResult{false, to_rust_string(created.error().message), SurfaceHandle{UINT64_MAX}};
            }
            std::unique_ptr<W::Window> window = std::move(*created);
            const auto window_id = static_cast<std::uint64_t>(window->id());

            auto added = engine.add_window(*window, desc.desired_frames_in_flight);
            if (!added) {
                return WindowOpenResult{false, to_rust_string(added.error().message), SurfaceHandle{UINT64_MAX}};
            }

            g_windows.emplace(window_id, std::move(window));
            return WindowOpenResult{true, rust::String(), SurfaceHandle{window_id}};
        }

    } // namespace

    WindowOpenResult window_open(EngineView &engine, const WindowDesc &desc) {
        return open_window_impl(engine, desc);
    }

    WindowOpenResult window_recreate(EngineView &engine, SurfaceHandle old_surface, const WindowDesc &desc) {
        const std::string title{desc.title};
        const W::WindowConfig config = build_window_config(desc, title);

        const auto old_it = g_windows.find(old_surface.window_id);
        if (old_it == g_windows.end()) {
            return WindowOpenResult{false, rust::String("unknown surface"), SurfaceHandle{UINT64_MAX}};
        }

        auto created = W::Window::create<W::SDL3::SDL3Window>(config);
        if (!created) {
            return WindowOpenResult{false, to_rust_string(created.error().message), SurfaceHandle{UINT64_MAX}};
        }
        std::unique_ptr<W::Window> window = std::move(*created);
        const auto new_window_id = static_cast<std::uint64_t>(window->id());

        auto recreated = engine.recreate_window(to_surface(old_surface), *window, desc.desired_frames_in_flight);
        if (!recreated) {
            return WindowOpenResult{false, to_rust_string(recreated.error().message), SurfaceHandle{UINT64_MAX}};
        }

        g_windows.erase(old_it);
        g_windows.emplace(new_window_id, std::move(window));
        return WindowOpenResult{true, rust::String(), SurfaceHandle{new_window_id}};
    }

    void window_close(EngineView &engine, SurfaceHandle surface) noexcept {
        engine.remove_window(to_surface(surface));
        g_windows.erase(surface.window_id);
    }

    void window_notify_resize(EngineView &engine, SurfaceHandle surface, std::uint32_t width, std::uint32_t height) noexcept {
        engine.on_surface_resize_needed(to_surface(surface), C::Extent2D{width, height});
    }

    void window_set_cursor_icon(EngineView &engine, SurfaceHandle surface, CursorIcon icon) noexcept {
        engine.window_requests().set_cursor_icon(window_id_of(surface), map(icon));
    }

    void window_set_cursor_grabbed(EngineView &engine, SurfaceHandle surface, bool grabbed) noexcept {
        engine.window_requests().set_cursor_grabbed(window_id_of(surface), grabbed);
    }

    void window_set_mode(EngineView &engine, SurfaceHandle surface, ::sturdy_rs::WindowMode mode) noexcept {
        engine.window_requests().set_fullscreen(window_id_of(surface), map(mode));
    }

    void window_set_decorated(EngineView &engine, SurfaceHandle surface, bool decorated) noexcept {
        engine.window_requests().set_decorated(window_id_of(surface), decorated);
    }

    void window_set_transparent(EngineView &engine, SurfaceHandle surface, bool transparent) noexcept {
        engine.window_requests().set_transparent(window_id_of(surface), transparent);
    }

    void window_set_relative_mouse_mode(EngineView &engine, SurfaceHandle surface, bool enabled) noexcept {
        engine.window_requests().set_relative_mouse_mode(window_id_of(surface), enabled);
    }

    void window_set_mouse_locked(EngineView &engine, SurfaceHandle surface, bool locked) noexcept {
        engine.window_requests().set_mouse_locked(window_id_of(surface), locked);
    }

    void window_set_text_input_active(EngineView &engine, SurfaceHandle surface, bool active) noexcept {
        engine.window_requests().set_text_input_active(window_id_of(surface), active);
    }

    void window_set_text_input_area(EngineView &engine, SurfaceHandle surface, TextInputArea area) noexcept {
        engine.window_requests().set_text_input_area(window_id_of(surface), map(area));
    }

    void window_set_effect(EngineView &engine, SurfaceHandle surface, WindowEffectKind kind, bool enabled) noexcept {
        engine.window_requests().set_blur(window_id_of(surface), map(kind), enabled);
    }

    OffscreenTargetCreateResult offscreen_target_create(EngineView &engine, const OffscreenTargetDesc &desc) {
        E::OffscreenRenderTargetDescription description{};
        description.width = desc.width;
        description.height = desc.height;
        description.label = to_ustring(desc.label);

        auto created = engine.create_offscreen_render_target(description);
        if (!created) {
            return OffscreenTargetCreateResult{false, to_rust_string(created.error().message), 0};
        }
        return OffscreenTargetCreateResult{true, rust::String(), created->value};
    }

    void offscreen_target_destroy(EngineView &engine, std::uint64_t handle) noexcept {
        engine.destroy_offscreen_render_target(E::RenderTargetHandle{handle});
    }

    bool offscreen_target_description(const EngineView &engine, std::uint64_t handle, OffscreenTargetDesc &out) {
        const auto description = engine.offscreen_render_target_description(E::RenderTargetHandle{handle});
        if (!description) {
            return false;
        }
        out.width = description->width;
        out.height = description->height;
        out.label = to_rust_string(description->label);
        return true;
    }

    std::uint64_t offscreen_target_texture(const EngineView &engine, std::uint64_t handle) noexcept {
        return engine.offscreen_render_target_texture(E::RenderTargetHandle{handle}).value;
    }

    PresentationSettings presentation_settings_get(const EngineView &engine, SurfaceHandle surface) noexcept {
        const C::PresentationSettings settings = engine.presentation_settings(to_surface(surface));
        PresentationSettings out{};
        out.vsync = [&] {
            switch (settings.vsync) {
            case C::VSyncMode::Off: return VSync::Off;
            case C::VSyncMode::On: return VSync::On;
            case C::VSyncMode::Adaptive: return VSync::Adaptive;
            }
            return VSync::On;
        }();
        out.variable_refresh = [&] {
            switch (settings.variable_refresh) {
            case C::VariableRefreshMode::Disabled: return VariableRefresh::Disabled;
            case C::VariableRefreshMode::Automatic: return VariableRefresh::Automatic;
            case C::VariableRefreshMode::Preferred: return VariableRefresh::Preferred;
            }
            return VariableRefresh::Automatic;
        }();
        out.latency = [&] {
            switch (settings.latency) {
            case C::LatencyMode::Normal: return LatencyMode::Normal;
            case C::LatencyMode::Low: return LatencyMode::Low;
            case C::LatencyMode::Ultra: return LatencyMode::Ultra;
            }
            return LatencyMode::Normal;
        }();
        out.preference = [&] {
            switch (settings.preference) {
            case C::PresentationPreference::Automatic: return PresentationPreference::Automatic;
            case C::PresentationPreference::LowestLatency: return PresentationPreference::LowestLatency;
            case C::PresentationPreference::Smoothest: return PresentationPreference::Smoothest;
            case C::PresentationPreference::PowerEfficient: return PresentationPreference::PowerEfficient;
            }
            return PresentationPreference::Automatic;
        }();
        out.hdr_enabled = static_cast<bool>(settings.hdr_enabled);
        out.hdr_color_space = map(settings.hdr_color_space);
        out.transparent_composition = static_cast<bool>(settings.transparent_composition);
        out.swapchain_image_count = settings.swapchain_image_count;
        out.allow_present_from_compute = static_cast<bool>(settings.allow_present_from_compute);
        return out;
    }

    Status presentation_settings_set(EngineView &engine, SurfaceHandle surface, const PresentationSettings &settings) {
        C::PresentationSettings native{};
        native.vsync = map(settings.vsync);
        native.variable_refresh = map(settings.variable_refresh);
        native.latency = map(settings.latency);
        native.preference = map(settings.preference);
        native.hdr_enabled = settings.hdr_enabled;
        native.hdr_color_space = map(settings.hdr_color_space);
        native.transparent_composition = settings.transparent_composition;
        native.swapchain_image_count = settings.swapchain_image_count;
        native.allow_present_from_compute = settings.allow_present_from_compute;

        const C::RendererResult result = engine.set_presentation_settings(to_surface(surface), native);
        if (!result) {
            return Status{false, to_rust_string(result.error().message)};
        }
        return Status{true, rust::String()};
    }

    PresentationResolution presentation_resolution_query(const EngineView &engine, SurfaceHandle surface) noexcept {
        const R::PresentationResolution resolution = engine.presentation_resolution(to_surface(surface));
        PresentationResolution out{};
        out.strategy = rust::String(std::string{R::present_strategy_name(resolution.strategy)});
        out.effective_mode = rust::String(std::string{R::present_mode_name(resolution.effective_mode)});
        out.degraded = resolution.degraded;
        out.present_queue_is_compute = resolution.present_queue_is_compute;
        out.effective_composite_alpha = rust::String(std::string{R::composite_alpha_mode_name(resolution.effective_composite_alpha)});
        out.composite_alpha_degraded = resolution.composite_alpha_degraded;
        out.via_composition_present = resolution.via_composition_present;
        out.supports_completion_fence = resolution.supports_completion_fence;
        out.full_screen_exclusive_active = resolution.full_screen_exclusive_active;
        out.effective_format = static_cast<std::uint32_t>(resolution.effective_format);
        out.effective_color_space = static_cast<std::uint32_t>(resolution.effective_color_space);
        return out;
    }

    HdrCapabilityQuery hdr_capabilities_query(const EngineView &engine, SurfaceHandle surface) {
        const auto queried = engine.query_hdr_capabilities(to_surface(surface));
        HdrCapabilityQuery out{};
        if (!queried) {
            out.ok = false;
            out.message = to_rust_string(queried.error().message);
            return out;
        }
        const R::SurfaceHdrCapabilityQuery &query = *queried;
        out.ok = static_cast<bool>(query);
        out.message = to_rust_string(query.message.message);
        out.hdr_supported = query.capabilities.hdr_supported;
        out.hdr_enabled_by_os = query.capabilities.hdr_enabled_by_os;
        out.hdr_metadata_output_supported = query.capabilities.hdr_metadata_output_supported;
        for (const R::HdrPresentationMode &mode : query.capabilities.supported_modes) {
            out.supported_modes.push_back(HdrPresentationMode{map(mode.transfer), map(mode.gamut), mode.requires_os_hdr_mode});
        }
        out.has_display_metadata = query.capabilities.display_metadata.has_value();
        if (out.has_display_metadata) {
            const R::HdrDisplayMetadata &metadata = *query.capabilities.display_metadata;
            out.display_metadata.red_primary_x = metadata.red_primary.x;
            out.display_metadata.red_primary_y = metadata.red_primary.y;
            out.display_metadata.green_primary_x = metadata.green_primary.x;
            out.display_metadata.green_primary_y = metadata.green_primary.y;
            out.display_metadata.blue_primary_x = metadata.blue_primary.x;
            out.display_metadata.blue_primary_y = metadata.blue_primary.y;
            out.display_metadata.white_point_x = metadata.white_point.x;
            out.display_metadata.white_point_y = metadata.white_point.y;
            out.display_metadata.min_luminance_nits = metadata.min_luminance_nits;
            out.display_metadata.max_luminance_nits = metadata.max_luminance_nits;
            out.display_metadata.max_full_frame_luminance_nits = metadata.max_full_frame_luminance_nits;
        }
        out.sdr_white_nits = query.capabilities.sdr_white_nits;
        out.edr_headroom = query.capabilities.edr_headroom;
        out.max_edr_headroom = query.capabilities.max_edr_headroom;
        return out;
    }

    Status hdr_update_content_light_level(EngineView &engine, SurfaceHandle surface, const HdrContentLightLevelUpdate &update) {
        R::HdrContentLightLevelUpdate native{};
        native.max_content_light_level_nits = update.max_content_light_level_nits;
        native.max_frame_average_light_level_nits = update.max_frame_average_light_level_nits;

        const R::RhiResult result = engine.update_hdr_content_light_level(to_surface(surface), native);
        if (!result) {
            return Status{false, to_rust_string(result.error().message)};
        }
        return Status{true, rust::String()};
    }

    Status render_graph_settings_validate(const RenderGraphSettings &settings) {
        E::RenderGraph graph(to_engine(settings));
        const E::RenderGraphResult result = graph.validate();
        if (!result) {
            return Status{false, to_rust_string(result.error().message)};
        }
        return Status{true, rust::String()};
    }

} // namespace sturdy_rs::render
