#include "sturdy_rs/rhi.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <span>
#include <string>
#include <utility>
#include <vector>

// Generated by build.rs from src/rhi.rs; defines the shared structs/enums declared in rhi.hpp.
#include "sturdy_rs/rhi_bridge.h"

#include <Engine/EngineModule.hpp>
#include <Renderer/RendererModule.hpp>

namespace sturdy_rs::rhi {
    namespace {

        namespace R = SFT::RHI;

        // ─── Handle conversion (every RHI handle is `{ u64 value; }`) ────────────────
        template <class RhiHandle, class OurHandle>
        RhiHandle to_rhi_handle(OurHandle h) noexcept {
            RhiHandle r{};
            r.value = h.value;
            return r;
        }
        template <class OurHandle, class RhiHandle>
        OurHandle from_rhi_handle(RhiHandle h) noexcept {
            OurHandle o{};
            o.value = h.value;
            return o;
        }

        // ─── Status / error conversion ────────────────────────────────────────────
        RhiErrorCode map_error_code(R::RhiErrorCode code) noexcept {
            switch (code) {
            case R::RhiErrorCode::Unsupported: return RhiErrorCode::Unsupported;
            case R::RhiErrorCode::OperationFailed: return RhiErrorCode::OperationFailed;
            case R::RhiErrorCode::OutOfMemory: return RhiErrorCode::OutOfMemory;
            case R::RhiErrorCode::DeviceLost: return RhiErrorCode::DeviceLost;
            case R::RhiErrorCode::SurfaceLost: return RhiErrorCode::SurfaceLost;
            case R::RhiErrorCode::FullScreenExclusiveLost: return RhiErrorCode::FullScreenExclusiveLost;
            case R::RhiErrorCode::NotReady: return RhiErrorCode::NotReady;
            case R::RhiErrorCode::InvalidArgument: return RhiErrorCode::InvalidArgument;
            }
            return RhiErrorCode::OperationFailed;
        }

        void set_ok(RhiStatus &status) {
            status.ok = true;
            status.code = RhiErrorCode::OperationFailed;
            status.message = rust::String();
        }

        void set_error(RhiStatus &status, const R::RhiError &error) {
            status.ok = false;
            status.code = map_error_code(error.code);
            status.message = rust::String::lossy(error.message);
        }

        template <class OurValue, class RhiValue>
        OurValue unwrap(R::RhiExpected<RhiValue> result, RhiStatus &status, OurValue on_error = OurValue{}) {
            if (!result) {
                set_error(status, result.error());
                return on_error;
            }
            set_ok(status);
            return OurValue{*result};
        }

        template <class OurHandle, class RhiHandle>
        OurHandle unwrap_handle(R::RhiExpected<RhiHandle> result, RhiStatus &status) {
            if (!result) {
                set_error(status, result.error());
                return OurHandle{};
            }
            set_ok(status);
            return from_rhi_handle<OurHandle>(*result);
        }

        void unwrap_void(R::RhiResult result, RhiStatus &status) {
            if (!result) {
                set_error(status, result.error());
                return;
            }
            set_ok(status);
        }

        // ─── Small sequential-enum conversions ───────────────────────────────────────
        R::MemoryLocation map(MemoryLocation v) noexcept {
            switch (v) {
            case MemoryLocation::DeviceLocal: return R::MemoryLocation::DeviceLocal;
            case MemoryLocation::HostUpload: return R::MemoryLocation::HostUpload;
            case MemoryLocation::HostReadback: return R::MemoryLocation::HostReadback;
            }
            return R::MemoryLocation::DeviceLocal;
        }

        R::TextureDimension map(TextureDimension v) noexcept {
            switch (v) {
            case TextureDimension::Dim1D: return R::TextureDimension::Dim1D;
            case TextureDimension::Dim2D: return R::TextureDimension::Dim2D;
            case TextureDimension::Dim3D: return R::TextureDimension::Dim3D;
            }
            return R::TextureDimension::Dim2D;
        }

        R::TextureViewType map(TextureViewType v) noexcept {
            switch (v) {
            case TextureViewType::View1D: return R::TextureViewType::View1D;
            case TextureViewType::View2D: return R::TextureViewType::View2D;
            case TextureViewType::View2DArray: return R::TextureViewType::View2DArray;
            case TextureViewType::ViewCube: return R::TextureViewType::ViewCube;
            case TextureViewType::ViewCubeArray: return R::TextureViewType::ViewCubeArray;
            case TextureViewType::View3D: return R::TextureViewType::View3D;
            }
            return R::TextureViewType::View2D;
        }

        R::Filter map(Filter v) noexcept {
            return v == Filter::Nearest ? R::Filter::Nearest : R::Filter::Linear;
        }

        R::MipmapMode map(MipmapMode v) noexcept {
            return v == MipmapMode::Nearest ? R::MipmapMode::Nearest : R::MipmapMode::Linear;
        }

        R::AddressMode map(AddressMode v) noexcept {
            switch (v) {
            case AddressMode::Repeat: return R::AddressMode::Repeat;
            case AddressMode::MirroredRepeat: return R::AddressMode::MirroredRepeat;
            case AddressMode::ClampToEdge: return R::AddressMode::ClampToEdge;
            case AddressMode::ClampToBorder: return R::AddressMode::ClampToBorder;
            }
            return R::AddressMode::Repeat;
        }

        R::BorderColor map(BorderColor v) noexcept {
            switch (v) {
            case BorderColor::TransparentBlack: return R::BorderColor::TransparentBlack;
            case BorderColor::OpaqueBlack: return R::BorderColor::OpaqueBlack;
            case BorderColor::OpaqueWhite: return R::BorderColor::OpaqueWhite;
            }
            return R::BorderColor::TransparentBlack;
        }

        R::CompareOp map(CompareOp v) noexcept {
            switch (v) {
            case CompareOp::Never: return R::CompareOp::Never;
            case CompareOp::Less: return R::CompareOp::Less;
            case CompareOp::Equal: return R::CompareOp::Equal;
            case CompareOp::LessEqual: return R::CompareOp::LessEqual;
            case CompareOp::Greater: return R::CompareOp::Greater;
            case CompareOp::NotEqual: return R::CompareOp::NotEqual;
            case CompareOp::GreaterEqual: return R::CompareOp::GreaterEqual;
            case CompareOp::Always: return R::CompareOp::Always;
            }
            return R::CompareOp::Always;
        }

        R::StencilOp map(StencilOp v) noexcept {
            switch (v) {
            case StencilOp::Keep: return R::StencilOp::Keep;
            case StencilOp::Zero: return R::StencilOp::Zero;
            case StencilOp::Replace: return R::StencilOp::Replace;
            case StencilOp::IncrementClamp: return R::StencilOp::IncrementClamp;
            case StencilOp::DecrementClamp: return R::StencilOp::DecrementClamp;
            case StencilOp::Invert: return R::StencilOp::Invert;
            case StencilOp::IncrementWrap: return R::StencilOp::IncrementWrap;
            case StencilOp::DecrementWrap: return R::StencilOp::DecrementWrap;
            }
            return R::StencilOp::Keep;
        }

        R::StencilFaceState map(const StencilFaceState &v) noexcept {
            R::StencilFaceState face{};
            face.fail_op = map(v.fail_op);
            face.depth_fail_op = map(v.depth_fail_op);
            face.pass_op = map(v.pass_op);
            face.compare = map(v.compare);
            return face;
        }

        R::AccelerationStructureCopyMode map(AccelerationStructureCopyMode v) noexcept {
            switch (v) {
            case AccelerationStructureCopyMode::Clone: return R::AccelerationStructureCopyMode::Clone;
            case AccelerationStructureCopyMode::Compact: return R::AccelerationStructureCopyMode::Compact;
            case AccelerationStructureCopyMode::Serialize: return R::AccelerationStructureCopyMode::Serialize;
            case AccelerationStructureCopyMode::Deserialize: return R::AccelerationStructureCopyMode::Deserialize;
            }
            return R::AccelerationStructureCopyMode::Clone;
        }

        // Format has ~50 variants copied verbatim (same order) from RHI/Types.hpp, so a direct
        // static_cast is safe; the static_assert below catches the header drifting later.
        static_assert(static_cast<int>(R::Format::BC7UnormSrgb) == 47, "RHI::Format layout drifted from the bridge's Format enum");
        R::Format map(Format v) noexcept {
            return static_cast<R::Format>(static_cast<std::uint8_t>(v));
        }

        R::SampleCount map(SampleCount v) noexcept {
            switch (v) {
            case SampleCount::X1: return R::SampleCount::X1;
            case SampleCount::X2: return R::SampleCount::X2;
            case SampleCount::X4: return R::SampleCount::X4;
            case SampleCount::X8: return R::SampleCount::X8;
            case SampleCount::X16: return R::SampleCount::X16;
            }
            return R::SampleCount::X1;
        }

        R::IndexFormat map(IndexFormat v) noexcept {
            return v == IndexFormat::Uint16 ? R::IndexFormat::Uint16 : R::IndexFormat::Uint32;
        }

        R::ShaderLanguage map(ShaderLanguage v) noexcept {
            switch (v) {
            case ShaderLanguage::SpirV: return R::ShaderLanguage::SpirV;
            case ShaderLanguage::Dxil: return R::ShaderLanguage::Dxil;
            case ShaderLanguage::Msl: return R::ShaderLanguage::Msl;
            case ShaderLanguage::Wgsl: return R::ShaderLanguage::Wgsl;
            }
            return R::ShaderLanguage::SpirV;
        }

        static_assert(static_cast<int>(R::VertexFormat::Float16x4) == 17, "RHI::VertexFormat layout drifted from the bridge's VertexFormat enum");
        R::VertexFormat map(VertexFormat v) noexcept {
            return static_cast<R::VertexFormat>(static_cast<std::uint8_t>(v));
        }

        R::VertexStepMode map(VertexStepMode v) noexcept {
            return v == VertexStepMode::Vertex ? R::VertexStepMode::Vertex : R::VertexStepMode::Instance;
        }

        R::BindingType map(BindingType v) noexcept {
            switch (v) {
            case BindingType::UniformBuffer: return R::BindingType::UniformBuffer;
            case BindingType::StorageBuffer: return R::BindingType::StorageBuffer;
            case BindingType::ReadOnlyStorageBuffer: return R::BindingType::ReadOnlyStorageBuffer;
            case BindingType::SampledTexture: return R::BindingType::SampledTexture;
            case BindingType::StorageTexture: return R::BindingType::StorageTexture;
            case BindingType::Sampler: return R::BindingType::Sampler;
            case BindingType::CombinedImageSampler: return R::BindingType::CombinedImageSampler;
            case BindingType::AccelerationStructure: return R::BindingType::AccelerationStructure;
            case BindingType::InputAttachment: return R::BindingType::InputAttachment;
            }
            return R::BindingType::UniformBuffer;
        }

        R::StorageTextureAccess map(StorageTextureAccess v) noexcept {
            switch (v) {
            case StorageTextureAccess::WriteOnly: return R::StorageTextureAccess::WriteOnly;
            case StorageTextureAccess::ReadOnly: return R::StorageTextureAccess::ReadOnly;
            case StorageTextureAccess::ReadWrite: return R::StorageTextureAccess::ReadWrite;
            }
            return R::StorageTextureAccess::WriteOnly;
        }

        R::BindGroupLifetime map(BindGroupLifetime v) noexcept {
            return v == BindGroupLifetime::Persistent ? R::BindGroupLifetime::Persistent : R::BindGroupLifetime::FrameTransient;
        }

        R::PrimitiveTopology map(PrimitiveTopology v) noexcept {
            switch (v) {
            case PrimitiveTopology::PointList: return R::PrimitiveTopology::PointList;
            case PrimitiveTopology::LineList: return R::PrimitiveTopology::LineList;
            case PrimitiveTopology::LineStrip: return R::PrimitiveTopology::LineStrip;
            case PrimitiveTopology::TriangleList: return R::PrimitiveTopology::TriangleList;
            case PrimitiveTopology::TriangleStrip: return R::PrimitiveTopology::TriangleStrip;
            }
            return R::PrimitiveTopology::TriangleList;
        }

        R::PolygonMode map(PolygonMode v) noexcept {
            switch (v) {
            case PolygonMode::Fill: return R::PolygonMode::Fill;
            case PolygonMode::Line: return R::PolygonMode::Line;
            case PolygonMode::Point: return R::PolygonMode::Point;
            }
            return R::PolygonMode::Fill;
        }

        R::CullMode map(CullMode v) noexcept {
            switch (v) {
            case CullMode::None: return R::CullMode::None;
            case CullMode::Front: return R::CullMode::Front;
            case CullMode::Back: return R::CullMode::Back;
            }
            return R::CullMode::Back;
        }

        R::FrontFace map(FrontFace v) noexcept {
            return v == FrontFace::CounterClockwise ? R::FrontFace::CounterClockwise : R::FrontFace::Clockwise;
        }

        R::BlendFactor map(BlendFactor v) noexcept {
            switch (v) {
            case BlendFactor::Zero: return R::BlendFactor::Zero;
            case BlendFactor::One: return R::BlendFactor::One;
            case BlendFactor::SrcColor: return R::BlendFactor::SrcColor;
            case BlendFactor::OneMinusSrcColor: return R::BlendFactor::OneMinusSrcColor;
            case BlendFactor::DstColor: return R::BlendFactor::DstColor;
            case BlendFactor::OneMinusDstColor: return R::BlendFactor::OneMinusDstColor;
            case BlendFactor::SrcAlpha: return R::BlendFactor::SrcAlpha;
            case BlendFactor::OneMinusSrcAlpha: return R::BlendFactor::OneMinusSrcAlpha;
            case BlendFactor::DstAlpha: return R::BlendFactor::DstAlpha;
            case BlendFactor::OneMinusDstAlpha: return R::BlendFactor::OneMinusDstAlpha;
            case BlendFactor::ConstantColor: return R::BlendFactor::ConstantColor;
            case BlendFactor::OneMinusConstantColor: return R::BlendFactor::OneMinusConstantColor;
            case BlendFactor::SrcAlphaSaturated: return R::BlendFactor::SrcAlphaSaturated;
            }
            return R::BlendFactor::One;
        }

        R::BlendOp map(BlendOp v) noexcept {
            switch (v) {
            case BlendOp::Add: return R::BlendOp::Add;
            case BlendOp::Subtract: return R::BlendOp::Subtract;
            case BlendOp::ReverseSubtract: return R::BlendOp::ReverseSubtract;
            case BlendOp::Min: return R::BlendOp::Min;
            case BlendOp::Max: return R::BlendOp::Max;
            }
            return R::BlendOp::Add;
        }

        R::LoadOp map(LoadOp v) noexcept {
            switch (v) {
            case LoadOp::Load: return R::LoadOp::Load;
            case LoadOp::Clear: return R::LoadOp::Clear;
            case LoadOp::DontCare: return R::LoadOp::DontCare;
            }
            return R::LoadOp::Load;
        }

        R::StoreOp map(StoreOp v) noexcept {
            return v == StoreOp::Store ? R::StoreOp::Store : R::StoreOp::DontCare;
        }

        R::QueueClass map(QueueClass v) noexcept {
            switch (v) {
            case QueueClass::Graphics: return R::QueueClass::Graphics;
            case QueueClass::Compute: return R::QueueClass::Compute;
            case QueueClass::Transfer: return R::QueueClass::Transfer;
            case QueueClass::Sparse: return R::QueueClass::Sparse;
            case QueueClass::VideoDecode: return R::QueueClass::VideoDecode;
            case QueueClass::VideoEncode: return R::QueueClass::VideoEncode;
            }
            return R::QueueClass::Graphics;
        }

        R::QueueLane map(const QueueLane &v) noexcept {
            return R::QueueLane{map(v.queue), v.index};
        }

        R::QueueOwnershipTransfer map(const QueueOwnershipTransfer &v) noexcept {
            R::QueueOwnershipTransfer out{};
            out.src = map(v.src);
            out.dst = map(v.dst);
            out.enabled = v.enabled;
            return out;
        }

        R::ShadingRate map(ShadingRate v) noexcept {
            switch (v) {
            case ShadingRate::X1x1: return R::ShadingRate::X1x1;
            case ShadingRate::X1x2: return R::ShadingRate::X1x2;
            case ShadingRate::X2x1: return R::ShadingRate::X2x1;
            case ShadingRate::X2x2: return R::ShadingRate::X2x2;
            case ShadingRate::X2x4: return R::ShadingRate::X2x4;
            case ShadingRate::X4x2: return R::ShadingRate::X4x2;
            case ShadingRate::X4x4: return R::ShadingRate::X4x4;
            }
            return R::ShadingRate::X1x1;
        }

        R::ShadingRateCombiner map(ShadingRateCombiner v) noexcept {
            switch (v) {
            case ShadingRateCombiner::Passthrough: return R::ShadingRateCombiner::Passthrough;
            case ShadingRateCombiner::Override: return R::ShadingRateCombiner::Override;
            case ShadingRateCombiner::Min: return R::ShadingRateCombiner::Min;
            case ShadingRateCombiner::Max: return R::ShadingRateCombiner::Max;
            case ShadingRateCombiner::Combine: return R::ShadingRateCombiner::Combine;
            }
            return R::ShadingRateCombiner::Passthrough;
        }

        std::vector<R::SampleLocation> to_rhi(rust::Slice<const SampleLocation> locations) {
            std::vector<R::SampleLocation> out;
            out.reserve(locations.size());
            for (const SampleLocation &location : locations) {
                out.push_back(R::SampleLocation{location.x, location.y});
            }
            return out;
        }

        R::TextureLayout map(TextureLayout v) noexcept {
            switch (v) {
            case TextureLayout::Undefined: return R::TextureLayout::Undefined;
            case TextureLayout::General: return R::TextureLayout::General;
            case TextureLayout::ColorAttachment: return R::TextureLayout::ColorAttachment;
            case TextureLayout::DepthStencilAttachment: return R::TextureLayout::DepthStencilAttachment;
            case TextureLayout::DepthStencilReadOnly: return R::TextureLayout::DepthStencilReadOnly;
            case TextureLayout::ShaderReadOnly: return R::TextureLayout::ShaderReadOnly;
            case TextureLayout::TransferSrc: return R::TextureLayout::TransferSrc;
            case TextureLayout::TransferDst: return R::TextureLayout::TransferDst;
            case TextureLayout::Present: return R::TextureLayout::Present;
            }
            return R::TextureLayout::Undefined;
        }

        R::AccelerationStructureType map(AccelerationStructureType v) noexcept {
            return v == AccelerationStructureType::BottomLevel ? R::AccelerationStructureType::BottomLevel
                                                                : R::AccelerationStructureType::TopLevel;
        }

        R::AccelerationStructureGeometryType map(AccelerationStructureGeometryType v) noexcept {
            switch (v) {
            case AccelerationStructureGeometryType::Triangles: return R::AccelerationStructureGeometryType::Triangles;
            case AccelerationStructureGeometryType::Instances: return R::AccelerationStructureGeometryType::Instances;
            case AccelerationStructureGeometryType::Aabbs: return R::AccelerationStructureGeometryType::Aabbs;
            }
            return R::AccelerationStructureGeometryType::Triangles;
        }

        R::OpacityMicromapFormat map(OpacityMicromapFormat v) noexcept {
            return v == OpacityMicromapFormat::FourState ? R::OpacityMicromapFormat::FourState
                                                         : R::OpacityMicromapFormat::TwoState;
        }

        std::vector<R::OpacityMicromapUsageCount> to_rhi(const rust::Vec<OpacityMicromapUsageCount> &counts) {
            std::vector<R::OpacityMicromapUsageCount> out;
            out.reserve(counts.size());
            for (const auto &c : counts) {
                out.push_back(R::OpacityMicromapUsageCount{c.count, c.subdivision_level, map(c.format)});
            }
            return out;
        }

        R::RayTracingShaderGroupType map(RayTracingShaderGroupType v) noexcept {
            switch (v) {
            case RayTracingShaderGroupType::General: return R::RayTracingShaderGroupType::General;
            case RayTracingShaderGroupType::TrianglesHitGroup: return R::RayTracingShaderGroupType::TrianglesHitGroup;
            case RayTracingShaderGroupType::ProceduralHitGroup: return R::RayTracingShaderGroupType::ProceduralHitGroup;
            }
            return R::RayTracingShaderGroupType::General;
        }

        R::QueryType map(QueryType v) noexcept {
            switch (v) {
            case QueryType::Occlusion: return R::QueryType::Occlusion;
            case QueryType::Timestamp: return R::QueryType::Timestamp;
            case QueryType::PipelineStatistics: return R::QueryType::PipelineStatistics;
            }
            return R::QueryType::Timestamp;
        }

        // ─── Byte-span helpers ────────────────────────────────────────────────────
        std::span<const std::byte> as_bytes(rust::Slice<const std::uint8_t> data) noexcept {
            return {reinterpret_cast<const std::byte *>(data.data()), data.size()};
        }
        std::span<std::byte> as_bytes_mut(rust::Slice<std::uint8_t> data) noexcept {
            return {reinterpret_cast<std::byte *>(data.data()), data.size()};
        }

        // ─── Descriptor conversions ───────────────────────────────────────────────
        R::ShaderEntry to_rhi(const ShaderEntry &e, std::string &entry_point_storage) {
            entry_point_storage = std::string(e.entry_point);
            R::ShaderEntry out{};
            out.module = to_rhi_handle<R::ShaderModuleHandle>(e.module);
            out.entry_point = entry_point_storage.c_str();
            out.stage = static_cast<R::ShaderStage>(e.stage);
            return out;
        }

        R::VertexAttribute to_rhi(const VertexAttribute &a, std::string &semantic_storage) {
            semantic_storage = std::string(a.semantic_name);
            R::VertexAttribute out{};
            out.format = map(a.format);
            out.offset = a.offset;
            out.shader_location = a.shader_location;
            out.semantic_name = semantic_storage.c_str();
            out.semantic_index = a.semantic_index;
            return out;
        }

        R::BindGroupLayoutEntry to_rhi(const BindGroupLayoutEntry &e) {
            R::BindGroupLayoutEntry out{};
            out.binding = e.binding;
            out.shader_register = e.shader_register;
            out.type = map(e.kind);
            out.visibility = static_cast<R::ShaderStage>(e.visibility);
            out.count = e.count;
            out.has_dynamic_offset = e.has_dynamic_offset;
            out.flags = static_cast<R::BindingFlags>(e.flags);
            out.storage_format = map(e.storage_format);
            out.storage_access = map(e.storage_access);
            out.sampler_is_comparison = e.sampler_is_comparison;
            out.sampled_texture_is_depth = e.sampled_texture_is_depth;
            out.sampled_texture_is_multisampled = e.sampled_texture_is_multisampled;
            return out;
        }

        R::BindGroupEntry to_rhi(const BindGroupEntry &e) {
            R::BindGroupEntry out{};
            out.binding = e.binding;
            out.array_element = e.array_element;
            out.buffer = to_rhi_handle<R::BufferHandle>(e.buffer);
            out.offset = e.offset;
            out.size = e.size;
            out.structure_stride = e.structure_stride;
            out.texture_view = to_rhi_handle<R::TextureViewHandle>(e.texture_view);
            out.sampler = to_rhi_handle<R::SamplerHandle>(e.sampler);
            out.acceleration_structure = to_rhi_handle<R::AccelerationStructureHandle>(e.acceleration_structure);
            return out;
        }

        R::PushConstantRange to_rhi(const PushConstantRange &p) {
            R::PushConstantRange out{};
            out.stages = static_cast<R::ShaderStage>(p.stages);
            out.offset = p.offset;
            out.size = p.size;
            out.shader_register = p.shader_register;
            out.register_space = p.register_space;
            return out;
        }

        R::AccelerationStructureTrianglesDesc to_rhi(const AccelerationStructureTrianglesDesc &t) {
            R::AccelerationStructureTrianglesDesc out{};
            out.vertex_buffer = to_rhi_handle<R::BufferHandle>(t.vertex_buffer);
            out.vertex_offset = t.vertex_offset;
            out.vertex_format = map(t.vertex_format);
            out.vertex_stride = t.vertex_stride;
            out.max_vertex = t.max_vertex;
            out.index_buffer = to_rhi_handle<R::BufferHandle>(t.index_buffer);
            out.index_offset = t.index_offset;
            out.index_format = map(t.index_format);
            out.transform_buffer = to_rhi_handle<R::BufferHandle>(t.transform_buffer);
            out.transform_offset = t.transform_offset;
            out.opacity_micromap = to_rhi_handle<R::OpacityMicromapHandle>(t.opacity_micromap);
            out.opacity_micromap_index_buffer = to_rhi_handle<R::BufferHandle>(t.opacity_micromap_index_buffer);
            out.opacity_micromap_index_offset = t.opacity_micromap_index_offset;
            out.opacity_micromap_index_format = map(t.opacity_micromap_index_format);
            return out;
        }

        R::AccelerationStructureInstancesDesc to_rhi(const AccelerationStructureInstancesDesc &i) {
            R::AccelerationStructureInstancesDesc out{};
            out.buffer = to_rhi_handle<R::BufferHandle>(i.buffer);
            out.offset = i.offset;
            out.array_of_pointers = i.array_of_pointers;
            return out;
        }

        R::AccelerationStructureGeometryDesc to_rhi(const AccelerationStructureGeometryDesc &g) {
            R::AccelerationStructureGeometryDesc out{};
            out.type = map(g.geometry_type);
            out.flags = static_cast<R::AccelerationStructureGeometryFlags>(g.flags);
            out.triangles = to_rhi(g.triangles);
            out.instances = to_rhi(g.instances);
            out.aabbs.buffer = to_rhi_handle<R::BufferHandle>(g.aabbs.buffer);
            out.aabbs.offset = g.aabbs.offset;
            out.aabbs.stride = g.aabbs.stride;
            return out;
        }

        R::AccelerationStructureBuildRangeInfo to_rhi(const AccelerationStructureBuildRangeInfo &r) {
            R::AccelerationStructureBuildRangeInfo out{};
            out.primitive_count = r.primitive_count;
            out.primitive_offset = r.primitive_offset;
            out.first_vertex = r.first_vertex;
            out.transform_offset = r.transform_offset;
            return out;
        }

        // Converts an AccelerationStructureBuildDesc, keeping the geometry/range storage alive in
        // the vectors passed by the caller (so the returned RHI struct's spans stay valid).
        R::AccelerationStructureBuildDesc to_rhi(const AccelerationStructureBuildDesc &d,
                                                 std::vector<R::AccelerationStructureGeometryDesc> &geometries,
                                                 std::vector<R::AccelerationStructureBuildRangeInfo> &ranges) {
            geometries.reserve(d.geometries.size());
            for (const auto &g : d.geometries) {
                geometries.push_back(to_rhi(g));
            }
            ranges.reserve(d.ranges.size());
            for (const auto &r : d.ranges) {
                ranges.push_back(to_rhi(r));
            }
            R::AccelerationStructureBuildDesc out{};
            out.type = map(d.kind);
            out.flags = static_cast<R::AccelerationStructureBuildFlags>(d.flags);
            out.dst = to_rhi_handle<R::AccelerationStructureHandle>(d.dst);
            out.src = to_rhi_handle<R::AccelerationStructureHandle>(d.src);
            out.scratch_buffer = to_rhi_handle<R::BufferHandle>(d.scratch_buffer);
            out.scratch_offset = d.scratch_offset;
            out.geometries = geometries;
            out.ranges = ranges;
            return out;
        }

        FeatureProperties to_bridge(const R::FeatureProperties &props) noexcept {
            FeatureProperties out{};
            out.ray_tracing.max_ray_recursion_depth = props.ray_tracing.max_ray_recursion_depth;
            out.ray_tracing.shader_group_handle_size = props.ray_tracing.shader_group_handle_size;
            out.ray_tracing.shader_group_base_alignment = props.ray_tracing.shader_group_base_alignment;
            out.ray_tracing.max_ray_hit_attribute_size = props.ray_tracing.max_ray_hit_attribute_size;
            out.ray_tracing.max_acceleration_structure_geometry_count =
                props.ray_tracing.max_acceleration_structure_geometry_count;
            out.ray_tracing.max_acceleration_structure_instance_count =
                props.ray_tracing.max_acceleration_structure_instance_count;
            out.ray_tracing.min_acceleration_structure_scratch_offset_alignment =
                props.ray_tracing.min_acceleration_structure_scratch_offset_alignment;

            out.mesh_shader.max_task_work_group_invocations = props.mesh_shader.max_task_work_group_invocations;
            out.mesh_shader.max_mesh_work_group_invocations = props.mesh_shader.max_mesh_work_group_invocations;
            out.mesh_shader.max_mesh_output_vertices = props.mesh_shader.max_mesh_output_vertices;
            out.mesh_shader.max_mesh_output_primitives = props.mesh_shader.max_mesh_output_primitives;
            out.mesh_shader.max_mesh_multiview_view_count = props.mesh_shader.max_mesh_multiview_view_count;
            out.mesh_shader.max_mesh_payload_size = props.mesh_shader.max_mesh_payload_size;

            out.variable_rate_shading.min_tile_width = props.variable_rate_shading.min_tile_width;
            out.variable_rate_shading.min_tile_height = props.variable_rate_shading.min_tile_height;
            out.variable_rate_shading.max_tile_width = props.variable_rate_shading.max_tile_width;
            out.variable_rate_shading.max_tile_height = props.variable_rate_shading.max_tile_height;

            out.subgroup.min_subgroup_size = props.subgroup.min_subgroup_size;
            out.subgroup.max_subgroup_size = props.subgroup.max_subgroup_size;
            out.subgroup.supported_stage_mask = props.subgroup.supported_stage_mask;
            out.subgroup.supported_operation_mask = props.subgroup.supported_operation_mask;

            out.descriptor_indexing.max_update_after_bind_descriptors =
                props.descriptor_indexing.max_update_after_bind_descriptors;
            out.descriptor_indexing.max_variable_descriptor_count =
                props.descriptor_indexing.max_variable_descriptor_count;

            out.sparse_resources.residency_standard_2d_block_shape = props.sparse_resources.residency_standard_2d_block_shape;
            out.sparse_resources.residency_standard_3d_block_shape = props.sparse_resources.residency_standard_3d_block_shape;
            out.sparse_resources.residency_aligned_mip_size = props.sparse_resources.residency_aligned_mip_size;
            out.sparse_resources.residency_non_resident_strict = props.sparse_resources.residency_non_resident_strict;
            return out;
        }

    } // namespace

    RhiDevice *engine_rhi_device(EngineView &engine) noexcept {
        return engine.rhi_device();
    }

    bool renderer_texture_resources(EngineView &engine, std::uint64_t renderer_texture, RendererTextureResources &out) noexcept {
        SFT::Renderer::Renderer *renderer = engine.renderer();
        if (renderer == nullptr || renderer_texture == 0) {
            return false;
        }
        const SFT::Renderer::TextureResource *resource = renderer->texture(SFT::Renderer::TextureHandle{renderer_texture});
        if (resource == nullptr || !resource->alive || !resource->texture.is_valid()) {
            return false;
        }
        out.texture.value = resource->texture.value;
        out.view.value = resource->view.value;
        out.sampler.value = resource->sampler.value;
        out.width = resource->width;
        out.height = resource->height;
        out.mip_levels = resource->mip_levels;
        out.format = static_cast<Format>(static_cast<std::uint8_t>(resource->format));
        return true;
    }

    FeatureProperties rhi_feature_properties(const RhiDevice &device) noexcept {
        return to_bridge(device.feature_properties());
    }

    DeviceLimits rhi_device_limits(const RhiDevice &device) noexcept {
        const R::DeviceLimits &limits = device.limits();
        DeviceLimits out{};
        out.max_texture_dimension_2d = limits.max_texture_dimension_2d;
        out.max_texture_array_layers = limits.max_texture_array_layers;
        out.max_bind_groups = limits.max_bind_groups;
        out.max_push_constants_size = limits.max_push_constants_size;
        out.max_vertex_buffers = limits.max_vertex_buffers;
        out.max_vertex_attributes = limits.max_vertex_attributes;
        out.max_color_attachments = limits.max_color_attachments;
        out.max_framebuffer_sample_count = limits.max_framebuffer_sample_count;
        out.framebuffer_sample_counts = limits.framebuffer_sample_counts;
        out.supports_minimum_depth_resolve = limits.supports_minimum_depth_resolve;
        out.supports_bc_texture_compression = limits.supports_bc_texture_compression;
        out.max_compute_workgroup_size_x = limits.max_compute_workgroup_size_x;
        out.max_compute_workgroup_size_y = limits.max_compute_workgroup_size_y;
        out.max_compute_workgroup_size_z = limits.max_compute_workgroup_size_z;
        out.min_uniform_buffer_offset_alignment = limits.min_uniform_buffer_offset_alignment;
        out.min_storage_buffer_offset_alignment = limits.min_storage_buffer_offset_alignment;
        out.timestamp_period_ns = limits.timestamp_period_ns;
        out.timestamp_valid_bits = limits.timestamp_valid_bits;
        return out;
    }

    namespace {
        rust::String feature_string(R::Feature feature) {
            const char *name = R::feature_name(feature);
            return rust::String::lossy(name != nullptr ? name : "");
        }

        rust::String view_string(std::string_view text) {
            return rust::String::lossy(text.data(), text.size());
        }

        QueueClass from_engine(R::QueueClass v) noexcept {
            switch (v) {
            case R::QueueClass::Graphics: return QueueClass::Graphics;
            case R::QueueClass::Compute: return QueueClass::Compute;
            case R::QueueClass::Transfer: return QueueClass::Transfer;
            case R::QueueClass::Sparse: return QueueClass::Sparse;
            case R::QueueClass::VideoDecode: return QueueClass::VideoDecode;
            case R::QueueClass::VideoEncode: return QueueClass::VideoEncode;
            }
            return QueueClass::Graphics;
        }
    } // namespace

    rust::Vec<rust::String> rhi_enabled_features(const RhiDevice &device) {
        rust::Vec<rust::String> out;
        device.enabled_features().for_each([&](R::Feature feature) { out.push_back(feature_string(feature)); });
        return out;
    }

    rust::Vec<rust::String> rhi_all_feature_names() {
        rust::Vec<rust::String> out;
        for (std::size_t i = 0; i < R::feature_count; ++i) {
            out.push_back(feature_string(static_cast<R::Feature>(i)));
        }
        return out;
    }

    rust::Vec<ExtensionInfo> rhi_enabled_extensions(const RhiDevice &device) {
        rust::Vec<ExtensionInfo> out;
        for (const R::ExtensionId &extension : device.enabled_extensions()) {
            ExtensionInfo info{};
            info.name_space = view_string(extension.name_space);
            info.name = view_string(extension.name);
            info.version = extension.version;
            out.push_back(std::move(info));
        }
        return out;
    }

    rust::Vec<QueueInfo> rhi_queue_infos(const RhiDevice &device) {
        rust::Vec<QueueInfo> out;
        for (const R::QueueInfo &queue : device.queue_infos()) {
            QueueInfo info{};
            info.queue = from_engine(queue.queue);
            info.capabilities = static_cast<std::uint32_t>(queue.capabilities);
            info.lane_count = queue.lane_count;
            info.physical_group = queue.physical_group;
            info.likely_parallel_with_graphics = queue.likely_parallel_with_graphics;
            info.dedicated = queue.dedicated;
            info.label = rust::String::lossy(queue.label != nullptr ? queue.label : "");
            out.push_back(std::move(info));
        }
        return out;
    }

    // ─── Buffers ──────────────────────────────────────────────────────────────────

    BufferHandle rhi_create_buffer(RhiDevice &device, const BufferDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::BufferDesc d{};
        d.size = desc.size;
        d.usage = static_cast<R::BufferUsage>(desc.usage);
        d.memory = map(desc.memory);
        d.label = label.c_str();
        return unwrap_handle<BufferHandle>(device.create_buffer(d), status);
    }

    void rhi_destroy_buffer(RhiDevice &device, BufferHandle handle) noexcept {
        device.destroy_buffer(to_rhi_handle<R::BufferHandle>(handle));
    }

    void rhi_write_buffer(RhiDevice &device, BufferHandle buffer, std::uint64_t offset,
                          rust::Slice<const std::uint8_t> data, RhiStatus &status) {
        unwrap_void(device.write_buffer(to_rhi_handle<R::BufferHandle>(buffer), offset, as_bytes(data)), status);
    }

    std::uint64_t rhi_buffer_device_address(const RhiDevice &device, BufferHandle buffer, RhiStatus &status) {
        return unwrap<std::uint64_t>(device.buffer_device_address(to_rhi_handle<R::BufferHandle>(buffer)), status);
    }

    std::uint8_t *rhi_map_buffer(RhiDevice &device, BufferHandle buffer, std::uint64_t &len, RhiStatus &status) {
        auto result = device.map_buffer(to_rhi_handle<R::BufferHandle>(buffer));
        if (!result) {
            set_error(status, result.error());
            len = 0;
            return nullptr;
        }
        set_ok(status);
        len = static_cast<std::uint64_t>(result->size());
        return reinterpret_cast<std::uint8_t *>(result->data());
    }

    void rhi_unmap_buffer(RhiDevice &device, BufferHandle buffer) noexcept {
        device.unmap_buffer(to_rhi_handle<R::BufferHandle>(buffer));
    }

    // ─── Textures ─────────────────────────────────────────────────────────────────

    TextureHandle rhi_create_texture(RhiDevice &device, const TextureDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::TextureDesc d{};
        d.dimension = map(desc.dimension);
        d.format = map(desc.format);
        d.extent = {desc.width, desc.height, desc.depth_or_layers};
        d.mip_levels = desc.mip_levels;
        d.samples = map(desc.samples);
        d.usage = static_cast<R::TextureUsage>(desc.usage);
        d.label = label.c_str();
        return unwrap_handle<TextureHandle>(device.create_texture(d), status);
    }

    void rhi_destroy_texture(RhiDevice &device, TextureHandle handle) noexcept {
        device.destroy_texture(to_rhi_handle<R::TextureHandle>(handle));
    }

    TextureViewHandle rhi_create_texture_view(RhiDevice &device, const TextureViewDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::TextureViewDesc d{};
        d.texture = to_rhi_handle<R::TextureHandle>(desc.texture);
        d.view_type = map(desc.view_type);
        d.format = map(desc.format);
        d.base_mip_level = desc.base_mip_level;
        d.mip_level_count = desc.mip_level_count;
        d.base_array_layer = desc.base_array_layer;
        d.array_layer_count = desc.array_layer_count;
        d.label = label.c_str();
        return unwrap_handle<TextureViewHandle>(device.create_texture_view(d), status);
    }

    void rhi_destroy_texture_view(RhiDevice &device, TextureViewHandle handle) noexcept {
        device.destroy_texture_view(to_rhi_handle<R::TextureViewHandle>(handle));
    }

    // ─── Samplers ─────────────────────────────────────────────────────────────────

    SamplerHandle rhi_create_sampler(RhiDevice &device, const SamplerDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::SamplerDesc d{};
        d.min_filter = map(desc.min_filter);
        d.mag_filter = map(desc.mag_filter);
        d.mipmap_mode = map(desc.mipmap_mode);
        d.address_u = map(desc.address_u);
        d.address_v = map(desc.address_v);
        d.address_w = map(desc.address_w);
        d.mip_lod_bias = desc.mip_lod_bias;
        d.min_lod = desc.min_lod;
        d.max_lod = desc.max_lod;
        d.max_anisotropy = desc.max_anisotropy;
        d.compare_enable = desc.compare_enable;
        d.compare = map(desc.compare);
        d.border_color = map(desc.border_color);
        d.label = label.c_str();
        return unwrap_handle<SamplerHandle>(device.create_sampler(d), status);
    }

    void rhi_destroy_sampler(RhiDevice &device, SamplerHandle handle) noexcept {
        device.destroy_sampler(to_rhi_handle<R::SamplerHandle>(handle));
    }

    // ─── Shader modules ───────────────────────────────────────────────────────────

    ShaderModuleHandle rhi_create_shader_module(RhiDevice &device, const ShaderModuleDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::ShaderModuleDesc d{};
        d.language = map(desc.language);
        d.code = {reinterpret_cast<const std::byte *>(desc.code.data()), desc.code.size()};
        d.label = label.c_str();
        return unwrap_handle<ShaderModuleHandle>(device.create_shader_module(d), status);
    }

    void rhi_destroy_shader_module(RhiDevice &device, ShaderModuleHandle handle) noexcept {
        device.destroy_shader_module(to_rhi_handle<R::ShaderModuleHandle>(handle));
    }

    // ─── Bind group layouts / bind groups ────────────────────────────────────────

    BindGroupLayoutHandle rhi_create_bind_group_layout(RhiDevice &device, const BindGroupLayoutDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        std::vector<R::BindGroupLayoutEntry> entries;
        entries.reserve(desc.entries.size());
        for (const auto &e : desc.entries) {
            entries.push_back(to_rhi(e));
        }
        R::BindGroupLayoutDesc d{};
        d.entries = entries;
        d.label = label.c_str();
        return unwrap_handle<BindGroupLayoutHandle>(device.create_bind_group_layout(d), status);
    }

    void rhi_destroy_bind_group_layout(RhiDevice &device, BindGroupLayoutHandle handle) noexcept {
        device.destroy_bind_group_layout(to_rhi_handle<R::BindGroupLayoutHandle>(handle));
    }

    BindGroupHandle rhi_create_bind_group(RhiDevice &device, const BindGroupDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        std::vector<R::BindGroupEntry> entries;
        entries.reserve(desc.entries.size());
        for (const auto &e : desc.entries) {
            entries.push_back(to_rhi(e));
        }
        R::BindGroupDesc d{};
        d.layout = to_rhi_handle<R::BindGroupLayoutHandle>(desc.layout);
        d.entries = entries;
        d.variable_descriptor_count = desc.variable_descriptor_count;
        d.lifetime = map(desc.lifetime);
        d.label = label.c_str();
        return unwrap_handle<BindGroupHandle>(device.create_bind_group(d), status);
    }

    void rhi_destroy_bind_group(RhiDevice &device, BindGroupHandle handle) noexcept {
        device.destroy_bind_group(to_rhi_handle<R::BindGroupHandle>(handle));
    }

    // ─── Pipeline layouts ─────────────────────────────────────────────────────────

    PipelineLayoutHandle rhi_create_pipeline_layout(RhiDevice &device, const PipelineLayoutDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        std::vector<R::BindGroupLayoutHandle> layouts;
        layouts.reserve(desc.bind_group_layouts.size());
        for (const auto &l : desc.bind_group_layouts) {
            layouts.push_back(to_rhi_handle<R::BindGroupLayoutHandle>(l));
        }
        std::vector<R::PushConstantRange> ranges;
        ranges.reserve(desc.push_constant_ranges.size());
        for (const auto &r : desc.push_constant_ranges) {
            ranges.push_back(to_rhi(r));
        }
        R::PipelineLayoutDesc d{};
        d.bind_group_layouts = layouts;
        d.push_constant_ranges = ranges;
        d.label = label.c_str();
        return unwrap_handle<PipelineLayoutHandle>(device.create_pipeline_layout(d), status);
    }

    void rhi_destroy_pipeline_layout(RhiDevice &device, PipelineLayoutHandle handle) noexcept {
        device.destroy_pipeline_layout(to_rhi_handle<R::PipelineLayoutHandle>(handle));
    }

    // ─── Pipelines ────────────────────────────────────────────────────────────────

    RenderPipelineHandle rhi_create_render_pipeline(RhiDevice &device, const RenderPipelineDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        std::string vertex_entry, fragment_entry;
        R::RenderPipelineDesc d{};
        d.layout = to_rhi_handle<R::PipelineLayoutHandle>(desc.layout);
        d.vertex = to_rhi(desc.vertex, vertex_entry);
        d.fragment = to_rhi(desc.fragment, fragment_entry);

        // Keep per-attribute semantic-name storage and the vertex-buffer vector alive for the call.
        std::vector<std::vector<std::string>> semantic_storage(desc.vertex_buffers.size());
        std::vector<std::vector<R::VertexAttribute>> attribute_storage(desc.vertex_buffers.size());
        std::vector<R::VertexBufferLayout> vertex_buffers;
        vertex_buffers.reserve(desc.vertex_buffers.size());
        for (std::size_t i = 0; i < desc.vertex_buffers.size(); ++i) {
            const auto &vb = desc.vertex_buffers[i];
            semantic_storage[i].resize(vb.attributes.size());
            attribute_storage[i].reserve(vb.attributes.size());
            for (std::size_t a = 0; a < vb.attributes.size(); ++a) {
                attribute_storage[i].push_back(to_rhi(vb.attributes[a], semantic_storage[i][a]));
            }
            R::VertexBufferLayout layout{};
            layout.stride = vb.stride;
            layout.step_mode = map(vb.step_mode);
            layout.attributes = attribute_storage[i];
            vertex_buffers.push_back(layout);
        }
        d.vertex_buffers = vertex_buffers;

        d.topology = map(desc.topology);
        d.rasterization.polygon_mode = map(desc.rasterization.polygon_mode);
        d.rasterization.cull_mode = map(desc.rasterization.cull_mode);
        d.rasterization.front_face = map(desc.rasterization.front_face);
        d.rasterization.depth_bias_constant = desc.rasterization.depth_bias_constant;
        d.rasterization.depth_bias_slope_scale = desc.rasterization.depth_bias_slope_scale;
        d.rasterization.depth_bias_clamp = desc.rasterization.depth_bias_clamp;
        d.rasterization.line_width = desc.rasterization.line_width;

        d.multisample.samples = map(desc.multisample.samples);
        d.multisample.sample_mask = desc.multisample.sample_mask;
        d.multisample.alpha_to_coverage_enable = desc.multisample.alpha_to_coverage_enable;
        d.multisample.sample_locations_enable = desc.multisample.sample_locations_enable;

        d.depth_stencil.format = map(desc.depth_stencil.format);
        d.depth_stencil.depth_test_enable = desc.depth_stencil.depth_test_enable;
        d.depth_stencil.depth_write_enable = desc.depth_stencil.depth_write_enable;
        d.depth_stencil.depth_compare = map(desc.depth_stencil.depth_compare);
        d.depth_stencil.stencil_test_enable = desc.depth_stencil.stencil_test_enable;
        d.depth_stencil.stencil_front = map(desc.depth_stencil.stencil_front);
        d.depth_stencil.stencil_back = map(desc.depth_stencil.stencil_back);
        d.depth_stencil.stencil_read_mask = desc.depth_stencil.stencil_read_mask;
        d.depth_stencil.stencil_write_mask = desc.depth_stencil.stencil_write_mask;
        d.depth_stencil.depth_bounds_test_enable = desc.depth_stencil.depth_bounds_test_enable;

        std::vector<R::ColorTargetState> color_targets;
        color_targets.reserve(desc.color_targets.size());
        for (const auto &c : desc.color_targets) {
            R::ColorTargetState t{};
            t.format = map(c.format);
            t.blend_enable = c.blend_enable;
            t.color.src_factor = map(c.color.src_factor);
            t.color.dst_factor = map(c.color.dst_factor);
            t.color.op = map(c.color.op);
            t.alpha.src_factor = map(c.alpha.src_factor);
            t.alpha.dst_factor = map(c.alpha.dst_factor);
            t.alpha.op = map(c.alpha.op);
            t.write_mask = static_cast<R::ColorWriteMask>(c.write_mask);
            color_targets.push_back(t);
        }
        d.color_targets = color_targets;
        d.label = label.c_str();

        return unwrap_handle<RenderPipelineHandle>(device.create_render_pipeline(d), status);
    }

    void rhi_destroy_render_pipeline(RhiDevice &device, RenderPipelineHandle handle) noexcept {
        device.destroy_render_pipeline(to_rhi_handle<R::RenderPipelineHandle>(handle));
    }

    ComputePipelineHandle rhi_create_compute_pipeline(RhiDevice &device, const ComputePipelineDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        std::string entry;
        R::ComputePipelineDesc d{};
        d.layout = to_rhi_handle<R::PipelineLayoutHandle>(desc.layout);
        d.compute = to_rhi(desc.compute, entry);
        d.label = label.c_str();
        return unwrap_handle<ComputePipelineHandle>(device.create_compute_pipeline(d), status);
    }

    void rhi_destroy_compute_pipeline(RhiDevice &device, ComputePipelineHandle handle) noexcept {
        device.destroy_compute_pipeline(to_rhi_handle<R::ComputePipelineHandle>(handle));
    }

    // ─── Query sets ───────────────────────────────────────────────────────────────

    QuerySetHandle rhi_create_query_set(RhiDevice &device, const QuerySetDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::QuerySetDesc d{};
        d.type = map(desc.query_type);
        d.count = desc.count;
        d.statistics = static_cast<R::PipelineStatistic>(desc.statistics);
        d.label = label.c_str();
        return unwrap_handle<QuerySetHandle>(device.create_query_set(d), status);
    }

    void rhi_destroy_query_set(RhiDevice &device, QuerySetHandle handle) noexcept {
        device.destroy_query_set(to_rhi_handle<R::QuerySetHandle>(handle));
    }

    void rhi_get_query_set_results(RhiDevice &device, QuerySetHandle query_set, std::uint32_t first,
                                   std::uint32_t count, rust::Slice<std::uint8_t> dst, std::uint64_t stride,
                                   std::uint32_t flags, RhiStatus &status) {
        unwrap_void(
            device.get_query_set_results(to_rhi_handle<R::QuerySetHandle>(query_set), first, count, as_bytes_mut(dst),
                                         stride, static_cast<R::QueryResultFlags>(flags)),
            status);
    }

    void rhi_reset_query_set(RhiDevice &device, QuerySetHandle query_set, std::uint32_t first, std::uint32_t count) noexcept {
        device.reset_query_set(to_rhi_handle<R::QuerySetHandle>(query_set), first, count);
    }

    // ─── Ray tracing ──────────────────────────────────────────────────────────────

    AccelerationStructureBuildSizes rhi_acceleration_structure_build_sizes(
        const RhiDevice &device, const AccelerationStructureBuildDesc &desc, RhiStatus &status) {
        std::vector<R::AccelerationStructureGeometryDesc> geometries;
        std::vector<R::AccelerationStructureBuildRangeInfo> ranges;
        R::AccelerationStructureBuildDesc d = to_rhi(desc, geometries, ranges);
        auto result = device.acceleration_structure_build_sizes(d);
        if (!result) {
            set_error(status, result.error());
            return AccelerationStructureBuildSizes{};
        }
        set_ok(status);
        AccelerationStructureBuildSizes out{};
        out.acceleration_structure_size = result->acceleration_structure_size;
        out.build_scratch_size = result->build_scratch_size;
        out.update_scratch_size = result->update_scratch_size;
        return out;
    }

    AccelerationStructureHandle rhi_create_acceleration_structure(
        RhiDevice &device, const AccelerationStructureDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::AccelerationStructureDesc d{};
        d.type = map(desc.kind);
        d.size = desc.size;
        d.label = label.c_str();
        return unwrap_handle<AccelerationStructureHandle>(device.create_acceleration_structure(d), status);
    }

    void rhi_destroy_acceleration_structure(RhiDevice &device, AccelerationStructureHandle handle) noexcept {
        device.destroy_acceleration_structure(to_rhi_handle<R::AccelerationStructureHandle>(handle));
    }

    std::uint64_t rhi_acceleration_structure_device_address(
        const RhiDevice &device, AccelerationStructureHandle handle, RhiStatus &status) {
        return unwrap<std::uint64_t>(
            device.acceleration_structure_device_address(to_rhi_handle<R::AccelerationStructureHandle>(handle)), status);
    }

    OpacityMicromapBuildSizes rhi_opacity_micromap_build_sizes(const RhiDevice &device, const OpacityMicromapDesc &desc,
                                                               RhiStatus &status) {
        const std::string label(desc.label);
        const std::vector<R::OpacityMicromapUsageCount> counts = to_rhi(desc.usage_counts);
        R::OpacityMicromapDesc d{};
        d.usage_counts = counts;
        d.label = label.c_str();
        auto result = device.opacity_micromap_build_sizes(d);
        if (!result) {
            set_error(status, result.error());
            return OpacityMicromapBuildSizes{};
        }
        set_ok(status);
        return OpacityMicromapBuildSizes{result->micromap_size, result->build_scratch_size};
    }

    OpacityMicromapHandle rhi_create_opacity_micromap(RhiDevice &device, const OpacityMicromapDesc &desc, std::uint64_t size,
                                                      RhiStatus &status) {
        const std::string label(desc.label);
        const std::vector<R::OpacityMicromapUsageCount> counts = to_rhi(desc.usage_counts);
        R::OpacityMicromapDesc d{};
        d.usage_counts = counts;
        d.label = label.c_str();
        return unwrap_handle<OpacityMicromapHandle>(device.create_opacity_micromap(d, size), status);
    }

    void rhi_destroy_opacity_micromap(RhiDevice &device, OpacityMicromapHandle handle) noexcept {
        device.destroy_opacity_micromap(to_rhi_handle<R::OpacityMicromapHandle>(handle));
    }

    RayTracingPipelineHandle rhi_create_ray_tracing_pipeline(
        RhiDevice &device, const RayTracingPipelineDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        // Keep every ShaderEntry's entry_point string alive for the call.
        std::vector<std::array<std::string, 4>> entry_storage(desc.groups.size());
        std::vector<R::RayTracingShaderGroupDesc> groups;
        groups.reserve(desc.groups.size());
        for (std::size_t i = 0; i < desc.groups.size(); ++i) {
            const auto &g = desc.groups[i];
            R::RayTracingShaderGroupDesc out{};
            out.type = map(g.group_type);
            out.general = to_rhi(g.general, entry_storage[i][0]);
            out.closest_hit = to_rhi(g.closest_hit, entry_storage[i][1]);
            out.any_hit = to_rhi(g.any_hit, entry_storage[i][2]);
            out.intersection = to_rhi(g.intersection, entry_storage[i][3]);
            groups.push_back(out);
        }
        R::RayTracingPipelineDesc d{};
        d.layout = to_rhi_handle<R::PipelineLayoutHandle>(desc.layout);
        d.groups = groups;
        d.max_ray_recursion_depth = desc.max_ray_recursion_depth;
        d.label = label.c_str();
        return unwrap_handle<RayTracingPipelineHandle>(device.create_ray_tracing_pipeline(d), status);
    }

    void rhi_destroy_ray_tracing_pipeline(RhiDevice &device, RayTracingPipelineHandle handle) noexcept {
        device.destroy_ray_tracing_pipeline(to_rhi_handle<R::RayTracingPipelineHandle>(handle));
    }

    void rhi_write_ray_tracing_shader_group_handles(
        RhiDevice &device, RayTracingPipelineHandle pipeline, std::uint32_t first_group,
        std::uint32_t group_count, rust::Slice<std::uint8_t> dst, RhiStatus &status) {
        unwrap_void(
            device.write_ray_tracing_shader_group_handles(
                to_rhi_handle<R::RayTracingPipelineHandle>(pipeline), first_group, group_count, as_bytes_mut(dst)),
            status);
    }

    rust::Vec<std::uint8_t> rhi_pack_acceleration_structure_instances(
        rust::Slice<const AccelerationStructureInstance> instances) {
        static_assert(sizeof(R::AccelerationStructureInstance) == 64);
        rust::Vec<std::uint8_t> out;
        out.reserve(instances.size() * sizeof(R::AccelerationStructureInstance));
        for (const auto &src : instances) {
            R::AccelerationStructureInstance packed{};
            for (int i = 0; i < 12; ++i) {
                packed.transform[static_cast<std::size_t>(i)] = src.transform[static_cast<std::size_t>(i)];
            }
            packed.set_custom_index_and_mask(src.custom_index, src.mask);
            packed.set_shader_binding_table_offset_and_flags(src.shader_binding_table_offset, src.flags);
            packed.acceleration_structure_device_address = src.blas_device_address;

            std::array<std::uint8_t, sizeof(R::AccelerationStructureInstance)> bytes{};
            std::memcpy(bytes.data(), &packed, sizeof(packed));
            for (auto b : bytes) {
                out.push_back(b);
            }
        }
        return out;
    }

    // ─── Command encoding ─────────────────────────────────────────────────────────

    std::unique_ptr<CommandEncoder> rhi_create_command_encoder(RhiDevice &device, const CommandEncoderDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::CommandEncoderDesc d{};
        d.queue.queue = map(desc.queue);
        d.label = label.c_str();
        auto result = device.create_command_encoder(d);
        if (!result) {
            set_error(status, result.error());
            return nullptr;
        }
        set_ok(status);
        return std::move(*result);
    }

    void rhi_submit(RhiDevice &device, rust::Slice<const CommandBufferHandle> command_buffers, RhiStatus &status) {
        std::vector<R::CommandBufferHandle> buffers;
        buffers.reserve(command_buffers.size());
        for (const auto &b : command_buffers) {
            buffers.push_back(to_rhi_handle<R::CommandBufferHandle>(b));
        }
        unwrap_void(device.submit(std::span<const R::CommandBufferHandle>(buffers)), status);
    }

    void rhi_wait_idle(RhiDevice &device) noexcept {
        device.wait_idle();
    }

    void rhi_submit_with(RhiDevice &device, const SubmitDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        std::vector<R::CommandBufferHandle> buffers;
        buffers.reserve(desc.command_buffers.size());
        for (const auto &b : desc.command_buffers) {
            buffers.push_back(to_rhi_handle<R::CommandBufferHandle>(b));
        }
        std::vector<R::QueueSemaphoreWait> waits;
        waits.reserve(desc.waits.size());
        for (const auto &w : desc.waits) {
            waits.push_back(R::QueueSemaphoreWait{to_rhi_handle<R::SemaphoreHandle>(w.semaphore), w.value,
                                                  static_cast<R::PipelineStage>(w.stages)});
        }
        std::vector<R::QueueSemaphoreSignal> signals;
        signals.reserve(desc.signals.size());
        for (const auto &s : desc.signals) {
            signals.push_back(R::QueueSemaphoreSignal{to_rhi_handle<R::SemaphoreHandle>(s.semaphore), s.value,
                                                      static_cast<R::PipelineStage>(s.stages)});
        }
        R::SubmitDesc d{};
        d.queue = map(desc.queue);
        d.command_buffers = buffers;
        d.waits = waits;
        d.signals = signals;
        d.fence = to_rhi_handle<R::FenceHandle>(desc.fence);
        d.flags = desc.one_shot ? R::SubmitFlags::OneShot : R::SubmitFlags::None;
        d.label = label.c_str();
        unwrap_void(device.submit(d), status);
    }

    // ─── Synchronization ──────────────────────────────────────────────────────────

    SemaphoreHandle rhi_create_semaphore(RhiDevice &device, const SemaphoreDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::SemaphoreDesc d{};
        d.initial_value = desc.initial_value;
        d.label = label.c_str();
        return unwrap_handle<SemaphoreHandle>(device.create_semaphore(d), status);
    }

    void rhi_destroy_semaphore(RhiDevice &device, SemaphoreHandle handle) noexcept {
        device.destroy_semaphore(to_rhi_handle<R::SemaphoreHandle>(handle));
    }

    std::uint64_t rhi_semaphore_value(const RhiDevice &device, SemaphoreHandle handle, RhiStatus &status) {
        return unwrap<std::uint64_t>(device.semaphore_value(to_rhi_handle<R::SemaphoreHandle>(handle)), status);
    }

    void rhi_wait_semaphore(RhiDevice &device, SemaphoreHandle handle, std::uint64_t value, std::uint64_t timeout_ns,
                            RhiStatus &status) {
        unwrap_void(device.wait_semaphore(to_rhi_handle<R::SemaphoreHandle>(handle), value, timeout_ns), status);
    }

    void rhi_signal_semaphore(RhiDevice &device, SemaphoreHandle handle, std::uint64_t value, RhiStatus &status) {
        unwrap_void(device.signal_semaphore(to_rhi_handle<R::SemaphoreHandle>(handle), value), status);
    }

    FenceHandle rhi_create_fence(RhiDevice &device, const FenceDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        R::FenceDesc d{};
        d.signaled = desc.signaled;
        d.label = label.c_str();
        return unwrap_handle<FenceHandle>(device.create_fence(d), status);
    }

    void rhi_destroy_fence(RhiDevice &device, FenceHandle handle) noexcept {
        device.destroy_fence(to_rhi_handle<R::FenceHandle>(handle));
    }

    namespace {
        std::vector<R::FenceHandle> to_rhi(rust::Slice<const FenceHandle> fences) {
            std::vector<R::FenceHandle> out;
            out.reserve(fences.size());
            for (const FenceHandle &f : fences) {
                out.push_back(to_rhi_handle<R::FenceHandle>(f));
            }
            return out;
        }
    } // namespace

    bool rhi_wait_fences(RhiDevice &device, rust::Slice<const FenceHandle> fences, bool wait_all, std::uint64_t timeout_ns,
                         RhiStatus &status) {
        return unwrap<bool>(device.wait_fences(to_rhi(fences), wait_all, timeout_ns), status, false);
    }

    void rhi_reset_fences(RhiDevice &device, rust::Slice<const FenceHandle> fences, RhiStatus &status) {
        unwrap_void(device.reset_fences(to_rhi(fences)), status);
    }

    // ─── Render bundles ───────────────────────────────────────────────────────────

    std::unique_ptr<RenderBundleEncoder> rhi_create_render_bundle_encoder(RhiDevice &device, const RenderBundleDesc &desc,
                                                                          RhiStatus &status) {
        const std::string label(desc.label);
        std::vector<R::Format> color_formats;
        color_formats.reserve(desc.color_formats.size());
        for (Format f : desc.color_formats) {
            color_formats.push_back(map(f));
        }
        R::RenderBundleDesc d{};
        d.color_formats = color_formats;
        d.depth_stencil_format = map(desc.depth_stencil_format);
        d.samples = map(desc.samples);
        d.view_mask = desc.view_mask;
        d.label = label.c_str();
        auto result = device.create_render_bundle_encoder(d);
        if (!result) {
            set_error(status, result.error());
            return nullptr;
        }
        set_ok(status);
        return std::move(*result);
    }

    void rhi_destroy_render_bundle(RhiDevice &device, RenderBundleHandle handle) noexcept {
        device.destroy_render_bundle(to_rhi_handle<R::RenderBundleHandle>(handle));
    }

    void rb_set_pipeline(RenderBundleEncoder &rb, RenderPipelineHandle pipeline) noexcept {
        rb.set_pipeline(to_rhi_handle<R::RenderPipelineHandle>(pipeline));
    }

    void rb_set_bind_group(RenderBundleEncoder &rb, std::uint32_t index, BindGroupHandle bind_group,
                           rust::Slice<const std::uint32_t> dynamic_offsets) noexcept {
        rb.set_bind_group(index, to_rhi_handle<R::BindGroupHandle>(bind_group),
                          std::span<const std::uint32_t>(dynamic_offsets.data(), dynamic_offsets.size()));
    }

    void rb_set_vertex_buffer(RenderBundleEncoder &rb, std::uint32_t slot, BufferHandle buffer, std::uint64_t offset) noexcept {
        rb.set_vertex_buffer(slot, to_rhi_handle<R::BufferHandle>(buffer), offset);
    }

    void rb_set_index_buffer(RenderBundleEncoder &rb, BufferHandle buffer, IndexFormat format, std::uint64_t offset) noexcept {
        rb.set_index_buffer(to_rhi_handle<R::BufferHandle>(buffer), map(format), offset);
    }

    void rb_set_push_constants(RenderBundleEncoder &rb, std::uint32_t stages, std::uint32_t offset,
                               rust::Slice<const std::uint8_t> data) noexcept {
        rb.set_push_constants(static_cast<R::ShaderStage>(stages), offset, as_bytes(data));
    }

    void rb_set_viewport(RenderBundleEncoder &rb, const Viewport &viewport) noexcept {
        rb.set_viewport(R::Viewport{viewport.x, viewport.y, viewport.width, viewport.height, viewport.min_depth, viewport.max_depth});
    }

    void rb_set_scissor(RenderBundleEncoder &rb, const Rect2D &scissor) noexcept {
        rb.set_scissor(R::Rect2D{scissor.x, scissor.y, scissor.width, scissor.height});
    }

    void rb_set_blend_constant(RenderBundleEncoder &rb, const ClearColor &color) noexcept {
        rb.set_blend_constant(R::ClearColor{color.r, color.g, color.b, color.a});
    }

    void rb_set_stencil_reference(RenderBundleEncoder &rb, std::uint32_t reference) noexcept {
        rb.set_stencil_reference(reference);
    }

    void rb_set_depth_bounds(RenderBundleEncoder &rb, float min_depth, float max_depth) noexcept {
        rb.set_depth_bounds(min_depth, max_depth);
    }

    void rb_set_sample_locations(RenderBundleEncoder &rb, std::uint32_t samples_per_pixel, std::uint32_t grid_width,
                                 std::uint32_t grid_height, rust::Slice<const SampleLocation> locations) noexcept {
        rb.set_sample_locations(samples_per_pixel, R::Extent2D{grid_width, grid_height}, to_rhi(locations));
    }

    void rb_draw(RenderBundleEncoder &rb, const DrawArgs &args) noexcept {
        rb.draw(R::DrawArgs{args.vertex_count, args.instance_count, args.first_vertex, args.first_instance});
    }

    void rb_draw_indexed(RenderBundleEncoder &rb, const DrawIndexedArgs &args) noexcept {
        rb.draw_indexed(R::DrawIndexedArgs{
            args.index_count, args.instance_count, args.first_index, args.base_vertex, args.first_instance});
    }

    void rb_draw_mesh_tasks(RenderBundleEncoder &rb, const DrawMeshTasksArgs &args) noexcept {
        rb.draw_mesh_tasks(R::DrawMeshTasksArgs{args.group_count_x, args.group_count_y, args.group_count_z});
    }

    void rb_draw_indirect(RenderBundleEncoder &rb, BufferHandle indirect_buffer, std::uint64_t offset) noexcept {
        rb.draw_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset);
    }

    void rb_draw_indexed_indirect(RenderBundleEncoder &rb, BufferHandle indirect_buffer, std::uint64_t offset) noexcept {
        rb.draw_indexed_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset);
    }

    void rb_draw_indirect_multi(RenderBundleEncoder &rb, BufferHandle indirect_buffer, std::uint64_t offset,
                                std::uint32_t draw_count, std::uint32_t stride) noexcept {
        rb.draw_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset, draw_count, stride);
    }

    void rb_draw_indexed_indirect_multi(RenderBundleEncoder &rb, BufferHandle indirect_buffer, std::uint64_t offset,
                                        std::uint32_t draw_count, std::uint32_t stride) noexcept {
        rb.draw_indexed_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset, draw_count, stride);
    }

    void rb_draw_indirect_count(RenderBundleEncoder &rb, BufferHandle indirect_buffer, std::uint64_t indirect_offset,
                                BufferHandle count_buffer, std::uint64_t count_offset, std::uint32_t max_draws,
                                std::uint32_t stride) noexcept {
        rb.draw_indirect_count(to_rhi_handle<R::BufferHandle>(indirect_buffer), indirect_offset,
                               to_rhi_handle<R::BufferHandle>(count_buffer), count_offset, max_draws, stride);
    }

    void rb_draw_indexed_indirect_count(RenderBundleEncoder &rb, BufferHandle indirect_buffer, std::uint64_t indirect_offset,
                                        BufferHandle count_buffer, std::uint64_t count_offset, std::uint32_t max_draws,
                                        std::uint32_t stride) noexcept {
        rb.draw_indexed_indirect_count(to_rhi_handle<R::BufferHandle>(indirect_buffer), indirect_offset,
                                       to_rhi_handle<R::BufferHandle>(count_buffer), count_offset, max_draws, stride);
    }

    void rb_draw_mesh_tasks_indirect(RenderBundleEncoder &rb, BufferHandle indirect_buffer, std::uint64_t offset) noexcept {
        rb.draw_mesh_tasks_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset);
    }

    void rb_draw_mesh_tasks_indirect_count(RenderBundleEncoder &rb, BufferHandle indirect_buffer,
                                           std::uint64_t indirect_offset, BufferHandle count_buffer,
                                           std::uint64_t count_offset, std::uint32_t max_draws,
                                           std::uint32_t stride) noexcept {
        rb.draw_mesh_tasks_indirect_count(to_rhi_handle<R::BufferHandle>(indirect_buffer), indirect_offset,
                                          to_rhi_handle<R::BufferHandle>(count_buffer), count_offset, max_draws, stride);
    }

    RenderBundleHandle rb_finish(RenderBundleEncoder &rb, RhiStatus &status) {
        return unwrap_handle<RenderBundleHandle>(rb.finish(), status);
    }

    std::unique_ptr<RenderPassEncoder> ce_begin_render_pass(CommandEncoder &encoder, const RenderPassDesc &desc, RhiStatus &status) {
        const std::string label(desc.label);
        std::vector<R::ColorAttachment> color_attachments;
        color_attachments.reserve(desc.color_attachments.size());
        for (const auto &c : desc.color_attachments) {
            R::ColorAttachment out{};
            out.view = to_rhi_handle<R::TextureViewHandle>(c.view);
            out.resolve_view = to_rhi_handle<R::TextureViewHandle>(c.resolve_view);
            out.load_op = map(c.load_op);
            out.store_op = map(c.store_op);
            out.clear_color = {c.clear_color.r, c.clear_color.g, c.clear_color.b, c.clear_color.a};
            color_attachments.push_back(out);
        }
        R::RenderPassDesc d{};
        d.color_attachments = color_attachments;
        if (desc.has_depth_stencil) {
            R::DepthStencilAttachment ds{};
            ds.view = to_rhi_handle<R::TextureViewHandle>(desc.depth_stencil.view);
            ds.depth_load_op = map(desc.depth_stencil.depth_load_op);
            ds.depth_store_op = map(desc.depth_stencil.depth_store_op);
            ds.stencil_load_op = map(desc.depth_stencil.stencil_load_op);
            ds.stencil_store_op = map(desc.depth_stencil.stencil_store_op);
            ds.clear_value = {desc.depth_stencil.clear_depth, desc.depth_stencil.clear_stencil};
            d.depth_stencil = ds;
        }
        d.render_area = {desc.render_area.x, desc.render_area.y, desc.render_area.width, desc.render_area.height};
        d.label = label.c_str();

        auto result = encoder.begin_render_pass(d);
        if (!result) {
            set_error(status, result.error());
            return nullptr;
        }
        set_ok(status);
        return std::move(*result);
    }

    std::unique_ptr<ComputePassEncoder> ce_begin_compute_pass(CommandEncoder &encoder, rust::Str label, RhiStatus &status) {
        const std::string label_storage(label);
        R::ComputePassDesc d{};
        d.label = label_storage.c_str();
        auto result = encoder.begin_compute_pass(d);
        if (!result) {
            set_error(status, result.error());
            return nullptr;
        }
        set_ok(status);
        return std::move(*result);
    }

    void ce_copy_buffer_to_buffer(CommandEncoder &encoder, BufferHandle src, BufferHandle dst, const BufferCopy &region) noexcept {
        R::BufferCopy r{region.src_offset, region.dst_offset, region.size};
        encoder.copy_buffer_to_buffer(to_rhi_handle<R::BufferHandle>(src), to_rhi_handle<R::BufferHandle>(dst), r);
    }

    namespace {
        R::BufferTextureCopy to_rhi(const BufferTextureCopy &c) noexcept {
            R::BufferTextureCopy r{};
            r.buffer_offset = c.buffer_offset;
            r.buffer_row_length = c.buffer_row_length;
            r.buffer_image_height = c.buffer_image_height;
            r.mip_level = c.mip_level;
            r.base_array_layer = c.base_array_layer;
            r.array_layer_count = c.array_layer_count;
            r.texture_offset = {c.offset_x, c.offset_y, c.offset_z};
            r.texture_extent = {c.extent_width, c.extent_height, c.extent_depth_or_layers};
            return r;
        }
    } // namespace

    void ce_copy_buffer_to_texture(CommandEncoder &encoder, BufferHandle src, TextureHandle dst, const BufferTextureCopy &region) noexcept {
        encoder.copy_buffer_to_texture(to_rhi_handle<R::BufferHandle>(src), to_rhi_handle<R::TextureHandle>(dst), to_rhi(region));
    }

    void ce_copy_texture_to_buffer(CommandEncoder &encoder, TextureHandle src, BufferHandle dst, const BufferTextureCopy &region) noexcept {
        encoder.copy_texture_to_buffer(to_rhi_handle<R::TextureHandle>(src), to_rhi_handle<R::BufferHandle>(dst), to_rhi(region));
    }

    void ce_barrier(CommandEncoder &encoder,
                    rust::Slice<const GlobalBarrier> global_barriers,
                    rust::Slice<const BufferBarrier> buffer_barriers,
                    rust::Slice<const TextureBarrier> texture_barriers) noexcept {
        std::vector<R::GlobalBarrier> globals;
        globals.reserve(global_barriers.size());
        for (const auto &b : global_barriers) {
            globals.push_back(R::GlobalBarrier{
                static_cast<R::PipelineStage>(b.src_stage), static_cast<R::AccessFlags>(b.src_access),
                static_cast<R::PipelineStage>(b.dst_stage), static_cast<R::AccessFlags>(b.dst_access)});
        }
        std::vector<R::BufferBarrier> buffers;
        buffers.reserve(buffer_barriers.size());
        for (const auto &b : buffer_barriers) {
            R::BufferBarrier out{};
            out.buffer = to_rhi_handle<R::BufferHandle>(b.buffer);
            out.src_stage = static_cast<R::PipelineStage>(b.src_stage);
            out.src_access = static_cast<R::AccessFlags>(b.src_access);
            out.dst_stage = static_cast<R::PipelineStage>(b.dst_stage);
            out.dst_access = static_cast<R::AccessFlags>(b.dst_access);
            out.ownership = map(b.ownership);
            out.offset = b.offset;
            out.size = b.size;
            buffers.push_back(out);
        }
        std::vector<R::TextureBarrier> textures;
        textures.reserve(texture_barriers.size());
        for (const auto &b : texture_barriers) {
            R::TextureBarrier out{};
            out.texture = to_rhi_handle<R::TextureHandle>(b.texture);
            out.src_stage = static_cast<R::PipelineStage>(b.src_stage);
            out.src_access = static_cast<R::AccessFlags>(b.src_access);
            out.dst_stage = static_cast<R::PipelineStage>(b.dst_stage);
            out.dst_access = static_cast<R::AccessFlags>(b.dst_access);
            out.ownership = map(b.ownership);
            out.old_layout = map(b.old_layout);
            out.new_layout = map(b.new_layout);
            out.range = {b.range.base_mip_level, b.range.mip_level_count, b.range.base_array_layer, b.range.array_layer_count};
            textures.push_back(out);
        }
        encoder.barrier(globals, buffers, textures);
    }

    void ce_fill_buffer(CommandEncoder &encoder, BufferHandle buffer, std::uint64_t offset, std::uint64_t size,
                        std::uint32_t value) noexcept {
        encoder.fill_buffer(to_rhi_handle<R::BufferHandle>(buffer), offset, size, value);
    }

    void ce_update_buffer(CommandEncoder &encoder, BufferHandle buffer, std::uint64_t offset,
                          rust::Slice<const std::uint8_t> data) noexcept {
        encoder.update_buffer(to_rhi_handle<R::BufferHandle>(buffer), offset, as_bytes(data));
    }

    void ce_blit_texture(CommandEncoder &encoder, TextureHandle src, TextureHandle dst, const TextureBlit &region,
                         Filter filter) noexcept {
        R::TextureBlit r{};
        r.src_subresource = {region.src_subresource.mip_level, region.src_subresource.base_array_layer,
                             region.src_subresource.array_layer_count};
        r.src_min = {region.src_min_x, region.src_min_y, region.src_min_z};
        r.src_max = {region.src_max_x, region.src_max_y, region.src_max_z};
        r.dst_subresource = {region.dst_subresource.mip_level, region.dst_subresource.base_array_layer,
                             region.dst_subresource.array_layer_count};
        r.dst_min = {region.dst_min_x, region.dst_min_y, region.dst_min_z};
        r.dst_max = {region.dst_max_x, region.dst_max_y, region.dst_max_z};
        encoder.blit_texture(to_rhi_handle<R::TextureHandle>(src), to_rhi_handle<R::TextureHandle>(dst), r, map(filter));
    }

    void ce_clear_color_texture(CommandEncoder &encoder, TextureHandle texture, const ClearColor &color,
                                const TextureSubresourceRange &range) noexcept {
        R::ClearColor c{color.r, color.g, color.b, color.a};
        R::TextureSubresourceRange r{range.base_mip_level, range.mip_level_count, range.base_array_layer,
                                     range.array_layer_count};
        encoder.clear_color_texture(to_rhi_handle<R::TextureHandle>(texture), c, r);
    }

    void ce_clear_depth_stencil_texture(CommandEncoder &encoder, TextureHandle texture,
                                        const ClearDepthStencilValue &value,
                                        const TextureSubresourceRange &range) noexcept {
        R::ClearDepthStencil v{value.depth, value.stencil};
        R::TextureSubresourceRange r{range.base_mip_level, range.mip_level_count, range.base_array_layer,
                                     range.array_layer_count};
        encoder.clear_depth_stencil_texture(to_rhi_handle<R::TextureHandle>(texture), v, r);
    }

    void ce_build_acceleration_structures(CommandEncoder &encoder, rust::Slice<const AccelerationStructureBuildDesc> builds) {
        // Each build owns its own geometry/range storage until the call returns.
        std::vector<std::vector<R::AccelerationStructureGeometryDesc>> geometries(builds.size());
        std::vector<std::vector<R::AccelerationStructureBuildRangeInfo>> ranges(builds.size());
        std::vector<R::AccelerationStructureBuildDesc> converted;
        converted.reserve(builds.size());
        for (std::size_t i = 0; i < builds.size(); ++i) {
            converted.push_back(to_rhi(builds[i], geometries[i], ranges[i]));
        }
        encoder.build_acceleration_structures(converted);
    }

    void ce_build_opacity_micromaps(CommandEncoder &encoder, rust::Slice<const OpacityMicromapBuildDesc> builds) {
        std::vector<std::vector<R::OpacityMicromapUsageCount>> counts(builds.size());
        std::vector<R::OpacityMicromapBuildDesc> converted;
        converted.reserve(builds.size());
        for (std::size_t i = 0; i < builds.size(); ++i) {
            const auto &b = builds[i];
            counts[i] = to_rhi(b.usage_counts);
            R::OpacityMicromapBuildDesc d{};
            d.dst = to_rhi_handle<R::OpacityMicromapHandle>(b.dst);
            d.scratch_buffer = to_rhi_handle<R::BufferHandle>(b.scratch_buffer);
            d.scratch_offset = b.scratch_offset;
            d.data_buffer = to_rhi_handle<R::BufferHandle>(b.data_buffer);
            d.data_buffer_offset = b.data_buffer_offset;
            d.usage_counts = counts[i];
            converted.push_back(d);
        }
        encoder.build_opacity_micromaps(converted);
    }

    void ce_copy_acceleration_structure(CommandEncoder &encoder, AccelerationStructureHandle src,
                                        AccelerationStructureHandle dst, AccelerationStructureCopyMode mode) noexcept {
        R::AccelerationStructureCopyDesc copy{};
        copy.src = to_rhi_handle<R::AccelerationStructureHandle>(src);
        copy.dst = to_rhi_handle<R::AccelerationStructureHandle>(dst);
        copy.mode = map(mode);
        encoder.copy_acceleration_structure(copy);
    }

    void ce_set_ray_tracing_pipeline(CommandEncoder &encoder, RayTracingPipelineHandle pipeline) noexcept {
        encoder.set_ray_tracing_pipeline(to_rhi_handle<R::RayTracingPipelineHandle>(pipeline));
    }

    void ce_trace_rays(CommandEncoder &encoder, const TraceRaysDesc &desc) noexcept {
        auto region = [](const ShaderBindingTableRegion &r) {
            return R::ShaderBindingTableRegion{to_rhi_handle<R::BufferHandle>(r.buffer), r.offset, r.size, r.stride};
        };
        R::TraceRaysDesc d{};
        d.raygen = region(desc.raygen);
        d.miss = region(desc.miss);
        d.hit = region(desc.hit);
        d.callable = region(desc.callable);
        d.width = desc.width;
        d.height = desc.height;
        d.depth = desc.depth;
        encoder.trace_rays(d);
    }

    void ce_reset_query_set(CommandEncoder &encoder, QuerySetHandle query_set, std::uint32_t first, std::uint32_t count) noexcept {
        encoder.reset_query_set(to_rhi_handle<R::QuerySetHandle>(query_set), first, count);
    }

    void ce_write_timestamp(CommandEncoder &encoder, std::uint64_t stage, QuerySetHandle query_set, std::uint32_t index) noexcept {
        encoder.write_timestamp(static_cast<R::PipelineStage>(stage), to_rhi_handle<R::QuerySetHandle>(query_set), index);
    }

    void ce_begin_pipeline_statistics_query(CommandEncoder &encoder, QuerySetHandle query_set, std::uint32_t index) noexcept {
        encoder.begin_pipeline_statistics_query(to_rhi_handle<R::QuerySetHandle>(query_set), index);
    }

    void ce_end_pipeline_statistics_query(CommandEncoder &encoder) noexcept {
        encoder.end_pipeline_statistics_query();
    }

    void ce_resolve_query_set(CommandEncoder &encoder, QuerySetHandle query_set, std::uint32_t first, std::uint32_t count,
                              BufferHandle dst, std::uint64_t dst_offset, std::uint64_t stride, std::uint32_t flags) noexcept {
        encoder.resolve_query_set(to_rhi_handle<R::QuerySetHandle>(query_set), first, count,
                                  to_rhi_handle<R::BufferHandle>(dst), dst_offset, stride,
                                  static_cast<R::QueryResultFlags>(flags));
    }

    void ce_push_debug_group(CommandEncoder &encoder, rust::Str label) noexcept {
        const std::string s(label);
        encoder.push_debug_group(s.c_str());
    }

    void ce_pop_debug_group(CommandEncoder &encoder) noexcept {
        encoder.pop_debug_group();
    }

    CommandBufferHandle ce_finish(CommandEncoder &encoder, RhiStatus &status) {
        return unwrap_handle<CommandBufferHandle>(encoder.finish(), status);
    }

    // ─── Render pass ──────────────────────────────────────────────────────────────

    void rp_set_pipeline(RenderPassEncoder &rp, RenderPipelineHandle pipeline) noexcept {
        rp.set_pipeline(to_rhi_handle<R::RenderPipelineHandle>(pipeline));
    }

    void rp_set_bind_group(RenderPassEncoder &rp, std::uint32_t index, BindGroupHandle bind_group,
                           rust::Slice<const std::uint32_t> dynamic_offsets) noexcept {
        rp.set_bind_group(index, to_rhi_handle<R::BindGroupHandle>(bind_group),
                          std::span<const std::uint32_t>(dynamic_offsets.data(), dynamic_offsets.size()));
    }

    void rp_set_vertex_buffer(RenderPassEncoder &rp, std::uint32_t slot, BufferHandle buffer, std::uint64_t offset) noexcept {
        rp.set_vertex_buffer(slot, to_rhi_handle<R::BufferHandle>(buffer), offset);
    }

    void rp_set_index_buffer(RenderPassEncoder &rp, BufferHandle buffer, IndexFormat format, std::uint64_t offset) noexcept {
        rp.set_index_buffer(to_rhi_handle<R::BufferHandle>(buffer), map(format), offset);
    }

    void rp_set_push_constants(RenderPassEncoder &rp, std::uint32_t stages, std::uint32_t offset,
                               rust::Slice<const std::uint8_t> data) noexcept {
        rp.set_push_constants(static_cast<R::ShaderStage>(stages), offset, as_bytes(data));
    }

    void rp_set_viewport(RenderPassEncoder &rp, const Viewport &viewport) noexcept {
        rp.set_viewport(R::Viewport{viewport.x, viewport.y, viewport.width, viewport.height, viewport.min_depth, viewport.max_depth});
    }

    void rp_set_scissor(RenderPassEncoder &rp, const Rect2D &scissor) noexcept {
        rp.set_scissor(R::Rect2D{scissor.x, scissor.y, scissor.width, scissor.height});
    }

    void rp_set_blend_constant(RenderPassEncoder &rp, const ClearColor &color) noexcept {
        rp.set_blend_constant(R::ClearColor{color.r, color.g, color.b, color.a});
    }

    void rp_set_stencil_reference(RenderPassEncoder &rp, std::uint32_t reference) noexcept {
        rp.set_stencil_reference(reference);
    }

    void rp_set_depth_bounds(RenderPassEncoder &rp, float min_depth, float max_depth) noexcept {
        rp.set_depth_bounds(min_depth, max_depth);
    }

    void rp_set_sample_locations(RenderPassEncoder &rp, std::uint32_t samples_per_pixel, std::uint32_t grid_width,
                                 std::uint32_t grid_height, rust::Slice<const SampleLocation> locations) noexcept {
        rp.set_sample_locations(samples_per_pixel, R::Extent2D{grid_width, grid_height}, to_rhi(locations));
    }

    void rp_set_shading_rate(RenderPassEncoder &rp, ShadingRate rate, ShadingRateCombiner primitive_combiner,
                             ShadingRateCombiner attachment_combiner) noexcept {
        rp.set_shading_rate(map(rate), map(primitive_combiner), map(attachment_combiner));
    }

    void rp_draw_mesh_tasks(RenderPassEncoder &rp, const DrawMeshTasksArgs &args) noexcept {
        rp.draw_mesh_tasks(R::DrawMeshTasksArgs{args.group_count_x, args.group_count_y, args.group_count_z});
    }

    void rp_draw_mesh_tasks_indirect(RenderPassEncoder &rp, BufferHandle indirect_buffer, std::uint64_t offset) noexcept {
        rp.draw_mesh_tasks_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset);
    }

    void rp_draw_mesh_tasks_indirect_count(RenderPassEncoder &rp, BufferHandle indirect_buffer,
                                           std::uint64_t indirect_offset, BufferHandle count_buffer,
                                           std::uint64_t count_offset, std::uint32_t max_draws,
                                           std::uint32_t stride) noexcept {
        rp.draw_mesh_tasks_indirect_count(to_rhi_handle<R::BufferHandle>(indirect_buffer), indirect_offset,
                                          to_rhi_handle<R::BufferHandle>(count_buffer), count_offset, max_draws, stride);
    }

    void rp_execute_bundles(RenderPassEncoder &rp, rust::Slice<const RenderBundleHandle> bundles) noexcept {
        std::vector<R::RenderBundleHandle> converted;
        converted.reserve(bundles.size());
        for (const RenderBundleHandle &bundle : bundles) {
            converted.push_back(to_rhi_handle<R::RenderBundleHandle>(bundle));
        }
        rp.execute_bundles(converted);
    }

    void rp_draw(RenderPassEncoder &rp, const DrawArgs &args) noexcept {
        rp.draw(R::DrawArgs{args.vertex_count, args.instance_count, args.first_vertex, args.first_instance});
    }

    void rp_draw_indexed(RenderPassEncoder &rp, const DrawIndexedArgs &args) noexcept {
        rp.draw_indexed(R::DrawIndexedArgs{
            args.index_count, args.instance_count, args.first_index, args.base_vertex, args.first_instance});
    }

    void rp_draw_indirect(RenderPassEncoder &rp, BufferHandle indirect_buffer, std::uint64_t offset) noexcept {
        rp.draw_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset);
    }

    void rp_draw_indexed_indirect(RenderPassEncoder &rp, BufferHandle indirect_buffer, std::uint64_t offset) noexcept {
        rp.draw_indexed_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset);
    }

    void rp_draw_indirect_multi(RenderPassEncoder &rp, BufferHandle indirect_buffer, std::uint64_t offset,
                                std::uint32_t draw_count, std::uint32_t stride) noexcept {
        rp.draw_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset, draw_count, stride);
    }

    void rp_draw_indexed_indirect_multi(RenderPassEncoder &rp, BufferHandle indirect_buffer, std::uint64_t offset,
                                        std::uint32_t draw_count, std::uint32_t stride) noexcept {
        rp.draw_indexed_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset, draw_count, stride);
    }

    void rp_draw_indirect_count(RenderPassEncoder &rp, BufferHandle indirect_buffer, std::uint64_t indirect_offset,
                                BufferHandle count_buffer, std::uint64_t count_offset, std::uint32_t max_draws,
                                std::uint32_t stride) noexcept {
        rp.draw_indirect_count(to_rhi_handle<R::BufferHandle>(indirect_buffer), indirect_offset,
                               to_rhi_handle<R::BufferHandle>(count_buffer), count_offset, max_draws, stride);
    }

    void rp_draw_indexed_indirect_count(RenderPassEncoder &rp, BufferHandle indirect_buffer, std::uint64_t indirect_offset,
                                        BufferHandle count_buffer, std::uint64_t count_offset, std::uint32_t max_draws,
                                        std::uint32_t stride) noexcept {
        rp.draw_indexed_indirect_count(to_rhi_handle<R::BufferHandle>(indirect_buffer), indirect_offset,
                                       to_rhi_handle<R::BufferHandle>(count_buffer), count_offset, max_draws, stride);
    }

    void rp_begin_occlusion_query(RenderPassEncoder &rp, QuerySetHandle query_set, std::uint32_t index) noexcept {
        rp.begin_occlusion_query(to_rhi_handle<R::QuerySetHandle>(query_set), index);
    }

    void rp_end_occlusion_query(RenderPassEncoder &rp) noexcept {
        rp.end_occlusion_query();
    }

    void rp_end(RenderPassEncoder &rp) noexcept {
        rp.end();
    }

    // ─── Compute pass ─────────────────────────────────────────────────────────────

    void cp_set_pipeline(ComputePassEncoder &cp, ComputePipelineHandle pipeline) noexcept {
        cp.set_pipeline(to_rhi_handle<R::ComputePipelineHandle>(pipeline));
    }

    void cp_set_bind_group(ComputePassEncoder &cp, std::uint32_t index, BindGroupHandle bind_group,
                           rust::Slice<const std::uint32_t> dynamic_offsets) noexcept {
        cp.set_bind_group(index, to_rhi_handle<R::BindGroupHandle>(bind_group),
                          std::span<const std::uint32_t>(dynamic_offsets.data(), dynamic_offsets.size()));
    }

    void cp_set_push_constants(ComputePassEncoder &cp, std::uint32_t stages, std::uint32_t offset,
                               rust::Slice<const std::uint8_t> data) noexcept {
        cp.set_push_constants(static_cast<R::ShaderStage>(stages), offset, as_bytes(data));
    }

    void cp_dispatch(ComputePassEncoder &cp, std::uint32_t group_count_x, std::uint32_t group_count_y,
                     std::uint32_t group_count_z) noexcept {
        cp.dispatch(group_count_x, group_count_y, group_count_z);
    }

    void cp_dispatch_indirect(ComputePassEncoder &cp, BufferHandle indirect_buffer, std::uint64_t offset) noexcept {
        cp.dispatch_indirect(to_rhi_handle<R::BufferHandle>(indirect_buffer), offset);
    }

    void cp_end(ComputePassEncoder &cp) noexcept {
        cp.end();
    }

} // namespace sturdy_rs::rhi
