#include "sturdy_rs/schedule.hpp"

#include <cstdint>
#include <cstring>
#include <vector>

#include <Ecs/System.hpp>
#include <Ecs/World.hpp>
#include <Engine/Engine.hpp>
#include <Foundation/Foundation.hpp>

// Generated by build.rs from src/schedule.rs; defines the shared structs/enums this file returns,
// and the extern "Rust" trampoline targets (`rust_entity_system_run`/`rust_global_system_run`).
#include "sturdy_rs/schedule_bridge.h"

namespace sturdy_rs::schedule {
    namespace {

        namespace WE = SFT::Ecs;

        rust::String to_rust_string(std::string_view text) {
            return rust::String(text.data(), text.size());
        }

        EcsStatus ok_status() noexcept {
            return EcsStatus{true, ecs::EcsErrorCode::InvalidArgument, rust::String()};
        }

        EcsStatus fail_status(ecs::EcsErrorCode code, std::string_view message) {
            return EcsStatus{false, code, to_rust_string(message)};
        }

        /// Same conversion as `ecs.cpp`'s own (private, anonymous-namespace) `to_engine_entity` —
        /// duplicated rather than shared since that one isn't exposed outside its translation unit.
        WE::Entity to_engine_entity(EntityId entity) noexcept {
            return WE::Entity{.index = entity.index, .generation = entity.generation};
        }

        WE::Schedule &resolve_schedule(EngineView &engine, ScheduleTarget target) noexcept {
            return target == ScheduleTarget::RenderExtraction ? engine.render_extraction_schedule()
                                                               : engine.update_schedule();
        }

        /// Resolves `ids` into `SystemAccess`-shaped `ComponentKey`s, validating each is actually
        /// registered along the way. Shared by the `reads`/`writes` halves of `SystemAccessSpec`.
        [[nodiscard]] bool resolve_component_keys(const WE::World &world,
                                                  rust::Slice<const std::uint32_t> ids,
                                                  std::vector<WE::ComponentKey> &out,
                                                  EcsStatus &error) {
            out.reserve(out.size() + ids.size());
            for (std::uint32_t id : ids) {
                const WE::ComponentInfo *descriptor = world.registry().info(id);
                if (descriptor == nullptr) {
                    error = fail_status(ecs::EcsErrorCode::UnknownComponent,
                                        "no component is registered under one of the declared access ids");
                    return false;
                }
                out.push_back(descriptor->key);
            }
            return true;
        }

        [[nodiscard]] bool build_system_access(const WE::World &world,
                                               const SystemAccessSpec &spec,
                                               WE::SystemAccess &out,
                                               EcsStatus &error) {
            if (!resolve_component_keys(world, rust::Slice<const std::uint32_t>{spec.reads.data(), spec.reads.size()},
                                        out.reads, error))
                return false;
            if (!resolve_component_keys(world,
                                        rust::Slice<const std::uint32_t>{spec.writes.data(), spec.writes.size()},
                                        out.writes, error))
                return false;
            for (std::size_t i = 0; i < spec.resource_reads_high.size(); ++i) {
                out.resource_reads.push_back(
                    WE::ResourceKey{.high = spec.resource_reads_high[i], .low = spec.resource_reads_low[i]});
            }
            for (std::size_t i = 0; i < spec.resource_writes_high.size(); ++i) {
                out.resource_writes.push_back(
                    WE::ResourceKey{.high = spec.resource_writes_high[i], .low = spec.resource_writes_low[i]});
            }
            return true;
        }

        // ─── Per-entity systems ─────────────────────────────────────────────────────────────────

        /// Leaked alongside its `RustEntitySystem*` (see schedule.rs's module doc): `Schedule` never
        /// gives up a registered system, so nothing here is ever freed.
        struct RegisteredEntitySystem {
            RustEntitySystem *rust_system;
        };

        void entity_system_trampoline(WE::Entity entity, void **components, void *dispatch_context,
                                      void *user_data) noexcept {
            auto *registered = static_cast<RegisteredEntitySystem *>(user_data);
            EntityId bridge_entity{entity.index, entity.generation};
            rust_entity_system_run(registered->rust_system, bridge_entity,
                                   reinterpret_cast<std::uint8_t **>(components),
                                   static_cast<Commands *>(dispatch_context));
        }

        // ─── Global systems ─────────────────────────────────────────────────────────────────────

        /// Leaked alongside its `RustGlobalSystem*`. `world` is `EngineView::ecs_world()`'s address,
        /// stable for the engine's lifetime (the same assumption `ecs.cpp`'s `g_owned`/`g_events`
        /// maps already make of the same pointer) — captured once here so the trampoline, which
        /// `ErasedSystemFn` gives no `World&` to, can still resolve resource pointers fresh on every
        /// dispatch. See schedule.rs's module doc for why this is safe only because the trampoline
        /// runs synchronously inside `Schedule::run`'s own call stack.
        struct RegisteredGlobalSystem {
            WE::World *world;
            std::vector<WE::ResourceKey> resource_reads;
            std::vector<WE::ResourceKey> resource_writes;
            RustGlobalSystem *rust_system;
        };

        void global_system_trampoline(WE::Entity, void **, void *dispatch_context, void *user_data) noexcept {
            auto *registered = static_cast<RegisteredGlobalSystem *>(user_data);
            std::vector<std::uint8_t *> pointers;
            pointers.reserve(registered->resource_reads.size() + registered->resource_writes.size());
            for (WE::ResourceKey key : registered->resource_reads) {
                SFT::usize size = 0;
                pointers.push_back(static_cast<std::uint8_t *>(registered->world->resource_pointer_erased(key, &size)));
            }
            for (WE::ResourceKey key : registered->resource_writes) {
                SFT::usize size = 0;
                pointers.push_back(static_cast<std::uint8_t *>(registered->world->resource_pointer_erased(key, &size)));
            }
            rust_global_system_run(registered->rust_system, pointers.data(), pointers.size(),
                                   static_cast<Commands *>(dispatch_context));
        }

        // ─── Commands (deferred spawn/despawn/add/remove-component) ───────────────────────────────
        //
        // `prepare` mints this dispatch's `Commands` handle once, before any entity is visited (or
        // once for a global system's single dispatch); the engine hands the very same pointer back
        // as `dispatch_context` to every trampoline call for that dispatch, which is exactly what
        // gets forwarded to Rust above. No `finish` callback is needed: `Commands` itself has
        // nothing to tear down (it's a thin, non-owning view over the schedule's own
        // `Detail::CommandBuffer`, which the engine applies and destroys on its own after
        // `Schedule::run` finishes with every system in it).
        void *commands_prepare_trampoline(Commands *commands, void *) noexcept {
            return static_cast<void *>(commands);
        }

    } // namespace

    void commands_spawn(Commands *commands, rust::Slice<const std::uint32_t> component_ids,
                        rust::Slice<const std::uint32_t> sizes, rust::Slice<const std::uint8_t> data) {
        if (commands == nullptr || component_ids.size() != sizes.size()) {
            return;
        }
        std::vector<WE::ComponentId> ids(component_ids.begin(), component_ids.end());
        std::vector<SFT::usize> byte_sizes(sizes.begin(), sizes.end());
        std::vector<const void *> pointers;
        pointers.reserve(ids.size());
        std::size_t offset = 0;
        for (std::size_t i = 0; i < ids.size(); ++i) {
            if (offset + byte_sizes[i] > data.size()) {
                return; // malformed: declared sizes overrun the supplied data
            }
            pointers.push_back(data.data() + offset);
            offset += byte_sizes[i];
        }
        commands->spawn_erased(ids, pointers, byte_sizes);
    }

    void commands_add_component(Commands *commands, EntityId entity, std::uint32_t component,
                                rust::Slice<const std::uint8_t> data) {
        if (commands == nullptr) {
            return;
        }
        commands->add_component_erased(to_engine_entity(entity), component, data.data(), data.size());
    }

    void commands_remove_component(Commands *commands, EntityId entity, std::uint32_t component) {
        if (commands == nullptr) {
            return;
        }
        commands->remove_component_erased(to_engine_entity(entity), component);
    }

    void commands_destroy(Commands *commands, EntityId entity) {
        if (commands == nullptr) {
            return;
        }
        commands->destroy(to_engine_entity(entity));
    }

    EcsStatus schedule_add_entity_system(EngineView &engine,
                                         ScheduleTarget target,
                                         const SystemAccessSpec &access,
                                         rust::Slice<const std::uint32_t> component_ids,
                                         RustEntitySystem *system) {
        WE::World &world = engine.ecs_world();
        WE::SystemAccess system_access;
        EcsStatus error{};
        if (!build_system_access(world, access, system_access, error)) {
            return error;
        }
        std::vector<WE::ComponentId> ids;
        std::vector<WE::ComponentKey> visit_keys; // only used to validate; discarded after.
        if (!resolve_component_keys(world, component_ids, visit_keys, error)) {
            return error;
        }
        ids.assign(component_ids.begin(), component_ids.end());

        // Leaked on purpose, exactly like `RegisteredSystem` in FFI/src/FFI/EcsSystems.cpp: a
        // system lives for the life of the schedule, and the schedule for the life of the engine.
        auto *registered = new RegisteredEntitySystem{system};
        resolve_schedule(engine, target)
            .add_erased_system(std::move(system_access), std::move(ids), &entity_system_trampoline, registered,
                              &commands_prepare_trampoline, nullptr);
        return ok_status();
    }

    EcsStatus schedule_add_global_system(EngineView &engine,
                                         ScheduleTarget target,
                                         const SystemAccessSpec &access,
                                         RustGlobalSystem *system) {
        WE::World &world = engine.ecs_world();
        WE::SystemAccess system_access;
        EcsStatus error{};
        if (!build_system_access(world, access, system_access, error)) {
            return error;
        }

        // Leaked on purpose; see RegisteredEntitySystem above.
        auto *registered = new RegisteredGlobalSystem{&world, system_access.resource_reads,
                                                       system_access.resource_writes, system};
        resolve_schedule(engine, target)
            .add_erased_global_system(std::move(system_access), &global_system_trampoline, registered,
                                      &commands_prepare_trampoline, nullptr);
        return ok_status();
    }

} // namespace sturdy_rs::schedule
