#include "sturdy_rs/shader_compiler.hpp"

#include <string>
#include <vector>

#include <Core/Slang/Shader.hpp>

// Generated by build.rs from src/shader_compiler.rs; defines the shared structs/enums declared
// in shader_compiler.hpp.
#include "sturdy_rs/shader_compiler_bridge.h"

namespace sturdy_rs::shader_compiler {
    namespace {

        namespace S = SFT::Core::Slang;

        S::ShaderStage map(ShaderStage stage) noexcept {
            switch (stage) {
            case ShaderStage::Vertex: return S::ShaderStage::Vertex;
            case ShaderStage::Fragment: return S::ShaderStage::Fragment;
            case ShaderStage::Compute: return S::ShaderStage::Compute;
            }
            return S::ShaderStage::Unknown;
        }

        rust::String to_rust_string(const std::string &text) {
            return rust::String::lossy(text);
        }

        /// Combines a `ShaderError`'s message and (if present) its compiler diagnostics into one
        /// human-readable string for `ShaderCompileResult::error`.
        rust::String describe(const S::ShaderError &error) {
            if (error.diagnostics.empty()) {
                return to_rust_string(error.message);
            }
            return to_rust_string(error.message + "\n" + error.diagnostics);
        }

    } // namespace

    ShaderCompileResult compile_slang_spirv(rust::Str source, rust::Str module_name,
                                            rust::Slice<const EntryPointRequest> entry_points) {
        ShaderCompileResult result{};

        S::ShaderSource shader_source =
            S::ShaderSource::from_source(std::string(module_name), std::string(source));

        S::ShaderCompileOptions options{};
        options.entry_points.reserve(entry_points.size());
        for (const EntryPointRequest &request : entry_points) {
            options.entry_points.push_back(
                S::ShaderEntryPointRequest{std::string(request.name), map(request.stage)});
        }

        S::ShaderCompiler compiler;
        S::ShaderExpected<S::Shader> compiled = compiler.compile(shader_source, options);
        if (!compiled) {
            result.error = describe(compiled.error());
            return result;
        }

        result.entry_points.reserve(entry_points.size());
        for (std::size_t i = 0; i < entry_points.size(); ++i) {
            S::ShaderExpected<S::ShaderBytecode> code = compiled->entry_point_code(i);
            if (!code) {
                result.ok = false;
                result.error = describe(code.error());
                result.entry_points.clear();
                return result;
            }
            CompiledEntryPoint out{};
            out.bytes.reserve(code->bytes.size());
            for (std::byte byte : code->bytes) {
                out.bytes.push_back(static_cast<std::uint8_t>(byte));
            }
            result.entry_points.push_back(std::move(out));
        }

        result.ok = true;
        return result;
    }

} // namespace sturdy_rs::shader_compiler
