#include "sturdy_rs/shim.hpp"

#include <memory>
#include <optional>
#include <string>
#include <utility>

#include <Runtime/Runtime.hpp>

// For render_graph_from_settings(), which turns a request's RenderGraphSettings (reused from this
// bridge into the root one, see lib.rs) into a real Engine::RenderGraph for this frame.
#include "sturdy_rs/render.hpp"

// For ui_run_frame()/ui_take_pending_overlay_hooks(), which build this frame's UI overlay from
// whatever draw hook `sturdy_rs::ui::ui_set_draw_hook` registered and attach it below.
#include "sturdy_rs/ui.hpp"

// Generated by build.rs from src/lib.rs; defines the shared structs/enums and the Rust callbacks.
#include "sturdy_rs/bridge.h"

namespace sturdy_rs {
    namespace {

        namespace E = SFT::Engine;
        namespace W = SFT::WindowManager;
        namespace C = SFT::Core;

        // The engine's factory is a bare function pointer (`unique_ptr<GameLogic>(*)()`), so the
        // Rust logic is handed over through this slot. run_runtime fills it immediately before
        // Runtime::run, and the factory drains it; only one runtime may run per process.
        std::optional<rust::Box<LogicHandle>> g_pending_logic;

        UString to_ustring(const rust::String &text) {
            const std::string_view view{text.data(), text.size()};
            if (auto converted = UString::try_from_utf8(view)) {
                return std::move(*converted);
            }
            return UString{};
        }

        E::Camera build_camera(const CameraDesc &d) {
            E::Camera camera = d.projection == CameraProjection::Orthographic
                                   ? E::Camera::orthographic(d.orthographic_size, d.aspect_ratio, d.near_clip, d.far_clip)
                                   : E::Camera::perspective(d.vertical_fov_degrees, d.aspect_ratio, d.near_clip, d.far_clip);
            camera.set_position({d.position[0], d.position[1], d.position[2]});
            camera.set_euler_degrees({d.euler_degrees[0], d.euler_degrees[1], d.euler_degrees[2]});
            return camera;
        }

        E::SceneLighting build_lighting(const SceneLightingDesc &d) {
            E::SceneLighting lighting{};
            lighting.ambient_radiance = {d.ambient_radiance[0], d.ambient_radiance[1], d.ambient_radiance[2]};
            lighting.exposure = d.exposure;
            return lighting;
        }

        class RustGameLogic final : public E::GameLogic {
          public:
            explicit RustGameLogic(rust::Box<LogicHandle> logic) : logic_(std::move(logic)) {
            }

            E::GameLogicResult on_engine_initialized(E::Engine &engine) override {
                Status status = logic_on_init(*logic_, engine);
                if (status.ok) {
                    return {};
                }
                return std::unexpected(E::GameLogicError{to_ustring(status.message)});
            }

            std::optional<E::RenderFrameParameters> request_render_frame(
                E::Engine &engine,
                C::RenderSurfaceHandle surface,
                const C::FrameInput &frame) override {
                const FrameInfo info{
                    .delta_seconds = frame.delta_seconds,
                    .frame_index = frame.frame_index,
                    .framebuffer_width = frame.framebuffer_width,
                    .framebuffer_height = frame.framebuffer_height,
                    .live_resize = frame.live_resize,
                    .window_id = static_cast<std::uint64_t>(surface.window_id),
                };
                FrameRequest request = logic_request_frame(*logic_, engine, info);
                if (!request.present) {
                    return std::nullopt;
                }
                E::RenderFrameParameters params{};
                params.camera = build_camera(request.camera);
                params.lighting = build_lighting(request.lighting);
                params.debug_label = to_ustring(request.debug_label);
                params.render_graph = sturdy_rs::render::consume_pending_render_graph();

                // Builds this frame's UI overlay (a no-op if no draw hook is registered / the UI
                // renderer isn't ready yet) and attaches whatever it produced. See ui.rs's module
                // doc comment: this is the "remaining integration step" that doc used to describe as
                // future work -- it now lives here, right where a hand-written C++ caller would put
                // the `sturdy_ui_begin`/`sturdy_ui_end` pair FFI/Ui.cpp documents.
                if (sturdy_rs::ui::ui_run_frame(engine, frame.framebuffer_width, frame.framebuffer_height,
                                                frame.delta_seconds)) {
                    if (auto overlay = sturdy_rs::ui::ui_take_pending_overlay_hooks()) {
                        params.ui_overlay = std::move(*overlay);
                    }
                }
                return params;
            }

            void on_shutdown(E::Engine &engine) noexcept override {
                logic_on_shutdown(*logic_, engine);
            }

          private:
            rust::Box<LogicHandle> logic_;
        };

        std::unique_ptr<E::GameLogic> make_logic() {
            auto logic = std::move(*g_pending_logic);
            g_pending_logic.reset();
            return std::make_unique<RustGameLogic>(std::move(logic));
        }

        SFT::Core::VSyncMode map(VSync v) {
            switch (v) {
            case VSync::Off: return C::VSyncMode::Off;
            case VSync::On: return C::VSyncMode::On;
            case VSync::Adaptive: return C::VSyncMode::Adaptive;
            }
            return C::VSyncMode::On;
        }

        C::VariableRefreshMode map(VariableRefresh v) {
            switch (v) {
            case VariableRefresh::Disabled: return C::VariableRefreshMode::Disabled;
            case VariableRefresh::Automatic: return C::VariableRefreshMode::Automatic;
            case VariableRefresh::Preferred: return C::VariableRefreshMode::Preferred;
            }
            return C::VariableRefreshMode::Automatic;
        }

        C::LatencyMode map(LatencyMode v) {
            switch (v) {
            case LatencyMode::Normal: return C::LatencyMode::Normal;
            case LatencyMode::Low: return C::LatencyMode::Low;
            case LatencyMode::Ultra: return C::LatencyMode::Ultra;
            }
            return C::LatencyMode::Normal;
        }

        C::PresentationPreference map(PresentationPreference v) {
            switch (v) {
            case PresentationPreference::Automatic: return C::PresentationPreference::Automatic;
            case PresentationPreference::LowestLatency: return C::PresentationPreference::LowestLatency;
            case PresentationPreference::Smoothest: return C::PresentationPreference::Smoothest;
            case PresentationPreference::PowerEfficient: return C::PresentationPreference::PowerEfficient;
            }
            return C::PresentationPreference::Automatic;
        }

        W::WindowMode map(WindowMode v) {
            switch (v) {
            case WindowMode::Windowed: return W::WindowMode::Windowed;
            case WindowMode::BorderlessFullscreen: return W::WindowMode::BorderlessFullscreen;
            case WindowMode::ExclusiveFullscreen: return W::WindowMode::ExclusiveFullscreen;
            }
            return W::WindowMode::Windowed;
        }

        // The Rust `Key` enum mirrors these numerically; catch drift at compile time.
        static_assert(static_cast<int>(W::KeyboardKey::Escape) == 0x100);
        static_assert(static_cast<int>(W::KeyboardKey::F1) == 0x200);
        static_assert(static_cast<int>(W::KeyboardKey::Numpad0) == 0x300);
        static_assert(static_cast<int>(W::KeyboardKey::VolumeUp) == 0x400);

        W::KeyboardKey key(std::int32_t k) noexcept {
            return static_cast<W::KeyboardKey>(k);
        }
        W::MouseButton button(std::uint8_t b) noexcept {
            return static_cast<W::MouseButton>(b);
        }

    } // namespace

    std::int32_t run_runtime(const RuntimeOptions &options,
                             const rust::Vec<rust::String> &args,
                             rust::Box<LogicHandle> logic) {
        // Strings referenced by pointer inside the engine config must outlive Runtime::run.
        const std::string window_title{options.window_title};
        const std::string app_name{options.app_name};

        SFT::Runtime::RuntimeConfig config{};
        auto &app = config.application;
        app.primary_window.title = window_title.c_str();
        app.primary_window.extent = {options.width, options.height};
        app.primary_window.resizable = options.resizable;
        app.primary_window.decorated = options.decorated;
        app.primary_window.high_dpi = options.high_dpi;
        app.primary_window.mode = map(options.window_mode);
        app.primary_window.graphics_api = W::WindowGraphicsApi::Vulkan;
        app.enable_runtime_window_management = options.runtime_window_management;
        if (options.title_update_interval_seconds > 0.0) {
            app.primary_window_title_update_interval_seconds = options.title_update_interval_seconds;
        }
        app.engine.app_name = app_name.c_str();
        app.engine.shaders_directory = std::string{options.shaders_directory};
        app.engine.features.raytracing = options.raytracing;
        auto &presentation = app.engine.features.presentation;
        presentation.vsync = map(options.vsync);
        presentation.variable_refresh = map(options.variable_refresh);
        presentation.latency = map(options.latency);
        presentation.preference = map(options.preference);
        config.primary_window_title = to_ustring(options.window_title);

        SFT::Foundation::CliArgs cli;
        cli.reserve(args.size());
        for (const auto &arg : args) {
            cli.emplace_back(arg.data(), arg.size());
        }

        g_pending_logic.emplace(std::move(logic));
        const auto exit_code = SFT::Runtime::run(cli, std::move(config), &make_logic);
        g_pending_logic.reset();
        return static_cast<std::int32_t>(exit_code);
    }

    double engine_delta_seconds(const EngineView &e) noexcept { return e.frame_time().delta_seconds(); }
    double engine_unscaled_delta_seconds(const EngineView &e) noexcept { return e.frame_time().unscaled_delta_seconds(); }
    std::uint64_t engine_tick_index(const EngineView &e) noexcept { return e.frame_time().tick_index(); }
    double engine_time_scale(const EngineView &e) noexcept { return e.time_scale().value(); }
    void engine_set_time_scale(EngineView &e, double scale) noexcept { e.time_scale().set(scale); }

    bool engine_gpu_description(const EngineView &e, GpuDescription &out) {
        const auto info = e.gpu_info();
        if (!info) {
            return false;
        }
        out.name = rust::String::lossy(info->name);
        out.vendor = rust::String::lossy(info->vendor);
        out.driver_version = rust::String::lossy(info->driver_version);
        out.api_version = rust::String::lossy(info->api_version);
        out.device_type = rust::String::lossy(info->device_type);
        out.vendor_id = info->vendor_id;
        out.device_id = info->device_id;
        return true;
    }

    bool input_key_down(const EngineView &e, std::int32_t k) noexcept { return e.input_state().key_down(key(k)); }
    bool input_key_just_pressed(const EngineView &e, std::int32_t k) noexcept { return e.input_state().key_just_pressed(key(k)); }
    bool input_key_just_released(const EngineView &e, std::int32_t k) noexcept { return e.input_state().key_just_released(key(k)); }
    bool input_mouse_down(const EngineView &e, std::uint8_t b) noexcept { return e.input_state().mouse_down(button(b)); }
    bool input_mouse_just_pressed(const EngineView &e, std::uint8_t b) noexcept { return e.input_state().mouse_just_pressed(button(b)); }
    bool input_mouse_just_released(const EngineView &e, std::uint8_t b) noexcept { return e.input_state().mouse_just_released(button(b)); }
    std::array<float, 2> input_mouse_position(const EngineView &e) noexcept { return {e.input_state().mouse_x(), e.input_state().mouse_y()}; }
    std::array<float, 2> input_mouse_delta(const EngineView &e) noexcept { return {e.input_state().mouse_delta_x(), e.input_state().mouse_delta_y()}; }
    std::array<float, 2> input_wheel_delta(const EngineView &e) noexcept { return {e.input_state().wheel_delta_x(), e.input_state().wheel_delta_y()}; }

    rust::String input_text_this_tick(const EngineView &e) {
        const auto text = e.input_state().text_this_tick();
        return rust::String::lossy(text.data(), text.size());
    }

} // namespace sturdy_rs
