#include "sturdy_rs/ui.hpp"

#include <algorithm>
#include <exception>
#include <filesystem>
#include <memory>
#include <mutex>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <glm/vec2.hpp>

#include <Foundation/Foundation.hpp>
#include <RHI/RHI.hpp>

#include <Engine/Engine.hpp>
#include <Renderer/Text/Font.hpp>
#include <Renderer/UI/TextEdit.hpp>
#include <Renderer/UI/Graph.hpp>
#include <Renderer/UI/UI.hpp>

// Generated by build.rs from src/ui.rs; defines the shared structs and the Rust callback
// (`ui_invoke_draw_hook`).
#include "sturdy_rs/ui_bridge.h"

namespace sturdy_rs::ui {
    namespace {

        namespace E = SFT::Engine;

        /// The UI frame currently being built, if any. Mirrors `FFI/src/FFI/Ui.cpp`'s `UiSession`
        /// (see that file's doc comment for why this is thread-local: a layout pass belongs to
        /// whichever thread is building it).
        struct UiSession {
            bool open = false;
            SFT::UI::Context *context = nullptr;
            glm::vec2 viewport{0.0f, 0.0f};
            /// Open element scopes, innermost last. Held by pointer because `ElementScope` closes
            /// its element on destruction and must not be moved or copied out from under the layout.
            std::vector<std::unique_ptr<SFT::UI::ElementScope>> open_elements;
        };

        thread_local UiSession g_session;

        /// The registered per-frame draw closure. Not thread-local: installed once (typically from
        /// the thread that owns the window/engine) and invoked from `ui_run_frame` on that same
        /// thread, same rationale `run_runtime`'s `g_pending_logic` documents in shim.cpp.
        std::optional<rust::Box<UiDrawHandle>> g_draw_hook;

        /// A font loaded through `ui_register_font`, kept alongside the id it was registered under.
        /// See `FFI/src/FFI/Ui.cpp`'s `FontRegistration` -- same rationale: `Context::register_font`
        /// borrows the font, so storage has to outlive registration, and a context re-created by
        /// `UiContext::ensure_ready` forgets every previously registered font, so the whole set is
        /// replayed on every `ui_run_frame` call rather than trusted to have survived.
        struct FontRegistration {
            SFT::UI::FontId font_id = 0;
            std::unique_ptr<SFT::Text::Font> font;
        };

        std::mutex g_font_mutex;
        std::vector<FontRegistration> g_fonts;

        void apply_font_registrations(SFT::UI::Context &context) {
            const std::lock_guard<std::mutex> lock{g_font_mutex};
            for (const FontRegistration &entry : g_fonts) {
                context.register_font(entry.font_id, *entry.font);
            }
        }

        /// The most recently finished frame's overlay hooks, awaiting `ui_take_pending_overlay_hooks`.
        std::mutex g_pending_mutex;
        std::optional<SFT::Renderer::UiOverlayHooks> g_pending_overlay;

        void reset_session() noexcept {
            // Destroyed innermost-first so each scope closes the element it opened, which is the
            // order the layout expects even when the draw hook left elements unbalanced.
            while (!g_session.open_elements.empty()) {
                g_session.open_elements.pop_back();
            }
            g_session.open = false;
            g_session.context = nullptr;
        }

        SFT::UI::Color to_engine_color(const std::array<float, 4> &rgba) noexcept {
            return SFT::UI::Color{static_cast<SFT::f64>(rgba[0]), static_cast<SFT::f64>(rgba[1]),
                                  static_cast<SFT::f64>(rgba[2]), static_cast<SFT::f64>(rgba[3])};
        }

        SFT::UI::SizingAxis to_engine_axis(UiSizing kind, float value) noexcept {
            switch (kind) {
            case UiSizing::Grow: return SFT::UI::SizingAxis::grow();
            case UiSizing::Fixed: return SFT::UI::SizingAxis::fixed(value);
            case UiSizing::Percent: return SFT::UI::SizingAxis::percent(value);
            case UiSizing::Fit:
            default: return SFT::UI::SizingAxis::fit();
            }
        }

        // The bridge enums below are declared in the engine's own variant order, so the
        // underlying-value casts in to_element_decl are exact; these catch either side drifting.
        static_assert(static_cast<int>(SFT::UI::AlignX::Right) == static_cast<int>(UiAlignX::Right));
        static_assert(static_cast<int>(SFT::UI::AlignY::Bottom) == static_cast<int>(UiAlignY::Bottom));
        static_assert(static_cast<int>(SFT::UI::CursorIcon::NotAllowed) == static_cast<int>(UiCursor::NotAllowed));
        static_assert(static_cast<int>(SFT::UI::FloatingAttachTo::Root) == static_cast<int>(UiFloatingAttachTo::Root));
        static_assert(static_cast<int>(SFT::UI::FloatingAttachPoint::RightBottom) ==
                      static_cast<int>(UiAttachPoint::RightBottom));
        static_assert(static_cast<int>(SFT::UI::Docking::DockDropZone::Bottom) == static_cast<int>(UiDockZone::Bottom));

        SFT::UI::ElementDecl to_element_decl(const UiElementDesc &desc) {
            SFT::UI::ElementDecl decl{};
            decl.sizing = SFT::UI::Sizing{to_engine_axis(desc.width_kind, desc.width_value),
                                          to_engine_axis(desc.height_kind, desc.height_value)};
            decl.padding = SFT::UI::Padding{desc.padding_left, desc.padding_right, desc.padding_top,
                                            desc.padding_bottom};
            decl.child_gap = desc.child_gap;
            decl.direction = desc.direction == UiDirection::TopToBottom ? SFT::UI::LayoutDirection::TopToBottom
                                                                        : SFT::UI::LayoutDirection::LeftToRight;
            decl.background_color = to_engine_color(desc.background);
            decl.corner_radius = SFT::UI::CornerRadius{desc.corner_radius[0], desc.corner_radius[1],
                                                        desc.corner_radius[2], desc.corner_radius[3]};
            decl.clip = SFT::UI::ClipConfig{desc.clip_horizontal, desc.clip_vertical};
            if (!desc.id.empty()) {
                decl.id = SFT::UString{std::string_view{desc.id.data(), desc.id.size()}};
            }
            decl.child_alignment.x = static_cast<SFT::UI::AlignX>(static_cast<std::uint8_t>(desc.align_x));
            decl.child_alignment.y = static_cast<SFT::UI::AlignY>(static_cast<std::uint8_t>(desc.align_y));
            decl.border.color = to_engine_color(desc.border_color);
            decl.border.width.left = desc.border_width[0];
            decl.border.width.right = desc.border_width[1];
            decl.border.width.top = desc.border_width[2];
            decl.border.width.bottom = desc.border_width[3];
            decl.border.width.between_children = desc.border_width[4];
            decl.z = desc.z;
            decl.cursor = static_cast<SFT::UI::CursorIcon>(static_cast<std::uint8_t>(desc.cursor));
            if (!desc.debug_label.empty()) {
                decl.debug_label = SFT::UString{std::string_view{desc.debug_label.data(), desc.debug_label.size()}};
            }
            const UiFloating &f = desc.floating;
            decl.floating.attach_to = static_cast<SFT::UI::FloatingAttachTo>(static_cast<std::uint8_t>(f.attach_to));
            if (!f.parent_id.empty()) {
                decl.floating.parent_id = SFT::UString{std::string_view{f.parent_id.data(), f.parent_id.size()}};
            }
            decl.floating.element_attach_point =
                static_cast<SFT::UI::FloatingAttachPoint>(static_cast<std::uint8_t>(f.element_attach_point));
            decl.floating.parent_attach_point =
                static_cast<SFT::UI::FloatingAttachPoint>(static_cast<std::uint8_t>(f.parent_attach_point));
            decl.floating.offset = glm::vec2{f.offset[0], f.offset[1]};
            decl.floating.z_index = f.z_index;
            decl.floating.capture_pointer = f.capture_pointer;
            decl.floating.clip_to = f.clip_to_attached_parent ? SFT::UI::FloatingClipTo::AttachedParent
                                                              : SFT::UI::FloatingClipTo::None;
            return decl;
        }

        SFT::Renderer::TextureHandle to_texture_handle(UiTexture texture) noexcept {
            return SFT::Renderer::TextureHandle{texture.value};
        }

    } // namespace

    void ui_set_draw_hook(rust::Box<UiDrawHandle> hook) {
        g_draw_hook.emplace(std::move(hook));
    }

    void ui_clear_draw_hook() noexcept {
        g_draw_hook.reset();
    }

    bool ui_register_font(EngineView &engine, rust::Str path, std::uint16_t font_id) {
        try {
            const std::string source{path.data(), path.size()};
            const std::optional<std::string> bytes = SFT::Foundation::read_file_to_string(source);
            if (!bytes) {
                return false;
            }
            const std::span<const char> chars{bytes->data(), bytes->size()};
            auto loaded = SFT::Text::Font::load(std::as_bytes(chars));
            if (!loaded) {
                return false;
            }
            const SFT::UI::FontId id = static_cast<SFT::UI::FontId>(font_id);
            auto owned = std::make_unique<SFT::Text::Font>(std::move(*loaded));
            {
                const std::lock_guard<std::mutex> lock{g_font_mutex};
                auto existing = std::find_if(g_fonts.begin(), g_fonts.end(),
                                             [id](const FontRegistration &entry) { return entry.font_id == id; });
                if (existing != g_fonts.end()) {
                    existing->font = std::move(owned);
                } else {
                    g_fonts.push_back(FontRegistration{.font_id = id, .font = std::move(owned)});
                }
            }
            apply_font_registrations(engine.ui_context().context());
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_run_frame(EngineView &engine, std::uint32_t framebuffer_width,
                      std::uint32_t framebuffer_height, double delta_seconds) {
        if (!g_draw_hook.has_value()) {
            return false;
        }
        try {
            SFT::RHI::RhiDevice *device = engine.rhi_device();
            if (device == nullptr) {
                return false;
            }
            // Matches the format the presentation path uses, so the overlay composites without a
            // conversion the renderer would otherwise have to insert (see FFI/src/FFI/Ui.cpp).
            const SFT::RHI::Format color_format = engine.config().features.presentation.hdr_enabled
                                                       ? SFT::RHI::Format::RGBA16Float
                                                       : SFT::RHI::Format::BGRA8UnormSrgb;
            if (!engine.ui_context().ensure_ready(*device, color_format)) {
                return false;
            }
            apply_font_registrations(engine.ui_context().context());

            const glm::vec2 viewport{static_cast<float>(framebuffer_width), static_cast<float>(framebuffer_height)};
            engine.ui_context().begin_layout(viewport, engine.ui_pointer_state(), static_cast<float>(delta_seconds));

            g_session.open = true;
            g_session.context = &engine.ui_context().context();
            g_session.viewport = viewport;

            ui_invoke_draw_hook(**g_draw_hook, engine);

            reset_session();

            auto snapshot = std::make_shared<SFT::UI::FrameSnapshot>(
                engine.ui_context().context().finish_frame(viewport));
            SFT::Renderer::UiOverlayHooks hooks =
                engine.ui_context().build_overlay_hooks(std::move(snapshot), engine.renderer());
            {
                const std::lock_guard<std::mutex> lock{g_pending_mutex};
                g_pending_overlay = std::move(hooks);
            }
            return true;
        } catch (...) {
            reset_session();
            return false;
        }
    }

    bool ui_begin_element(const UiElementDesc &desc) {
        if (!g_session.open) {
            return false;
        }
        try {
            const SFT::UI::ElementDecl decl = to_element_decl(desc);
            g_session.open_elements.push_back(
                std::make_unique<SFT::UI::ElementScope>(g_session.context->element(decl)));
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_end_element() {
        if (!g_session.open || g_session.open_elements.empty()) {
            return false;
        }
        g_session.open_elements.pop_back();
        return true;
    }

    bool ui_text(rust::Str text, const UiTextStyle &style) {
        if (!g_session.open) {
            return false;
        }
        try {
            SFT::UI::TextStyle engine_style{};
            engine_style.color = to_engine_color(style.color);
            engine_style.font_id = static_cast<SFT::UI::FontId>(style.font_id);
            engine_style.font_size = style.font_size;
            g_session.context->text(SFT::ustr{std::string_view{text.data(), text.size()}}, engine_style);
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_image(const UiElementDesc &desc, UiTexture texture) {
        if (!g_session.open) {
            return false;
        }
        try {
            g_session.context->image(to_element_decl(desc), to_texture_handle(texture));
            return true;
        } catch (...) {
            return false;
        }
    }

    UiSvgOutcome ui_load_svg(EngineView &engine, rust::Str path, float target_px) {
        UiSvgOutcome outcome{};
        try {
            const std::filesystem::path source{std::string{path.data(), path.size()}};
            const auto result = engine.ui_svg_cache().resolve(engine.assets(), source, target_px);
            if (!result) {
                const auto view = result.error().message.cpp_string_view();
                outcome.ok = false;
                outcome.message = rust::String::lossy(view.data(), view.size());
                return outcome;
            }
            outcome.ok = true;
            outcome.texture = UiTexture{result->value};
            return outcome;
        } catch (const std::exception &e) {
            outcome.ok = false;
            outcome.message = rust::String::lossy(e.what());
            return outcome;
        } catch (...) {
            outcome.ok = false;
            outcome.message = rust::String{"an unexpected C++ exception was caught at the FFI boundary"};
            return outcome;
        }
    }

    bool ui_svg(const UiElementDesc &desc, UiTexture texture) {
        if (!g_session.open) {
            return false;
        }
        try {
            g_session.context->svg(to_element_decl(desc), to_texture_handle(texture));
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_hovered(rust::Str id) {
        if (!g_session.open) {
            return false;
        }
        return g_session.context->hovered(SFT::UString{std::string_view{id.data(), id.size()}});
    }

    bool ui_clicked(rust::Str id) {
        if (!g_session.open) {
            return false;
        }
        return g_session.context->clicked(SFT::UString{std::string_view{id.data(), id.size()}});
    }

    std::array<float, 2> ui_pointer_position() noexcept {
        if (!g_session.open) {
            return {0.0f, 0.0f};
        }
        const glm::vec2 position = g_session.context->pointer_position();
        return {position.x, position.y};
    }

    bool ui_pointer_is_down() noexcept {
        return g_session.open && g_session.context->pointer_is_down();
    }

    UiPointerSnapshot ui_pointer_state(const EngineView &engine) noexcept {
        const E::UiPointerState &pointer = engine.ui_pointer_state();
        const SFT::UI::PointerState &state = pointer.state();
        UiPointerSnapshot snapshot{};
        snapshot.position = {state.position.x, state.position.y};
        snapshot.down = state.down;
        snapshot.pressed_this_frame = state.pressed;
        snapshot.released_this_frame = state.released;
        snapshot.cancelled_this_frame = state.cancelled;
        snapshot.has_press_position = state.press_position.has_value();
        if (state.press_position) {
            snapshot.press_position = {state.press_position->x, state.press_position->y};
        } else {
            snapshot.press_position = {0.0f, 0.0f};
        }
        snapshot.scroll_delta = {state.scroll_delta.x, state.scroll_delta.y};
        snapshot.consumed = pointer.consumed();
        return snapshot;
    }

    UiTextInputSnapshot ui_text_input_state(const EngineView &engine) {
        const E::UiTextInputState &input = engine.ui_text_input_state();
        const SFT::UI::TextEditInput frame_input = input.frame_input();
        UiTextInputSnapshot snapshot{};
        snapshot.typed_text = rust::String::lossy(frame_input.typed_text.data(), frame_input.typed_text.size());
        snapshot.composing = frame_input.composing;
        snapshot.composition_text =
            rust::String::lossy(frame_input.composition_text.data(), frame_input.composition_text.size());
        return snapshot;
    }

    void ui_focus(rust::Str id) {
        if (!g_session.open) {
            return;
        }
        try {
            g_session.context->focus(SFT::UString{std::string_view{id.data(), id.size()}});
        } catch (...) {
            // Focus is best-effort UI state, not something a caller can react to failing.
        }
    }

    bool ui_has_focus(rust::Str id) {
        if (!g_session.open) {
            return false;
        }
        return g_session.context->has_focus(SFT::UString{std::string_view{id.data(), id.size()}});
    }

    bool ui_focused() {
        if (!g_session.open) {
            return false;
        }
        return g_session.context->focused();
    }

    void ui_clear_focus(rust::Str id) {
        if (!g_session.open) {
            return;
        }
        g_session.context->clear_focus(SFT::UString{std::string_view{id.data(), id.size()}});
    }

    UiScrollMetrics ui_scroll_metrics(rust::Str container_id) {
        UiScrollMetrics metrics{};
        if (!g_session.open) {
            return metrics;
        }
        const SFT::UI::Context::ScrollMetrics engine_metrics =
            g_session.context->scroll_metrics(SFT::UString{std::string_view{container_id.data(), container_id.size()}});
        metrics.found = engine_metrics.found;
        metrics.offset = {engine_metrics.offset.x, engine_metrics.offset.y};
        metrics.content_size = {engine_metrics.content_size.x, engine_metrics.content_size.y};
        metrics.container_size = {engine_metrics.container_size.x, engine_metrics.container_size.y};
        metrics.horizontal = engine_metrics.horizontal;
        metrics.vertical = engine_metrics.vertical;
        return metrics;
    }

    bool ui_set_scroll_offset(rust::Str container_id, std::array<float, 2> offset) {
        if (!g_session.open) {
            return false;
        }
        return g_session.context->set_scroll_offset(
            SFT::UString{std::string_view{container_id.data(), container_id.size()}},
            glm::vec2{offset[0], offset[1]});
    }

    std::optional<SFT::Renderer::UiOverlayHooks> ui_take_pending_overlay_hooks() noexcept {
        const std::lock_guard<std::mutex> lock{g_pending_mutex};
        std::optional<SFT::Renderer::UiOverlayHooks> taken = std::move(g_pending_overlay);
        g_pending_overlay.reset();
        return taken;
    }


    namespace {

        std::vector<glm::vec2> to_points(rust::Slice<const float> flat) {
            std::vector<glm::vec2> points;
            points.reserve(flat.size() / 2);
            for (std::size_t i = 0; i + 1 < flat.size(); i += 2) {
                points.emplace_back(flat[i], flat[i + 1]);
            }
            return points;
        }

        std::vector<glm::vec2> to_points(const rust::Vec<float> &flat) {
            return to_points(rust::Slice<const float>{flat.data(), flat.size()});
        }

        SFT::UI::StrokeStyle to_engine(const UiStrokeStyle &style) noexcept {
            SFT::UI::StrokeStyle out{};
            out.color = to_engine_color(style.color);
            out.width = style.width;
            out.feather_px = style.feather_px;
            out.dash_length = style.dash_length;
            out.dash_gap = style.dash_gap;
            out.cap = style.cap == UiStrokeCap::Butt     ? SFT::UI::StrokeCapKind::Butt
                      : style.cap == UiStrokeCap::Square ? SFT::UI::StrokeCapKind::Square
                                                         : SFT::UI::StrokeCapKind::Round;
            out.join = style.join == UiStrokeJoin::Miter   ? SFT::UI::StrokeJoinKind::Miter
                       : style.join == UiStrokeJoin::Bevel ? SFT::UI::StrokeJoinKind::Bevel
                                                           : SFT::UI::StrokeJoinKind::Round;
            out.snap_to_pixel_grid = style.snap_to_pixel_grid;
            out.glow_intensity = style.glow_intensity;
            return out;
        }

        SFT::UI::CustomShaderRef to_engine(const UiCustomShader &shader) {
            SFT::UI::CustomShaderRef out{};
            out.shader_path = std::string{shader.shader_path};
            out.module_name = std::string{shader.module_name};
            if (!shader.fragment_entry_point.empty()) {
                out.fragment_entry_point = std::string{shader.fragment_entry_point};
            }
            out.push_constants.reserve(shader.push_constants.size());
            for (std::uint8_t byte : shader.push_constants) {
                out.push_constants.push_back(static_cast<std::byte>(byte));
            }
            return out;
        }

    } // namespace

    bool ui_stroke_paths(const UiElementDesc &desc, rust::Slice<const UiStrokePath> paths) {
        if (!g_session.open) {
            return false;
        }
        try {
            std::vector<SFT::UI::StrokePath> converted;
            converted.reserve(paths.size());
            for (const UiStrokePath &path : paths) {
                converted.push_back(SFT::UI::StrokePath{to_points(path.points), to_engine(path.style)});
            }
            g_session.context->stroke_paths(to_element_decl(desc), converted);
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_fill_quads(const UiElementDesc &desc, rust::Slice<const UiFillQuad> quads) {
        if (!g_session.open) {
            return false;
        }
        try {
            std::vector<SFT::UI::FillQuad> converted;
            converted.reserve(quads.size());
            for (const UiFillQuad &q : quads) {
                SFT::UI::FillQuad out{};
                out.position = glm::vec2{q.position[0], q.position[1]};
                out.size = glm::vec2{q.size[0], q.size[1]};
                out.color = to_engine_color(q.color);
                out.corner_radius = SFT::UI::CornerRadius{q.corner_radius[0], q.corner_radius[1], q.corner_radius[2],
                                                          q.corner_radius[3]};
                converted.push_back(out);
            }
            g_session.context->fill_quads(to_element_decl(desc), converted);
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_fill_sectors(const UiElementDesc &desc, rust::Slice<const UiSector> sectors) {
        if (!g_session.open) {
            return false;
        }
        try {
            std::vector<SFT::UI::Sector> converted;
            converted.reserve(sectors.size());
            for (const UiSector &sector : sectors) {
                SFT::UI::Sector out{};
                out.center = glm::vec2{sector.center[0], sector.center[1]};
                out.inner_radius = sector.inner_radius;
                out.outer_radius = sector.outer_radius;
                out.start_angle = sector.start_angle;
                out.end_angle = sector.end_angle;
                out.style.color = to_engine_color(sector.color);
                out.style.feather_px = sector.feather_px;
                converted.push_back(out);
            }
            g_session.context->fill_sectors(to_element_decl(desc), converted);
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_begin_custom_element(const UiElementDesc &desc, const UiCustomShader &shader) {
        if (!g_session.open) {
            return false;
        }
        try {
            g_session.open_elements.push_back(std::make_unique<SFT::UI::ElementScope>(
                g_session.context->custom_element(to_element_decl(desc), to_engine(shader))));
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_stroke_custom(const UiElementDesc &desc, rust::Slice<const float> points, float half_width, float feather_px,
                          const UiCustomShader &shader) {
        if (!g_session.open) {
            return false;
        }
        try {
            const std::vector<glm::vec2> converted = to_points(points);
            g_session.context->stroke_custom(to_element_decl(desc), converted, half_width, feather_px, to_engine(shader));
            return true;
        } catch (...) {
            return false;
        }
    }

    namespace {

        std::string to_std(const rust::String &text) {
            return std::string{text.data(), text.size()};
        }

        SFT::UI::AxisConfig to_engine(const UiGraphAxis &axis) {
            SFT::UI::AxisConfig out{};
            out.scale.kind = axis.scale == UiScaleKind::Log      ? SFT::UI::ScaleKind::Log
                             : axis.scale == UiScaleKind::Symlog ? SFT::UI::ScaleKind::Symlog
                                                                 : SFT::UI::ScaleKind::Linear;
            out.scale.log_base = axis.log_base;
            out.scale.symlog_linear_threshold = axis.symlog_linear_threshold;
            if (axis.has_min) {
                out.min = axis.min;
            }
            if (axis.has_max) {
                out.max = axis.max;
            }
            out.autoscale_padding_percent = axis.autoscale_padding_percent;
            out.target_tick_count = axis.target_tick_count;
            out.show_gridlines = axis.show_gridlines;
            out.show_minor_gridlines = axis.show_minor_gridlines;
            out.axis_color = to_engine_color(axis.axis_color);
            out.gridline_color = to_engine_color(axis.gridline_color);
            out.minor_gridline_color = to_engine_color(axis.minor_gridline_color);
            out.title = to_std(axis.title);
            out.is_categorical = axis.is_categorical;
            out.categories.reserve(axis.categories.size());
            for (const rust::String &category : axis.categories) {
                out.categories.push_back(to_std(category));
            }
            return out;
        }

    } // namespace

    bool ui_graph(const UiElementDesc &desc, const UiGraphDesc &graph) {
        if (!g_session.open) {
            return false;
        }
        try {
            SFT::UI::GraphDesc out{};
            switch (graph.graph_type) {
            case UiGraphType::Area: out.type = SFT::UI::GraphType::Area; break;
            case UiGraphType::Bar: out.type = SFT::UI::GraphType::Bar; break;
            case UiGraphType::Scatter: out.type = SFT::UI::GraphType::Scatter; break;
            case UiGraphType::Pie: out.type = SFT::UI::GraphType::Pie; break;
            case UiGraphType::Line:
            default: out.type = SFT::UI::GraphType::Line; break;
            }
            out.x_axis = to_engine(graph.x_axis);
            out.y_axis = to_engine(graph.y_axis);
            // SeriesRef borrows x/y as spans; `graph` (and its rust::Vecs) outlives this call.
            out.series.reserve(graph.series.size());
            for (const UiGraphSeries &series : graph.series) {
                SFT::UI::SeriesRef ref{};
                ref.name = to_std(series.name);
                ref.x = std::span<const double>{series.x.data(), series.x.size()};
                ref.y = std::span<const double>{series.y.data(), series.y.size()};
                ref.color = to_engine_color(series.color);
                ref.line_width = series.line_width;
                ref.feather_px = series.feather_px;
                ref.area_fill_opacity = series.area_fill_opacity;
                ref.marker_radius = series.marker_radius;
                ref.glow_intensity = series.glow_intensity;
                out.series.push_back(std::move(ref));
            }
            out.bar_stack_mode = graph.bar_stack_mode == UiBarStackMode::Stacked ? SFT::UI::BarStackMode::Stacked
                                                                                 : SFT::UI::BarStackMode::Grouped;
            out.bar_group_gap_fraction = graph.bar_group_gap_fraction;
            out.bar_series_gap_fraction = graph.bar_series_gap_fraction;
            out.pie_slices.reserve(graph.pie_slices.size());
            for (const UiPieSlice &slice : graph.pie_slices) {
                out.pie_slices.push_back(SFT::UI::PieSlice{to_std(slice.name), slice.value, to_engine_color(slice.color)});
            }
            out.pie_style.hole_ratio = graph.pie_hole_ratio;
            out.pie_style.start_angle_degrees = graph.pie_start_angle_degrees;
            out.pie_style.gap_degrees = graph.pie_gap_degrees;
            out.pie_style.feather_px = graph.pie_feather_px;
            out.background_color = to_engine_color(graph.background);
            out.corner_radius = SFT::UI::CornerRadius{graph.corner_radius[0], graph.corner_radius[1],
                                                      graph.corner_radius[2], graph.corner_radius[3]};
            out.axis_margin_left = graph.axis_margins[0];
            out.axis_margin_bottom = graph.axis_margins[1];
            out.axis_margin_top = graph.axis_margins[2];
            out.axis_margin_right = graph.axis_margins[3];
            out.font_id = static_cast<SFT::UI::FontId>(graph.font_id);
            out.label_font_size = graph.label_font_size;
            out.title_font_size = graph.title_font_size;
            out.show_legend = graph.show_legend;

            SFT::UI::GraphState state{};
            return SFT::UI::graph(*g_session.context, to_element_decl(desc), out, state).drawn;
        } catch (...) {
            return false;
        }
    }

    namespace {
        namespace Dock = SFT::UI::Docking;

        Dock::DockPanelId to_panel_id(rust::Str id) {
            return SFT::UString{std::string_view{id.data(), id.size()}};
        }

        rust::String to_rust(const SFT::UString &text) {
            const auto view = text.cpp_string_view();
            return rust::String::lossy(view.data(), view.size());
        }
    } // namespace

    std::unique_ptr<DockWorkspace> ui_dock_workspace_new(rust::Str id_prefix) {
        return std::make_unique<DockWorkspace>(SFT::UString{std::string_view{id_prefix.data(), id_prefix.size()}});
    }

    bool ui_dock_add_panel(DockWorkspace &workspace, rust::Str id, rust::Str title, bool closable,
                           const UiDockPlacement &placement) {
        try {
            Dock::DockPanelDesc desc{};
            desc.id = to_panel_id(id);
            desc.title = SFT::UString{std::string_view{title.data(), title.size()}};
            desc.closable = closable;
            std::optional<Dock::DockPlacement> engine_placement;
            if (placement.has_placement) {
                engine_placement = Dock::DockPlacement{
                    static_cast<Dock::DockNodeId>(placement.target_node),
                    static_cast<Dock::DockDropZone>(static_cast<std::uint8_t>(placement.zone))};
            }
            return workspace.add_panel(std::move(desc), engine_placement);
        } catch (...) {
            return false;
        }
    }

    void ui_dock_remove_panel(DockWorkspace &workspace, rust::Str id) {
        workspace.remove_panel(to_panel_id(id));
    }

    bool ui_dock_has_panel(const DockWorkspace &workspace, rust::Str id) {
        return workspace.has_panel(to_panel_id(id));
    }

    bool ui_dock_is_empty(const DockWorkspace &workspace) noexcept {
        return workspace.empty();
    }

    std::int64_t ui_dock_focused_leaf(const DockWorkspace &workspace) noexcept {
        const auto leaf = workspace.focused_leaf();
        return leaf ? static_cast<std::int64_t>(static_cast<std::uint32_t>(*leaf)) : -1;
    }

    void ui_dock_set_content_background(DockWorkspace &workspace, std::array<float, 4> color) noexcept {
        workspace.set_content_background(to_engine_color(color));
    }

    bool ui_dock_begin_frame(DockWorkspace &workspace, std::array<float, 4> rect, float delta_seconds) {
        if (!g_session.open) {
            return false;
        }
        try {
            workspace.begin_frame(*g_session.context,
                                  Dock::DockRect{glm::vec2{rect[0], rect[1]}, glm::vec2{rect[2], rect[3]}},
                                  delta_seconds);
            return true;
        } catch (...) {
            return false;
        }
    }

    bool ui_dock_begin_panel_content(const DockWorkspace &workspace, rust::Str id) {
        if (!g_session.open) {
            return false;
        }
        try {
            const std::optional<SFT::UI::ElementDecl> region = workspace.panel_content_region(to_panel_id(id));
            if (!region) {
                return false;
            }
            g_session.open_elements.push_back(
                std::make_unique<SFT::UI::ElementScope>(g_session.context->element(*region)));
            return true;
        } catch (...) {
            return false;
        }
    }

    UiDockEvents ui_dock_end_frame(DockWorkspace &workspace) {
        UiDockEvents out{};
        if (!g_session.open) {
            return out;
        }
        try {
            const Dock::DockWorkspaceEvents events = workspace.end_frame(*g_session.context);
            for (const Dock::DockTearOffRequest &request : events.tear_off_requests) {
                out.tear_off_panels.push_back(to_rust(request.panel));
                out.tear_off_positions.push_back(request.workspace_local_drop_position.x);
                out.tear_off_positions.push_back(request.workspace_local_drop_position.y);
            }
            for (const Dock::DockPanelId &panel : events.close_requests) {
                out.close_requests.push_back(to_rust(panel));
            }
        } catch (...) {
        }
        return out;
    }

} // namespace sturdy_rs::ui
